### ISSUE TITLE
Eslint does not reload dependencies after installing a new package ('X' should be listed in the project's dependencies)

### ISSUE THREAD

**Issue by hongz1** [microsoft/vscode-eslint#1821] opened 2024-04-03 18:30 UTC
I remotely connect vscode projects via ssh (Ubuntu server) and I know this wasn't happened before.

1. opened existing project via ssh (eslint extension is installed into both local and server sides)
2. installed a new package.
3. imported package.

This error message showed:
`'http-status-codes' should be listed in the project's dependencies. Run 'npm i -S http-status-codes' to add it`

![image](https://github.com/microsoft/vscode-eslint/assets/6565136/1bc72638-2597-4531-baa5-1d156df16470)

When I disconnect and connect again, this error message is gone.

![image](https://github.com/microsoft/vscode-eslint/assets/6565136/3522827a-6ffc-4f4a-b115-ceac9f3da566)

This is so annoying because I have to reconnect whenever I install a new package.

Is there a way to fix this? or Is this a bug???

**Comment by dbaeumer** [comment] 2024-04-04 07:18
This is very hard to fix since ESLint doesn't offer any API to find out when a file should be validated, especially when a file A depends on an external dependency D.

The next version of ESLint extension (available as a pre-release already) has two ways to improve this:

- files will be validated on focus gain
- a command to re-validate all open files

This will avoid that you need to reconnect to the server.

I will close the issue since without new API from ESLint there is little I can do to make this correct in all cases.

**Closed by dbaeumer** 2024-04-04 07:18 UTC

**Comment by justfalter** [comment] 2024-07-31 21:46
This happens to me locally, with no SSH involved. To reiterate, the issue is:

1. Open up vscode on existing project.
2. Open up a file that is linted by eslint.
3. Add a new dependency (ex: `npm install --save tmp`).
4. Return to vscode and add `import * as tmp from 'tmp'` 
5. vscode eslint complains that the `tmp` doesn't exist as a dependency.

The only resolution is to restart the Eslint server, which is effectively what  hongz1  is doing by re-connecting via SSH.

> This is very hard to fix since ESLint doesn't offer any API to find out when a file should be validated, especially when a file A depends on an external dependency D.

@dbaeumer I don't see how this is related --- It seems to me that the problem is simply that the VSCode ESLint server should know to restart itself when the dependencies in a package.json have been modified?  This is essentially what we are having to do right now.
