### ISSUE TITLE
Error in vue/valid-v-slot rule

### ISSUE THREAD

**Issue by nbiriukov** [microsoft/vscode-eslint#1263] opened 2021-05-19 06:47 UTC
VSCode: 1.56.1 
ESLint plugin for VSCode: 2.1.20
Dependencies in package.json:

  "devDependencies": {
    "@vue/cli-plugin-eslint": "^4.4.0",
    "@vue/eslint-config-airbnb": "^5.0.2",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-vue": "^7.9.0",
    ...
  }

WebStorm works with my configuration fine, but VSCode detects errors in such code: `<template v-slot:item.actions="{ item }">`. It shows a message: `[vue/valid-v-slot] 'v-slot' directive doesn't support any modifier.`. But eslint does not find any error when I start my application or run "vue-cli-service lint". WebStorm pass this code too. Here is my .eslintrc.js:

module.exports = {
  ...
  extends: ["plugin:vue/essential"],
  parserOptions: {
    parser: "babel-eslint"
  },
  rules: {
    ...
    'vue/valid-v-slot': 'off',
  },
};

To ensure that eslint plugin in VSCode sees eslintrc, I added `no-console: "error"` rule to eslintrc and `console.log()` to the component where I got vue/valid-v-slot error. Than, I got an error in WebStorm and VSCode both. So, eslint plugin in VSCode load rules from eslintrc but not work properly with 'vue/valid-v-slot' rule. How to fix it?

**Comment by dbaeumer** [comment] 2021-05-19 14:41
@nbiriukov can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by nbiriukov** [comment] 2021-05-19 14:48
Sorry, but I can't. I'll try to reproduce that errors on empty project later.

**Comment by dbaeumer** [comment] 2021-05-20 06:48
Thanks.

**Comment by mariuszmikolajczak** [comment] 2021-05-21 19:37
I have this same problem:
`.eslintrc.js`
```
export default {
  env: {
    node: true
  },
  extends: ["plugin:vue/essential", "plugin:prettier/recommended"],
  rules: {
    "vue/valid-v-slot": [
      "error",
      {
        allowModifiers: true
      }
    ],
    "comma-dangle": ["error", "never"],
    "prettier/prettier": ["error", { trailingComma: "none" }]
  }
};
```
eslint on command line is not finding any errors, but on VSCode:
<img width="528" alt="Screenshot 2021-05-21 at 21 35 45" src="https://user-images.githubusercontent.com/1331758/119189709-af9dd680-ba7c-11eb-92ae-dd477cf73ab2.png">

**Comment by mariuszmikolajczak** [comment] 2021-05-22 23:21
@dbaeumer I created empty Vue.js project that can be used  to reproduce problem with VSCode plugin. https://github.com/mariuszmikolajczak/vscode-eslint-example

This line should be red on VS Code https://github.com/mariuszmikolajczak/vscode-eslint-example/blob/master/src/App.vue#L5 but doesnt seems to be problem on console when running `yarn lint`.

<img width="360" alt="Screenshot 2021-05-23 at 01 12 33" src="https://user-images.githubusercontent.com/1331758/119243213-ff57cd00-bb64-11eb-9e75-12821e712d8b.png">
<img width="666" alt="Screenshot 2021-05-23 at 01 12 43" src="https://user-images.githubusercontent.com/1331758/119243218-07b00800-bb65-11eb-951b-3db5efe40064.png">

**Comment by dbaeumer** [comment] 2021-05-25 19:24
@mariuszmikolajczak not sure I understand everything. If you expect an error in the console (via `yarn lint`) then this is a problem of the eslint configuration itself. VS Code doesn't influence the execution in the terminal. Only inside the editor.

**Comment by mariuszmikolajczak** [comment] 2021-05-28 12:39
@dbaeumer Yes sorry my english was pretty bad, but I mean exact opposite. I expect VSCode to respect what `yarn lint` is doing (in this example eslint). Why VSCode is displaying me an error if eslint not?

Here you have rule that VSCode doesn't respect: https://github.com/mariuszmikolajczak/vscode-eslint-example/blob/master/package.json#L40

It doesn't matter if I configure it on `package.json` or in `.eslintrc` VSCode doesn't care.

Now am I clear?

**Comment by dbaeumer** [comment] 2021-05-28 14:14
Yes, you are.

**Comment by dbaeumer** [comment] 2021-06-02 14:04
It took me a long time to understand what is going on but the specific error is not produced by the eslint extension. All errors from the eslint extension have the source `eslint`. The one comes from `eslint-plugin-vue` and I don't know who is generating that message. 

<img width="446" alt="capture" src="https://user-images.githubusercontent.com/1931590/120494299-fca67480-c3bb-11eb-9e06-b0bb75464503.png">

I even debugged the example and the eslint extension is not producing this error

<img width="501" alt="capture" src="https://user-images.githubusercontent.com/1931590/120494566-35dee480-c3bc-11eb-89e9-24eb3b11f50a.png">

Closing the issue.

**Closed by dbaeumer** 2021-06-02 14:04 UTC
Labels: needs more info

**Comment by mariuszmikolajczak** [comment] 2021-06-09 15:30
@dbaeumer I like your engagement to actually find the issue. 😂 "Ah this is something different closing". What I recall `eslint-plugin-vue` is not a VSCode plugin but eslint plugin, but maybe I'm not fully aware how this Microsoft thing is working. Anyway thank you for looking at this.

**Comment by dbaeumer** [comment] 2021-06-09 15:42
I haven't digged deeper but I guess that this comes from some VUE plugin. The screen shot of the debugger shows the errors the ESLint extension is producing.

A good way to find the extension is using VS Code's extension bisect https://code.visualstudio.com/blogs/2021/02/16/extension-bisect#:~:text=The%20Extension%20bisect%20utility%20in%20VS%20Code%20was,know%20that%20the%20iterative%20approach%20requires%208%20steps.

**Comment by HansCronau** [comment] 2021-08-05 16:52
@mariuszmikolajczak Are you using Vetur? `eslint-plugin-vue` does not play well with Vetur's default settings.

> You need to turn off Vetur's template validation by adding `vetur.validation.template: false` to your `.vscode/settings.json`.

Source: https://eslint.vuejs.org/user-guide/#trouble-with-visual-studio-code
