### ISSUE TITLE
After upgrade to version 3.x, json files are broken

### ISSUE THREAD

**Issue by yp05327** [microsoft/vscode-eslint#1876] opened 2024-06-19 00:23 UTC
It works well in 2.4.4, but after I upgrade to the latest 3.x.x, it seems that it will lint all `.json` as `js/ts` file
In 2.4.4:
![image](https://github.com/microsoft/vscode-eslint/assets/18380374/c3b49197-0843-49af-af3e-603811c057ba)
In 3.0.8 and 3.0.10:
![image](https://github.com/microsoft/vscode-eslint/assets/18380374/a37e9da7-09c2-46d4-9508-f30ed6c40c08)

**Comment by dbaeumer** [comment] 2024-06-19 06:33
I tried to reproduce this but failed. A GitHub repository to clone is highly appreciated.

**Comment by yp05327** [comment] 2024-06-20 01:33
I'm using a payed VUE template, so I can't push all of them. I will try to provide a demo later.

**Comment by yp05327** [comment] 2024-06-20 12:51
@dbaeumer 
I have done. You can clone this repo:
https://github.com/yp05327/eslinterror

Reproduce:
- Open it in dev container
- Run `pnpm install` in terminal
- Reload window (press F1 and select Developer: Reload Window)

Then you can see this issue:
![image](https://github.com/microsoft/vscode-eslint/assets/18380374/e1b3939c-2e8f-49e9-ba42-5c2aa5b402dd)

I notice that the following two things effect this issue:
- You should run `pnpm install`
- You should not delete `.eslintrc.cjs`

I have tested it in my local PC in a clean space again, so I'm sure you can reproduce it.

I didn't modify `.eslintrc.cjs`, but I removed several custom commands in packages.json which will cause error during the installation as not all files are uploaded, and this is not related to this issue

**Comment by dbaeumer** [comment] 2024-06-20 15:12
I was able to reproduce, however the same errors seem to be reported on the command line as well (see screen shot). 

![Image](https://github.com/user-attachments/assets/a1f5d639-f0ab-4dec-83b6-87119d877721)

So there seems to be a more general problem with the setup since this happens independent of the ESLint extension.

**Comment by yp05327** [comment] 2024-06-23 23:47
So this issue comes from eslint self but not the extension?
One thing I don't understand, why after I downgrade the extension, it worked.
And eslint's version is hard coding (in `package.json`), so eslint version and configs are all the same. 
The only difference between these are the extension's version. This seems strange. 🤔

**Comment by dbaeumer** [comment] 2024-06-24 07:44
It sounds strange. May be the extension doesn't work when downgraded :-). Does it work in general?

**Comment by yp05327** [comment] 2024-06-25 08:26
![image](https://github.com/microsoft/vscode-eslint/assets/18380374/575c0e6b-1e3e-4173-8bfc-94c329e605cf)
These two conditions are required.

**Comment by dbaeumer** [comment] 2024-06-25 11:56
I followed these steps and still see the errors both in the editor AND when running eslint directly in the terminal. Since these errors are present in the terminal it is IMO correct that they are shown in the extension as well. 

![Image](https://github.com/user-attachments/assets/e8b346d5-0405-436b-a690-7dac930a0480)

**Comment by yp05327** [comment] 2024-06-25 12:10
If I downgrade the extension, you will see nothing happened, but eslint still reports errors.
![image](https://github.com/microsoft/vscode-eslint/assets/18380374/775940d3-3236-4139-992a-0248b884ecdd)
Maybe it is better to report this issue to eslint not here. 🤔

**Comment by yp05327** [comment] 2024-06-26 02:03
I confirmed that this is partly caused by https://github.com/microsoft/vscode-eslint/pull/1787
In this PR, json files are added. So in 2.x, json files will not be triggered, but in 3.x, it will.

And then because of the bad logic here:
![image](https://github.com/microsoft/vscode-eslint/assets/18380374/0bfa0578-964d-4fb9-9fec-b1580cf13473)
If user didn't even enable the plugins in `.eslintrc.cjs`, extension will still validate these files.
In my case, this project don't use json lint, but it will be detected by the extension.

Maybe a fix can be checking whether user enabled the plugin in eslint config file, then mark `settings.validate` to `on` or `off`.

**Comment by dbaeumer** [comment] 2024-06-26 08:50
Happy to hear you could get it to work

Actually the code checks if the plugin is enabled by loading the configuration of the file. In your setup the following plug-ins are available according the the eslint npm package.

![Image](https://github.com/user-attachments/assets/9730379e-1763-45a2-9493-e53e4e0902e7)

I don't check config files since configuration can come from many many place. So I check what ESLint tells me the configuration looks like.

I think the problem is that `.eslintrc.cjs` files are only honored when running inside a module package. This is why you need to pass it on the command line since it is not the case in the setup of the example repository.

**Comment by dbaeumer** [comment] 2024-06-26 08:50
I double checked the code and IMO it does the right thing.

I will close the issue. Please ping if you think somethings should be done.

**Closed by dbaeumer** 2024-06-26 08:50 UTC
Labels: info-needed

**Comment by yp05327** [comment] 2024-06-26 09:03
Are you sure eslint.plugins means the plugins that user has installed and enabled, but not eslint is providing these plugins?

**Comment by yp05327** [comment] 2024-06-26 09:33
I clean the node_modules, and runned `pnpm install` again. It will install `eslint-plugin-jsonc` for you, even it is not listed in packages.json, that's why jsonc is in eslint.plugins list.
![image](https://github.com/microsoft/vscode-eslint/assets/18380374/d5100e6f-1540-4f58-bb67-76cd8fa740b2)

Maybe it is required by some packages, so installed automatically.
But I don't think it is right to get plugins from the installed plugins list, as in some cases it is not expected.

**Comment by dbaeumer** [comment] 2024-06-26 09:52
But ESLint does the same thing on the command line. Since I use the same code (and I don't want to do my own parsing of config files) I get the same result.

What I can think of is to  enforce the validate setting. If a user has defined it and the file type is not in the list it will not validate the file. This would be an equal behavior as specifying things on the command line.

**Comment by dbaeumer** [comment] 2024-06-26 09:55
I opened https://github.com/microsoft/vscode-eslint/issues/1892 for the validate setting
