### ISSUE TITLE
Adapt ESLint v7 API

### ISSUE THREAD

**Issue by sdalonzo** [microsoft/vscode-eslint#972] opened 2020-05-13 20:41 UTC
With the recent [release of ESLint v7](https://eslint.org/blog/2020/05/eslint-v7.0.0-released#new-eslint-class), `CLIEngine` was deprecated in favor of a new async `ESLint` class: [CLIEngine deprecation notes](https://eslint.org/docs/user-guide/migrating-to-7.0.0#deprecate-cliengine)

I've had some difficulty in getting this to work in VSCode (currently stuck in resolving plugins), and I'm wondering if this extension is currently compatible with ESLint 7 or if there is a roadmap for when that will be ready.

I did search and didn't see any issues related to this, but if I missed something and this is a duplicate, I apologize.

EDIT: I forgot to mention a few other details: This is in a monorepo where I'm passing `eslint.options` a `resolvePluginsRelativeTo`, and the linting does work via CLI (well, via our wrapper which used to implement `CLIEngine` and was just refactored to use `ESLint`.

Thanks!

**Comment by dbaeumer** [comment] 2020-05-14 12:08
To my knowledge ESLint 7 still ships the CLIEngine API. So the extension should still work. I have not done any work yet to move the extension to version 7.0 API.

Why do you think the way the extension is implemented affects this?

**Comment by spoldman** [comment] 2020-05-14 13:29
Just to add to this conversation an issue that might be related. But during my process of updating to yarn v2 I updated esLint to v7. After this VSCode started becoming very slow and running 100% CPI. I followed the Yarn PnP instructions for VSCode and nothing improved. But now I have downgraded to v6.8 of esLint and everything seams to be running nicely. Not sure if it is important but I just wanted to point it out.

**Comment by sdalonzo** [comment] 2020-05-14 14:45
I think I was a little unclear - I think my problem was really due to [changes in plugin resolution](https://eslint.org/docs/user-guide/migrating-to-7.0.0#plugin-resolution-has-been-updated) - so when I mapped the extension to my ESLint binary in my monorepo, it was no longer able to resolve plugins. In the short term, I've rolled back to 6.8.0.

**Comment by dbaeumer** [comment] 2020-05-15 13:19
I will keep the issue open since we should look into adapting the new API.

**Comment by ericblade** [comment] 2020-05-26 06:17
> I think I was a little unclear - I think my problem was really due to [changes in plugin resolution](https://eslint.org/docs/user-guide/migrating-to-7.0.0#plugin-resolution-has-been-updated) - so when I mapped the extension to my ESLint binary in my monorepo, it was no longer able to resolve plugins. In the short term, I've rolled back to 6.8.0.

I have an issue where I have a plugin resolution problem in a particular repo.  It is configured as a pure javascript server sort of thing, with a typescript webapp inside it.  The server project uses airbnb-base, and the webapp uses typescript-airbnb.  With ESLint 6, this seemed to work pretty well, but with ESLint 7, it seems to pretty randomly break with a complaint about module resolution between the two projects:

![image](https://user-images.githubusercontent.com/1451847/82866427-e3403200-9ef6-11ea-9a32-94a2af062cb1.png)

This seems to be more of a configuration issue for something that has changed, rather than directly affecting VSC .. there might not be anything necessarily actionable from VSC on this,

**Comment by dbaeumer** [comment] 2020-05-26 07:58
The eslint plugin allows to pass these options using the `eslint.options` setting in VS Code.

**Comment by ericblade** [comment] 2020-05-26 08:18
having some issue with that -- first, setting it at the project level, with ````{
    "eslint.options": {
        "resolvePluginsRelativeTo": "."
    }
}```` doesn't seem to be capable of doing the right thing -- i think? i need it to resolvePluginsRelativeTo the root of the project when i'm editing code there, and relative to the "public" directory when i'm editing code below that structure.

As well, the schema validation for eslint.options seems to be broken - when i enter "eslint.options" in my project settings, it tells me it should be an object, so i open some braces, and then i hit shift-space to see what options are available there, and it tells me "eslint.options" is the only valid option.  (granted, this should be a different bug, but i just ran into it and wanted to note it before i forgot about it)

So, anyway, that gets the eslint server running, but it doesn't seem to be validating the "public" project any differently than it does the base server javascript.  It would be good to know what the ESLint people are expecting for a solution for this sort of problem, so that it works outside of VS, too.  And so that it works correctly either in or out.

**Comment by dbaeumer** [comment] 2020-05-26 09:47
The `resolvePluginsRelativeTo` is relative to the working directories which are specified using `eslint.workingDirectories`. It is like the current working directory in a terminal.

**Comment by ericblade** [comment] 2020-05-26 19:51
like this?
````
{
    "eslint.options": {
        "resolvePluginsRelativeTo": "."
    },
    "eslint.workingDirectories": [ ".", "./public" ]
}
````

That doesn't seem to work -- it looks like eslint is working, but it's not reporting very much at all, i'm not seeing anything other than regular javascript warnings in the typescript code, and i'd expect that it would be very vocal about my usage of 'any' all over this project.

**Comment by dbaeumer** [comment] 2020-05-27 08:58
Yes, but without the "." in the working directories. If you provide me with a GitHub repository I can clone and steps on how to reproduce I can have a quick look.

**Comment by jaydenseric** [comment] 2020-06-07 09:31
ESLint ignores dotfiles by default, so to lint files like `.babelrc.js` with ESLint v7 you have to add this to your `.eslintignore` file:

```
!.*
```

With ESLint v6, you had to do this:

```
!.*
node_modules
```

Otherwise you would end up linting dotfiles in `node_modules`.

Unfortunately, `vscode-eslint` has the v6 behavior even if your project has v7 as a dependency, and has the v7 compatible `.eslintignore` config. Essentially, running ESLint via an npm package script will report no errors, but opening a `node_modules` JS dotfile in the editor result in `vscode-eslint` reporting a lot of errors.

Perhaps this be fixed once this issue is resolved? It seems the `ESLint` class relates to this behavior as it has a `isPathIgnored` method.

**Comment by wapenshaw** [comment] 2020-07-28 21:18
I was using eslint v7.x on a create react app ejected project, and the whole linting/intellisense experience was running at a crawling pace. I had to downgrade to v 6.8.0 because I figured out this was the extension that's slowing down everything. After downgrading to 6.8.0 everything is working as intended and snappy as ever. if you want to replicate my env, run vscode on my [repo here] (https://github.com/wapenshaw/react-typescript-eslint-prettier-vscode-boilerplate). If i did something wrong, please let me know. Because for sure downgrading to 6.8 fixed the issue for me.

**Comment by ghaiklor-wix** [comment] 2020-11-03 12:04
Bumping this issue, because when using shared configurations with plugins relative to the configuration, this extensions does not check and provide no errors in VSCode. Calling lint from CLI works though.

**Comment by dbaeumer** [comment] 2020-11-03 15:10
@ghaiklor-wix are you saying that you can't use ESLint v7. To my knowledge it still works with the extension the only drawback is that everything is sync. However this doesn't matter to much since I run the validation in a separate node process anyways.

**Comment by ghaiklor-wix** [comment] 2020-11-03 15:36
@dbaeumer yes, ESLint does not work in VSCode, no errors from it. Some context...

We are using a separate npm package, where our company shares configuration for ESLint and other tooling. This package has all the plugins as its dependencies. So our projects have only eslint and its configuration package, nothing else, no peer dependencies to eslint to work.

When running such a setup from CLI - it works just fine. But it does not work "interactively" in VSCode, no error highlights and stuff. AFAIU, this is related to the plugin resolve algorithm.

**Comment by dbaeumer** [comment] 2020-11-04 09:57
@ghaiklor-wix this has nothing to do with the V7 API. Rush patches the eslint command which makes this work. See https://github.com/microsoft/vscode-eslint/issues/1040#issuecomment-669193727 for details.

**Comment by ghaiklor-wix** [comment] 2020-11-04 13:14
@dbaeumer 

In the issue you gave a link, the solutions was:

> You can use the resolvePluginsRelativeTo option to point it to the package that contains the config. In my case, I ended up with a config like this:

It was required for ESLint v6, yes, but ESLint v7 changes the way how it resolves plugins, so the solution from the issue with `resolve-plugins-relative-to` is no longer required, because it is the default behaviour in ESLint v7. And still, it does not work.

**Comment by dbaeumer** [comment] 2020-11-05 07:12
@ghaiklor-wix what happens when you still use the option together with v7.

**Comment by btmills** [comment] 2021-05-26 04:02
:wave: Hello from the ESLint team! I wanted to give you all a heads up about an RFC we're currently working on, https://github.com/eslint/rfcs/pull/80. We plan to define package exports in v8.0.0, which means the `CLIEngine` API will no longer be available. We know the `ESLint` API is currently missing a replacement for the `CLIEngine#getRules()` method, so the RFC includes a new `ESLint#getRulesForReport(report)` method to cover that use case. If you have time, would you please take a look at the RFC and the [`ESLint` class API documentation](https://eslint.org/docs/developer-guide/nodejs-api#eslint-class) and let us know on the RFC if there are any use cases we haven't handled?

**Comment by dbaeumer** [comment] 2021-05-26 09:48
@btmills from a first look the API looks OK to me. However without really trying to adapt this it is hard to say what might be missing. What is your schedule to release v8.0.0. The biggest problem I have with removing the old CLIEngine is that I as an extension still have to support the old API. Users can still rely on ESLint version < 8.0.0 in their workspace which will not have the new API especially not `ESLint#getRulesForReport(report)` So I need to write probing code and then do the right thing depending on the ESLint version installed. This will be quite some code effort on my end.

**Comment by dbaeumer** [comment] 2021-08-23 08:55
There is a new insider version that adapts ESLintClass API as introduced in 7.0.0. Would love to get some feedback. It is here:

https://github.com/microsoft/vscode-eslint/releases/tag/release%2F2.1.24-Insider. You need to install by hand using `Install Extension from VSIX` command.

**Comment by dbaeumer** [comment] 2021-08-23 09:04
Actually the version only uses the ESLint class when using ESLint 8.0.0 beta.

**Comment by joshunger** [comment] 2021-09-01 10:42
@dbaeumer do you want issues logged under this issue or a new issue for feedback on 2.1.24?

**Comment by dbaeumer** [comment] 2021-09-02 13:48
@joshunger please open new issues.

**Comment by joshunger** [comment] 2021-09-02 14:03
@dbaeumer 2.1.24-Insider works great thank you! I was after top level await which landed in eslint 8.

**Comment by dbaeumer** [comment] 2021-10-01 15:35
Will come in 2.2.0. Coding is done.

**Closed by dbaeumer** 2021-10-01 15:35 UTC
Labels: feature-request, help wanted

**Comment by simonv3** [comment] 2022-04-04 23:44
Just curious, eslint is now on 2.2.3, but the latest that I see in VSCode is 2.1.23. Is that update coming?

**Comment by dbaeumer** [comment] 2022-04-05 07:15
Which version of VS Code are you on? 2.2.3 needs a fairly updated VS Code version.

**Comment by simonv3** [comment] 2022-04-05 11:56
Thank you for the super fast reply @dbaeumer ! Updating eslint (i'd been ignoring the little warning for a couple of days) seems to have fixed it. Thanks!
