### ISSUE TITLE
eslint extension fails to import plugin when it exists in the pnpm workspace package

### ISSUE THREAD

**Issue by vim-daniel** [microsoft/vscode-eslint#1531] opened 2022-10-03 14:38 UTC
Opening this issue again, but this time with reproduction 😄 

The original issue:
https://github.com/microsoft/vscode-eslint/issues/1373

Reproduction:
https://github.com/vim-daniel/eslint-pnpm-workspace-reproduction

**Comment by dbaeumer** [comment] 2022-10-04 06:51
@vim-daniel the problem is that pnpm modified the `NODE_PATH` by generating a different `eslint` script into the `node_modules\bin` folder. Neither VS Code nor the VS Code ESLint extension knows about this. 

From the eslint script

```sh
if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/workspaces/eslint-pnpm-workspace-reproduction/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="$NODE_PATH:/workspaces/eslint-pnpm-workspace-reproduction/node_modules/.pnpm/node_modules"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/eslint@8.24.0/node_modules/eslint/bin/eslint.js" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/eslint@8.24.0/node_modules/eslint/bin/eslint.js" "$@"
fi
```

The `yarn` people did have the same problem and they provided a `yarn sdk` command to integrate into the editor (see https://yarnpkg.com/getting-started/editor-sdks) since they know what modifications they do to Node / NODE_PATH and the detection of the `eslint.js` file compared to standard node resolution.

The VS Code eslint extension has a setting `eslint.nodePath` that allows these SDKS to inject their setting. 

You might want to try modifying the `NODE_PATH` yourself and see if you can get it working that way. But the right approach would be to ask the `pnpm` developers to provide a `sdk` command like the `yarn` people do.

If the `pnpm` developers discover that they need additional settings in the extension to provide the right information I am happy to help.

Any objections to close since there is little I can do ?

**Comment by vim-daniel** [comment] 2022-10-04 08:46
Ok, I think i understand the issue I'll create an issue in the pnpm repo as well
https://github.com/pnpm/pnpm/issues/5447

But a question about this mechanism, shouldn't the extension use the eslint binary that is closest to the file?
and then it will use the one that pnpm altered

**Comment by dbaeumer** [comment] 2022-10-05 07:30
The VS Code ESLint extension loads the ESLint npm module using `require` and keeps it alive (this needs a proper NODE_PATH value). It doesn't go through the shell script. Going through the shell script would mean that we need to spawn a process on every lint run which makes linting very inefficient on type. You can configure a task for now as a workaround which starts eslint uing the shell script.

I will close the issue for now.

**Closed** 2022-10-05 07:30 UTC
Labels: info-needed
