### ISSUE TITLE
Extends isn't playing well with others

### ISSUE THREAD

**Issue by jsodeman** [microsoft/vscode-eslint#411] opened 2018-02-22 16:43 UTC
My settings.json is
```
{
	"eslint.options": {
		"extensions": [".js", ".vue", ".jsx"]
	},
	"eslint.validate": [
		{
			"language": "vue",
			"autoFix": true
		},
		{
			"language": "javascript",
			"autoFix": true
		},
		{
			"language": "javascriptreact",
			"autoFix": true
		}
	]
}
```

When I have .eslintrc.json set to
```
{
	"extends": ["airbnb-base"],
	"plugins":[
		"html",
		"import",
		"vue"
	],
}
```
then VS Code reports 9 problems with my code. But when I add in the vue plugin as follows then I get 0 problems reported.
```
{
	"extends": ["airbnb-base", "plugin:vue/strongly-recommended"],
	"plugins":[
		"html",
		"import",
		"vue"
	],
}
```

I'm using:
eslint 4.18.1
eslint-plugin-vue 4.2.2
and the Vetur and ESLint VS Code extensions

**Comment by jsodeman** [comment] 2018-02-23 17:23
With `"extends": ["airbnb-base", "plugin:vue/strongly-recommended"],`

Running the following from the command line:
`eslint --ext .js,.vue -c .eslintrc.json js/src/`

Results in 0 error reported in VSCode and 9 errors reported on the command line. 

With `"extends": ["airbnb-base"],`

Results in 0 error reported in VSCode and 0 errors reported on the command line. So it looks like eslint-plugin-vue is working correctly with the .eslintrc.* from the command line but not within VSCode for some reason.

**Comment by dbaeumer** [comment] 2018-02-26 08:34
@jsodeman have you installed the vue extension from the market place (https://marketplace.visualstudio.com/items?itemName=octref.vetur). Without a vue plugin the language `vue` is not known to VS Code and the configuration 

```
		{
			"language": "vue",
			"autoFix": true
		}
```

has no effect.

**Comment by jsodeman** [comment] 2018-02-26 15:49
Yes, I've got both the Vetur and ESLint plugins installed in VS Code.

**Comment by jsodeman** [comment] 2018-02-26 15:56
I'm not sure if one of the Code extensions updated but today the errors started being reported correctly.

**Comment by dbaeumer** [comment] 2018-02-27 08:58
Can you provide me with a GitHub repository I can clone that reproduce the problem. Then I can have a look and try to understand why this is happening.

**Comment by jsodeman** [comment] 2018-03-01 16:16
I'll work on putting one together.

**Comment by dbaeumer** [comment] 2019-10-17 10:30
Closing since no reproducible steps were provided.

**Closed by dbaeumer** 2019-10-17 10:30 UTC
Labels: needs more info
