### ISSUE TITLE
No Quick Fixes Available on Svelte files only

### ISSUE THREAD

**Issue by D-Marc1** [microsoft/vscode-eslint#1635] opened 2023-04-14 16:54 UTC
For some reason, when I hover over an ESLint issue on a Svelte file, it'll state that it knows there's an issue, but that there's `no quick fixes available`. 

<img width="284" alt="qdBzC" src="https://user-images.githubusercontent.com/30007968/232107870-81b59335-e992-403f-aa6a-cc1333f46506.png">

However, if I go to a TypeScript file, I can easily click on `Quick Fix`.

<img width="271" alt="snzPc" src="https://user-images.githubusercontent.com/30007968/232107903-3f299e57-bef0-407d-ac56-c2db0323f108.png">

Weirdly enough, it actually used to work for me, and then all of sudden it stopped working one day. I even tried to completely erase VS Code and start from scratch, but to no avail.

Here are the `devDependencies` in the **package.json** for linters I'm using:

```json 
"devDependencies": {
  "@typescript-eslint/eslint-plugin": "^5.50.0",
  "eslint-config-prettier": "^8.5.0",
  "eslint-plugin-prettier": "^4.2.1",
  "eslint-plugin-svelte": "^2.15.0",
  "prettier": "^2.8.3",
  "prettier-plugin-svelte": "^2.8.1",
}
```

*I'm using `eslint-plugin-svelte`, rather than `eslint-plugin-svelte3` (the official Svelte one), since [`eslint-plugin-prettier` recommends to use the non-official one](https://github.com/prettier/eslint-plugin-prettier#svelte-support)*.

Here's the pertinent info on the `.eslint.cjs` file:

```js
extends: [
  'eslint:recommended',
  'plugin:@typescript-eslint/recommended',
  'plugin:svelte/recommended',
  'plugin:prettier/recommended',
],
plugins: ['@typescript-eslint'],
ignorePatterns: ['*.cjs', '*.config.js'],
parser: '@typescript-eslint/parser',
parserOptions: {
  extraFileExtensions: ['.svelte'],
  project: './tsconfig.json',
},
overrides: [
  {
    files: ['*.svelte'],
    parser: 'svelte-eslint-parser',
    // Parse the script tag in Svelte as TypeScript
    parserOptions: {
      parser: '@typescript-eslint/parser',
      project: './tsconfig.json',
    },
  },
],
```

Here are my user settings on VS Code:

```json
{
  "eslint.validate": [
    "svelte",
    "typescript"
    "javascript",
  ],
  "svelte.enable-ts-plugin": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[svelte]": {
    "editor.defaultFormatter": "svelte.svelte-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "css.validate": false,
  "scss.validate": false
}
```

*I'm aware of `eslint.probe` as the "new" way to do it, but it actually doesn't work for me*.

**Comment by dbaeumer** [comment] 2023-04-17 07:26
@D-Marc1 does fixing work for you correctly on the command line (e.g. when running eslint in the terminal). If yes, can you please provide me with a GitHub repository that I can clone that demos this. This ensures that we are using the same setup.

**Comment by jamesinvt** [comment] 2023-04-18 21:44
I'm having the same problem.   I believe it's a similar issue to #1610 

When I disable "Disable Rule Comment" in the vscode-eslint it then works and I see the Quick Fix option -- so that's a good temporary workaround to try unless you absolutely need the "disable on the next line/whole file" options.  I tried the suggested fix in the issue above and changed the `commentStyle` to `line` but that didn't work

If I go to the Output console tab > Select ESLint in the dropdown, I see this error:

```
[Error - 5:36:49 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Invalid regular expression: //** eslint-disable-line/: Nothing to repeat
  Code: -32603 
```

**Comment by dbaeumer** [comment] 2023-04-19 07:02
@jamesinvt thanks for pointing this out.

**Comment by D-Marc1** [comment] 2023-04-22 21:23
@dbaeumer, this doesn't work when I run this on command line either, with: `npx eslint --fix`.

**Comment by dbaeumer** [comment] 2023-04-24 10:44
@D-Marc1 if it doesn't work on the command line (terminal) then it will not work in the extension. The exension basically uses the eslint npm package internally.

I will close the issue since there is nothing the extension can do if it doesn't work in ESLint itself. All I can recommend is to open an issue with the ESLint npm  package.

**Closed by dbaeumer** 2023-04-24 10:44 UTC
Labels: info-needed

**Comment by jamesinvt** [comment] 2023-04-24 18:13
@D-Marc1 when you say "it didn't work" when you ran `npx eslint --fix` do you mean that it produced an error or just did nothing at all?

I ran this in the root folder and there was no output or change to the files.  I ran `npx eslint --fix ./src` and that did work. 

@dbaeumer Sorry for the back-and-forth.  Let me know if you want me to open a new issue but I do believe the Author and I are having the same issue.  I don't think it's an issue with the eslint cli package.

I set up an example repo here that should let you reproduce the error.  No need to run any build or anything:

https://github.com/jamesinvt/vscode-eslint-svelte-test

To reproduce:

In `src/App.svelte` hover over the console.log and it will show `No Quick Fixes Available` and in the ESLint output it will give the error:
```
[Error - 5:36:49 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Invalid regular expression: //** eslint-disable-line/: Nothing to repeat
  Code: -32603 
  ```
Go into `.vscode/settings.json` and under `eslint.codeAction.disableRuleComment` change `enabled` to `true` and the quick fixes option will work.

**Comment by D-Marc1** [comment] 2023-04-25 14:03
@jamesinvt You are correct, I forgot to add `./src`. I'm getting the exact same situation as you. I see it working to lint on command-line and I see the exact same message in the output.

@dbaeumer Please reopen this issue. I made a mistake by not typing in the full command for eslint. `npx eslint --fix ./src` does in fact work and fixes the linter issues. This looks like it probably is an issue with VS Code after all.

**Comment by dbaeumer** [comment] 2023-04-28 08:30
The regexp problem is tracked here and already fixed in main: https://github.com/microsoft/vscode-eslint/issues/1610 Will be in the new next release which will ship beginning of next week.
