### ISSUE TITLE
Cannot find module 'eslint-config-google' 

### ISSUE THREAD

**Issue by hmmChase** [Microsoft/vscode-eslint#105] opened 2016-07-30 03:55 UTC
After several hours of trying to get this to work, I have to admit defeat and ask for help.

The error I am getting is:
![image](https://cloud.githubusercontent.com/assets/10532835/17267948/ba7988ec-55e6-11e6-84e2-2cca42d7a71f.png)

I've tried all the suggestions in similar issues including only having the packages global, and only having the packages local.  Neither works for me.

Currently, I have a local-only setup, which looks like this:
![image](https://cloud.githubusercontent.com/assets/10532835/17267957/e0711f1a-55e6-11e6-8051-e247ef6bfe35.png)
![image](https://cloud.githubusercontent.com/assets/10532835/17267960/fb1eef72-55e6-11e6-869e-105dd7714bb7.png)
![image](https://cloud.githubusercontent.com/assets/10532835/17267963/101e8298-55e7-11e6-9aa5-2961f5fdb9a7.png)
![image](https://cloud.githubusercontent.com/assets/10532835/17267971/39b286d6-55e7-11e6-83b8-a9cb92c8122f.png)
![image](https://cloud.githubusercontent.com/assets/10532835/17267975/564f3d52-55e7-11e6-88f8-8081dbdc3131.png)

According to all the advice I've read here and elsewhere, this should be working.  I must be not understanding something correctly.  Any help would be greatly appreciated, thanks!

**Comment by kumarharsh** [comment] 2016-07-30 14:17
I think you need to specify the full name of the config, such as `eslint-config-google`.

Here's my eslint config, and this works (this is a *js* file, not *json*, hence the `module.exports`)

```js
/* .eslintrc.js */
module.exports = {
  root: true, /* restrict to this level */
  extends: [
    "eslint-config-playlyfe",
    "eslint-config-playlyfe/rules/testing",
  ],

  plugins: [
    "eslint-plugin-playlyfe",
  ],
  .
  .
  .
};
```

**Comment by hmmChase** [comment] 2016-07-30 17:12
@kumarharsh Thanks for the suggestion, but unfortunately that didn't seem to make a difference.

**Comment by caiges** [comment] 2016-07-31 20:56
@hmmChase This is a duplicate of #101

**Comment by hmmChase** [comment] 2016-08-01 00:52
@caiges after reading the documentation referenced in the issue you linked, I was able to figure out a workable solution.  I had to substitute the names of the config in .eslintrc.json file with the path to the actuals configs index.js file.

so now my .eslintrc.json looks like this as opposed to my original above.
![image](https://cloud.githubusercontent.com/assets/10532835/17280505/4517a7f8-575f-11e6-978e-0f0eeae54eba.png)

However, you will get another error because the google config includes a config within it called XO.  So you go into /node_modules/eslint-config-google/index.js and change this:
![image](https://cloud.githubusercontent.com/assets/10532835/17280543/f7794960-575f-11e6-837b-c5b13edc460c.png)

to this:
![image](https://cloud.githubusercontent.com/assets/10532835/17280561/396eaf72-5760-11e6-9c09-4f0dc6404e2e.png)

and tada....
![image](https://cloud.githubusercontent.com/assets/10532835/17280581/6beb852e-5760-11e6-9e25-1db5c84b6cc4.png)

woo!...

**Comment by caiges** [comment] 2016-08-01 00:59
Nice find, I'll give that a try. The current behavior still needs a fix as
it's out of line with the expectations users will have given the eslint
spec. I haven't looked into the fix yet but it shouldn't be too hard to
resolve.

**Comment by hmmChase** [comment] 2016-08-02 18:37
just to add some more info...

If you try to do this for plugins, you get this error:
![image](https://cloud.githubusercontent.com/assets/10532835/17340471/3d6d3dd2-58be-11e6-9b59-76bca4be7310.png) 
because ESLint  automatically prefixes "eslint-plugin-" on any plugin value so the path gets messed up, which makes the Airbnb and Standard configs unusable.

**Comment by Shuunen** [comment] 2016-08-04 13:27
@hmmChase Solution works ! thanks !

**Comment by caiges** [comment] 2016-08-04 23:52
@hmmChase Is this still broken for you after the 1.4 release? My extended configs appear to be working now.

**Comment by dbaeumer** [comment] 2016-09-14 20:02
@hmmChase Could you give this a try using the latest ESLint extension. If the problem still exists do you see the same behavior in a terminal ?

**Comment by dbaeumer** [comment] 2016-11-10 11:58
Closing since I haven't received any response. Please ping if you still think this is a problem.

**Closed by dbaeumer** 2016-11-10 11:58 UTC
Labels: needs more info

**Comment by karlpatrickespiritu** [comment] 2016-12-04 13:16
I'm having this issue

````
$ eslint server.js
Cannot find module 'eslint-config-google'
Referenced from: C:\Users\Private\Development\web\food-shop-server\.eslintrc.js
Error: Cannot find module 'eslint-config-google'
````

I already have it installed
````
"devDependencies": {
    "eslint": "^3.11.1",
    "eslint-config-google": "^0.7.1",
    "eslint-config-standard": "^6.2.1",
    "nodemon": "^1.11.0"
  }
````

**Comment by awebdeveloper** [comment] 2017-02-17 06:33
still exists in the latest version of eslint & vscode

**Comment by kumarharsh** [comment] 2017-02-17 08:33
It works well for me. @awebdeveloper  Can you post a reproducible project link to test?

**Comment by anniee** [comment] 2017-03-07 19:42
I had the same issue and was using a similar solution to hmmChase's until I installed eslint-config-google globally, and used `"extends": "google"` in my config. For reference: https://github.com/google/eslint-config-google
