### ISSUE TITLE
eslint-plugin-import error/not work

### ISSUE THREAD

**Issue by SilentFlute** [microsoft/vscode-eslint#1738] opened 2023-11-24 07:32 UTC
i use `eslint` in `vs code` for a long time, it's very well, recently, i have a new project, i still use it, it works very well, until i install `eslint-plugin-import`, first, i open an issue in there:
[this plugin not work for me](https://github.com/import-js/eslint-plugin-import/issues/2927)
they suggested me to open a issue here, so i came here to find a help, this is my `vs code` config:
`keybindings.json`:
```
//...
  {
    "key": "alt+f",
    "command": "eslint.executeAutofix"
  },
//...
```
`settings.json`:
```
//...
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
//...
```
in which, i can lint my code without save it through `alt+f`, when i think its ok, i use `ctrl+s` save it and fix the rest errors, if there are of course, that's very convenient for me, and every rule in `eslint` works fine, except for the `import/order`, which doesn't work either as a shortcut or in the terminal, and here is the minimal reproduce repo: https://github.com/SilentFlute/eslint-import-issue

any suggest will be appreciated

**Comment by SilentFlute** [comment] 2023-11-24 07:38
almost forget, first, i press `alt+f` in `/src/pages/index/index.tsx` the rule dont work at all and i got a error from `eslint` extension:
![error](https://user-images.githubusercontent.com/28900312/284814915-a0525ed5-f142-4f83-bfb2-2ea2085ad545.png)

when i quit `vs code` and close my computer, next day i reopen the computer and `vs code`, press `alt+f` in `/src/pages/index/index.tsx` again, still not work, but no error any more

and i tried lint the same file in terminal, its stay still(no work, no error), that confused me

**Comment by dbaeumer** [comment] 2023-11-24 08:35
I can't reproduce this. I don't have a short cut bound but executing `Fix all` for ESLint fixes errors in the file. Any additional steps / hints


![cast](https://github.com/microsoft/vscode-eslint/assets/1931590/430ed15b-c054-4e0b-a262-2dd64c491632)

**Comment by SilentFlute** [comment] 2023-11-24 12:29
u r right, the semicolon's issue is fine, but the `import/order` doesn't, actually each rule is fine except the `import/order`, the order of import in the file is:
```
import { PureComponent } from 'react';
import { Card, Calendar, Tabs } from 'antd';
import type { Dayjs } from 'dayjs';
import type { CalendarProps, TabsProps } from 'antd';
import './index.less';
```
i config the `import/order` rule in `.eslintrc.json`, and when i lint the file, the order of import should have some change i guess, in my opinion, the `import type` statements should turns to end, may be like this:
```
import { PureComponent } from 'react';
import { Card, Calendar, Tabs } from 'antd';
import './index.less';
import type { Dayjs } from 'dayjs';
import type { CalendarProps, TabsProps } from 'antd';
```
or sth like that, any way it should change, but it doesn't

**Comment by SilentFlute** [comment] 2023-11-29 01:37
well, i cant provide u an example

In fact, I've only seen this error the first time I configured `import/order`, and not since, I first filed an `issue` with `eslint-plugin-import`, but one of the contributors suggested that I file an `issue` with you guys, and that's how I got this `issue`.

The problem I'm having is that `import/order` doesn't work, or to be more precise, at first it's report errors and doesn't work, and then it doesn't work and doesn't report errors.

And as you show in your `gif`, other rules like the semicolon rule are fine, but `import/order` is not.

I'm just trying to figure out how to make the `import/order` rule work.

**Comment by dbaeumer** [comment] 2023-11-29 08:58
Actually without steps there is little I can do. When you see it again please run ESLint in the terminal as well. If they differ in result then it would be good to have detailed information about the setup. As said, if eslint itself in the terminal doesn't report or fix errors the VS Code extension doesn't either.

I will close the issue for now. You can always add comments and I will reopen if there is something I can investigate.

**Closed by dbaeumer** 2023-11-29 08:58 UTC
Labels: info-needed
