### ISSUE TITLE
Eslint installed globally, working from CLI, but not in VS

### ISSUE THREAD

**Issue by doic** [Microsoft/vscode-eslint#335] opened 2017-11-03 10:37 UTC
Hello! I'm new to VS and Eslint.

Installed globally v 4.9.0, it works fine if I
`$ eslint ./project/js/app.js`

.eslintrc.json file is in my dev folder, I added also tasks.json (global config):
```javascript
{
	"version": "0.1.0",
	"windows": {
		"command": "eslint"
	},
	"linux": {
		"command": "eslint"
	},
	"osx": {
		"command": "eslint"
	},
	"isShellCommand": true,
	"args": ["*.js"],
	"showOutput": "silent",
	"problemMatcher": "$eslint-stylish"
}
```

VS knows Eslint is running but anyway:
```
[Info  - 11:11:02] ESLint server is running.
[Info  - 11:11:03] 
Failed to load the ESLint library for the document c:\project\js\app.js
```

**Comment by dbaeumer** [comment] 2017-11-03 12:37
@doic for the eslint extension you don't need a tasks.json file. However you do need a .eslintrc configuration file. Can you provide me with a clone GitHub repository and your config then I will try to reproduce. This worked for me without problems.

One question: how did you install eslint globally yarn or npm

**Comment by doic** [comment] 2017-11-03 12:46
NPM

Can I just share my .eslintrc file here? I never used GitHub myself; I still need to learn how it works...

```
{
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "sourceType": "module"
    },
    "rules": {
        "indent": [
            "error",
            "tab"
        ],
        "linebreak-style": [
            "error",
            "windows"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
}
```

**Comment by dbaeumer** [comment] 2017-11-03 13:55
@doic this works for me without problems

![capture](https://user-images.githubusercontent.com/1931590/32377033-c1b88cc6-c0a6-11e7-8cfd-54537f32282f.png)

Can you enable tracing to see why the library can't be resolved via: `"eslint.trace.server": "verbose"
`

**Comment by doic** [comment] 2017-11-03 14:12
@dbaeumer I hope this is what you're asking for:
```
[Trace - 15:08:36] Sending request 'initialize - (0)'.
Params: {
    "processId": 10176,
    "rootPath": "c:\\wamp\\www\\herbamobile2",
    "rootUri": "file:///c%3A/wamp/www/herbamobile2",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "workspaceFolders": true,
            "configuration": true
        },
        "textDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true
                }
            },
            "hover": {
                "dynamicRegistration": true
            },
            "signatureHelp": {
                "dynamicRegistration": true
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true
            },
            "codeAction": {
                "dynamicRegistration": true
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true
            },
            "documentLink": {
                "dynamicRegistration": true
            }
        }
    },
    "initializationOptions": {
        "legacyModuleResolve": false,
        "nodePath": null,
        "languageIds": [
            "javascript",
            "javascriptreact"
        ],
        "workspaceFolders": [
            "[object Object]"
        ]
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///c%3A/wamp/www/herbamobile2",
            "name": "herbamobile2"
        }
    ]
}


[Trace - 15:08:36] Received response 'initialize - (0)' in 80ms.
Result: {
    "capabilities": {
        "textDocumentSync": {
            "openClose": true,
            "change": 1,
            "willSaveWaitUntil": true,
            "save": {
                "includeText": false
            }
        },
        "codeActionProvider": true,
        "executeCommandProvider": {
            "commands": [
                "eslint.applySingleFix",
                "eslint.applySameFixes",
                "eslint.applyAllFixes",
                "eslint.applyAutoFix"
            ]
        }
    }
}


[Info  - 15:08:36] ESLint server is running.
[Trace - 15:08:36] Sending notification 'initialized'.
Params: {}


[Trace - 15:08:36] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/wamp/www/herbamobile2/js/app.js",
        "languageId": "javascript",
        "version": 1,
        "text": "import Catalog          from './class/Catalog';\r\nimport Cart             from './class/Cart';\r\nimport LazyLoadImages   from './class/LazyLoadImages';\r\n\r\nvar ua = window.navigator.userAgent;\r\nvar pass = ua.indexOf('Chrome/') > 0 || ua.indexOf('Firefox/') > 0;\r\nvar fails = ua.indexOf('Edge/') > 0 || ua.indexOf('Trident/') > 0;\r\n\r\nif(fails || !pass){\r\n    window.location = './seriously.htm';\r\n}\r\n\r\n//Chrome:   Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36\r\n//Edge:     Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063\r\n//IE:       Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; ASU2JS; Zoom 3.6.0; rv:11.0) like Gecko\r\n//FF:       Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0\r\n//Safari:   Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/534.57.2 (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2\r\n\r\nvar img = new Image();\r\nimg.onload=()=>{webpReady((img.width>0)&&(img.height>0))}\r\nimg.onerror=()=>{webpReady(false)}\r\nimg.src = 'data:image/webp;base64,UklGRhoAAABXRUJQVlA4TA0AAAAvAAAAEAcQERGIiP4HAA==';\r\n\r\nfunction webpReady(can){\r\n    window._can = can;\r\n    if(DEBUG)console.log('webpReady:',can)\r\n    var fileref=document.createElement(\"link\")\r\n    fileref.setAttribute(\"rel\", \"stylesheet\")\r\n    fileref.setAttribute(\"type\", \"text/css\")\r\n    if(can){\r\n        fileref.setAttribute(\"href\", 'css/main.webp.css')\r\n    } else {\r\n        fileref.setAttribute(\"href\", 'css/main.css')\r\n    }\r\n    document.getElementsByTagName(\"head\")[0].appendChild(fileref)\r\n}\r\n\r\nif('serviceWorker' in navigator){\r\n\tnavigator.serviceWorker.register('./sw.js',{scope: '/2/'});\r\n}\r\n\r\nwindow.catalog = new Catalog;\r\nvar cart = new Cart([{ref:'0141',count:2},{ref:'0142',count:1},{ref:'3114',count:4}]);\r\n\r\n/* Online / Offline Management */\r\nwindow.addEventListener('offline', e=> {\r\n    if(DEBUG)console.log('offline event');\r\n    var span = document.getElementById('disconnectedSpan');\r\n    if(DEBUG)console.log(span.style);\r\n    span.style.display = 'inline';\r\n})\r\nwindow.addEventListener('online', e=> {\r\n    if(DEBUG)console.log('online event');\r\n    document.getElementById('disconnectedSpan').style.display = 'none';\r\n})\r\n\r\nvar connection = navigator.connection || navigator.mozConnection || navigator.webkitConnection;\r\nif(connection){\r\n    var type = connection.type;\r\n    var effectiveType = connection.effectiveType;\r\n\r\n    if(DEBUG)console.log(\"Connection: \" + connection);\r\n\r\n    connection.addEventListener('typechange', e=>{\r\n        if(DEBUG)console.log(\"Connection type changed from \" + type + \" to \" + connection.type);\r\n        if(DEBUG)console.log(\"Connection effectiveType changed from \" + effectiveType + \" to \" + connection.effectiveType);\r\n    });\r\n\r\n    connection.onchange = e=>{\r\n        if(DEBUG)console.log(\"Connection type onchanged from \" + type + \" to \" + connection.type);\r\n        if(DEBUG)console.log(\"Connection effectiveType onchanged from \" + effectiveType + \" to \" + connection.effectiveType);\r\n    };\r\n}\r\n\r\ndocument.addEventListener('catalogReady', e=> {\r\n    cart.matchCatalog(catalog);\r\n    catalog.updateProductList();\r\n    LazyLoadImages.init();\r\n});\r\ndocument.getElementById('accept-notification').addEventListener('click',ev=>{\r\n    document.getElementById('modal-notification-permission').style.display = 'none';\r\n    Notification.requestPermission().then(result=>{\r\n        if (result === 'denied') {\r\n            if(DEBUG)console.log('Permission wasn\\'t granted. Allow a retry.');\r\n            return;\r\n        }\r\n        if (result === 'default') {\r\n            if(DEBUG)console.log('The permission request was dismissed.');\r\n            return;\r\n        }\r\n        if(DEBUG) console.log('Notification permission result:', result);\r\n        navigator.serviceWorker.getRegistration().then(reg=>{\r\n            reg.showNotification(\r\n            \"NOTIFICATION\",\r\n            {\r\n                body: \"body: \" + window.savedNotification,\r\n                tag: \"tag\"\r\n            }\r\n            )\r\n        });\r\n    });\r\n});\r\n\r\ndocument.getElementById('add').onclick = ev=>{\r\n    cart.addItem('0141');\r\n};\r\n\r\ndocument.getElementById('del').onclick = ev=>{\r\n    cart.deleteItem({ref:'0141',count:1});\r\n};\r\n\r\nnavigator.serviceWorker.addEventListener(\"message\", e=> {\r\n    if(DEBUG)console.log('e: ',e); // type rajouté depuis sw.js\r\n    if(e.data.type=='notification'){\r\n        window.savedNotification = e.data.body;\r\n        document.getElementById('modal-notification-permission').style.display = 'block';\r\n    }\r\n    \r\n});\r\n\r\nif(!DEBUG)console.warn('Console Logs Are Not Displayed; Compile JS with gulp -debug');"
    }
}


[Trace - 15:08:36] Received request 'client/registerCapability - (0)'.
Params: {
    "registrations": [
        {
            "id": "414f4632-f27d-4335-9f3b-b8daf163e887",
            "method": "workspace/didChangeConfiguration",
            "registerOptions": {}
        }
    ]
}


[Trace - 15:08:36] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
[Trace - 15:08:36] Received request 'client/registerCapability - (1)'.
Params: {
    "registrations": [
        {
            "id": "8ef06d7d-9037-46df-8597-44fdf1bcfb66",
            "method": "workspace/didChangeWorkspaceFolders",
            "registerOptions": {}
        }
    ]
}


[Trace - 15:08:36] Sending response 'client/registerCapability - (1)'. Processing request took 0ms
[Trace - 15:08:36] Received request 'workspace/configuration - (2)'.
Params: {
    "items": [
        {
            "scopeUri": "file:///c%3A/wamp/www/herbamobile2/js/app.js",
            "section": ""
        }
    ]
}


[Trace - 15:08:36] Sending response 'workspace/configuration - (2)'. Processing request took 1ms
[Trace - 15:08:38] 'npm config get prefix' value is: C:\Users\Doïc\AppData\Roaming\npm
[Trace - 15:08:38] NODE_PATH value is: C:\Users\Doïc\AppData\Roaming\npm\node_modules
[Trace - 15:08:38] Received request 'eslint/noLibrary - (3)'.
Params: {
    "source": {
        "uri": "file:///c%3A/wamp/www/herbamobile2/js/app.js"
    }
}


[Info  - 15:08:38] 
Failed to load the ESLint library for the document c:\wamp\www\herbamobile2\js\app.js

To use ESLint please install eslint by running 'npm install eslint' in the workspace folder herbamobile2
or globally using 'npm install -g eslint'. You need to reopen the workspace after installing eslint.

Alternatively you can disable ESLint for the workspace folder herbamobile2 by executing the 'Disable ESLint' command.
[Trace - 15:08:38] Sending response 'eslint/noLibrary - (3)'. Processing request took 1ms
```

**Comment by dbaeumer** [comment] 2017-11-06 08:47
@doic the extension is looking for the eslint node module here: `C:\Users\Doïc\AppData\Roaming\npm\node_modules`. Is this where the npm module is installed. If not, where is it installed on your system.

**Comment by doic** [comment] 2017-11-06 13:33
OK, so I looked at this directory and there was no eslint. I thought if I installed eslint globally via npm, it would work in VS Code?

I installed it locally and now it is working.
Do I need to install eslint in every new project for it to work in VS Code ?

**Comment by dbaeumer** [comment] 2017-11-06 16:22
Global install npm eslint should work. Interestingly npm tells eslint that the global installed module is under `C:\Users\Doïc\AppData\Roaming\npm` and `C:\Users\Doïc\AppData\Roaming\npm\node_modules` but interestingly npm doesn't seem to install them there. Can you find out where npm installed it by either using the `where` or `which` command.

**Comment by doic** [comment] 2017-11-06 16:33
Oooh, interesting, it looks like the `ï` in my Windows user name is messing things up!
I ran `npm list -g` and the folder was `C:\Users\Do{c\AppData\Roaming\npm` !!

I'll try to figure out a way to replace it with a latin `i`.

**Comment by dbaeumer** [comment] 2017-11-07 08:50
@doic you might want to think about reporting this to npm.

**Comment by doic** [comment] 2017-11-07 10:19
@dbaeumer OK I will ! Thanks for your help !

**Comment by dbaeumer** [comment] 2017-11-08 09:14
Closing. This seems to be a npm installation problem.

**Closed by dbaeumer** 2017-11-08 09:14 UTC
Labels: needs more info
