### ISSUE TITLE
Why does saving a .tsx taking so long with "Getting code actions from "ESLint" !?!

### ISSUE THREAD

**Issue by khteh** [microsoft/vscode-eslint#1514] opened 2022-08-24 06:48 UTC
```
{
    "workbench.colorTheme": "Visual Studio Light",
    "files.autoSave": "afterDelay",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "git.enableSmartCommit": true,
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {

        "source.fixAll": true
    },
    "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
    "javascript.format.placeOpenBraceOnNewLineForControlBlocks": false,
    "javascript.format.placeOpenBraceOnNewLineForFunctions": false,
    "typescript.format.insertSpaceBeforeFunctionParenthesis": true,
    "typescript.format.placeOpenBraceOnNewLineForControlBlocks": false,
    "typescript.format.placeOpenBraceOnNewLineForFunctions": false,
    "vetur.format.defaultFormatter.html": "prettyhtml",
    "vetur.format.defaultFormatter.js": "prettier-eslint",
    "git.confirmSync": false,
    "vetur.grammar.customBlocks": {
        "test": "js",
    },
    "security.workspace.trust.untrustedFiles": "open",
    "python.pylanceLspNotebooksEnabled": false,
    "jupyter.pylanceHandlesNotebooks": false,
    "notebook.lineNumbers": "on",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "[typescript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "auto-close-tag.activationOnLanguage": [
        "xml",
        "markdown",
        "HTML (EEx)",
        "HTML (Eex)"
    ]    
}
```

**Comment by cgooderham94** [comment] 2022-08-24 08:58
Also experiencing this issue my side. Removing this extension eliminates the issue.

**Comment by dbaeumer** [comment] 2022-08-24 09:11
This is very likely causes by a rules that runs because code actions on save are enabled.

You can enable `eslint.debug` to get a trace to see where the time is spent. If it is not spent in ESLint itself can you please provide me with a GitHub repository I can clone that demos what you are seeing, including steps on how to reproduce.

**Comment by khteh** [comment] 2022-08-24 09:13
Where to enable `eslint.debug`?

**Comment by cgooderham94** [comment] 2022-08-24 09:19
We resolved this issue by upgrading related NPM packages to the following versions:

```
"@typescript-eslint/eslint-plugin": "5.34.0",
"@typescript-eslint/parser": "5.34.0",
"eslint-import-resolver-typescript": "3.5.0",
"eslint-plugin-jest": "26.8.7",
```

**Comment by khteh** [comment] 2022-08-25 01:42
What value should be provided to `eslint.debug` in settings and where to see the debug message? https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint Where is the `ESLint output channel`?

**Comment by dbaeumer** [comment] 2022-08-25 09:21
You can specify `eslint.debug` in the VS Code settings. The output channel is under `View > Output` and then select `ESLint` from the drop down.

**Comment by khteh** [comment] 2022-08-29 07:44
After upgrading the packages as shared by @cgooderham94 it seems to improve.

**Comment by dbaeumer** [comment] 2022-08-29 09:01
OK. I will close the issue then. Please ping if you think there is something to do in the ESLint extension.

**Closed by dbaeumer** 2022-08-29 09:01 UTC
Labels: info-needed
