### ISSUE TITLE
Template Literals Appear to Break Linting

### ISSUE THREAD

**Issue by MuseofMoose** [microsoft/vscode-eslint#1002] opened 2020-06-29 20:43 UTC
A few days ago, I noticed strange behavior with my project's linting. 

First, vscode eslint was not working if there was a template literal present in the .js file (it would continue to highlight existing lint issues but not detect or highlight any new issues). This would happen on a per-file basis. So if a file had any kind of template literal in it, it would stop detecting/highlighting lint issues but if that wasn't the case, it would work just fine. Also of a note, commenting out the template literals in the file would immediately cause the linting to work as normal and highlight all the issue it had been ignoring. Commenting back in the template literal would then "freeze" the current linting state, with no file changes having any effect on the linting state as long as that template literal remained.

Second, my own manual lint commands were running into a very similar issue and kept giving me the following error for js files with template literals in them:

```
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
```

Both of these problems arose around the same time. I started with the second problem since I had a specific error and happened upon this issue:

https://github.com/babel/babel-eslint/issues/530

Following the instructions there, I ran
`yarn upgrade babel-eslint @babel/types`
and no longer had any template-literal problems with my manual linter. The vscode eslint plugin, however, continues to fail in the same way. Perhaps it's quietly running into similar errors in the background?

Versions:
- vscode v1.46.1
- vscode-eslint v2.1.5
- macos v10.15.3

Let me know if there's any additional info I can provide to help with this.

**Comment by dbaeumer** [comment] 2020-06-30 08:39
@MuseofMoose  can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by rchl** [comment] 2020-07-03 07:14
I can reproduce this on repo linked from another issue: https://github.com/mattfbacon/prefer-template-issue-demo (once the code is fixed by eslint).

I normally run with my own eslint dependency so I don't have this issue but I saw it in my projects that include eslint dependency and I think the solution could be to just install `@babel/types` manually (`npm i @babel/types`) to force the latest version.

**Comment by dbaeumer** [comment] 2020-07-21 13:21
I can't reproduce this using the linked repository. Any additional steps?

**Closed** 2020-07-28 13:28 UTC
Labels: needs more info
