### ISSUE TITLE
Prefer-const false positive

### ISSUE THREAD

**Issue by SenHeng** [microsoft/vscode-eslint#449] opened 2018-04-13 06:39 UTC
Posting here instead of in eslint repo because the error only appears in vscode, not on the cli.

<img width="584" alt="2018-04-13 15 31 40" src="https://user-images.githubusercontent.com/11208360/38720341-dd56a248-3f30-11e8-9f86-d3b9a86dd2dc.png">

vscode: 1.22.2
eslint: 4.19.2

**Comment by dbaeumer** [comment] 2018-04-13 08:46
@SenHeng can you provide me with a GitHub repository to reproduce the problem. The ESLint plugin calls the eslint npm libraries so in principal the code is the same and should produce the same errors.

Could it be when you execute eslint in the terminal it uses a global installed one compared to the ESLint extension using a local one?

**Comment by SenHeng** [comment] 2018-04-16 01:35
I'll see if I can reproduce a smaller repo. I took a quick look at the various config files and I think this is how it works.

Grunt -> babelify -> .babelrc -> babel-eslint -> .eslintrc.js

There's also a separate `npm link` run script that's simply `eslint .eslintrc.js app/scripts/`. So both of them end up using the same eslint config but neither of them produce any errors or warnings.

Both global and local eslint versions are at 4.19.1.

**Comment by dbaeumer** [comment] 2019-10-17 10:31
Closing since no reproducible steps where provided.

**Closed by dbaeumer** 2019-10-17 10:31 UTC
Labels: needs more info
