### ISSUE TITLE
Cannot read config file: Error: Unexpected token E in JSON at position 0

### ISSUE THREAD

**Issue by atif089** [Microsoft/vscode-eslint#250] opened 2017-06-05 17:21 UTC
```
OS Version: Windows 10 Professional x64
VS Code Version: 1.12.2
ESLint Version: v3.19.0
ESLint Plugin Version: 1.2.11
```

I get the following every time I open a JS file.

`Cannot read config file: c:\Users\111111111\.eslintrc.json Error: Unexpected token E in JSON at position 0`

http://i.imgur.com/9Y6hX9H.png

I don't understand where this configuration is stored so that I can remove it.

###Workspace Settings

http://i.imgur.com/eW2YtTT.png

###User Settings

http://i.imgur.com/FruFW9Y.png

**Comment by dbaeumer** [comment] 2017-06-06 07:43
This is eslint (http://eslint.org/) default behavior. It looks for .eslintrc files up the parent chain of your current working directory. Does that file exist on your machine ? Another possibility is that one of your other .eslintrc files include that file. 

You should see the same error when you execute eslint directly from the terminal. @atif089 I will close the issue since this is not specific to the vscode-eslint extension. If you think otherwise can you provide a setup (best would be a cloneable repository) so that I can reproduce the problem.

**Closed by dbaeumer** 2017-06-06 07:43 UTC
