### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by domoritz** [microsoft/vscode-eslint#721] opened 2019-07-25 15:10 UTC
On https://github.com/vega/vega-lite/commit/dc7278f1b42acbad5bfecfe56131830d78c00551, I get high (99%) CPU usage with VScode. 

MacOS, VSCode 1.36.1, Eslint plugin 1.9.0. Could be related to https://github.com/microsoft/vscode-eslint/issues/659 but I can't downgrade TypeScript.

**Comment by eamodio** [comment] 2019-08-16 01:43
I'm seeing the same thing -- started very recently and it was the eslintserver.js that was consuming a lot of CPU.

**Comment by SantoJambit** [comment] 2019-08-27 13:41
Same here.

**Comment by dbaeumer** [comment] 2019-08-28 12:12
I tried to reproduce this using the vega repository but couldn't. Could someone point me to the file to open that triggers the CPU load?

**Comment by SantoJambit** [comment] 2019-08-28 16:04
I just tried myself and couldn't get it to 100% cpu by simply opening any of the src/* files.

Maybe it's something other than plainly loading the files though. Maybe it's something that happens while editing a file or while browsing type definitions inside node_modules? Just spit-balling here.

**Comment by dbaeumer** [comment] 2019-08-29 07:50
@domoritz & @SantoJambit thanks for getting back. Any additional steps are welcome.

**Comment by jbinto** [comment] 2019-08-29 14:40
This is happening for me and a few other members of my team. Seems to have started in the last 1-4 weeks. We are using `@typescript-eslint/parser`. 

Notably we'll see `Code Helper` processes that get orphaned (they continue to run away with 100% CPU after VS Code has closed, and in Activity Monitor their parents are `launchd`, which is odd.)

I don't know how to trigger this condition but it seems to happen frequently. I have 2 orphaned Code Helper processes now currently taking 100% CPU and I've tried to run `dtruss` to get some information but I'm having much success sleuthing any info here.

I also tried to profile the extension per here https://github.com/Microsoft/vscode/wiki/Performance-Issues but since I don't have a way to trigger it (and can't figure out how to profile an existing runaway process), there's no real useful information. 

If anyone has tips on how to get some more insight into debugging these running processes let me know, I'll contribute whatever data I can to help get this fixed. I may even consider running for a few hours with the extension profiler on, we'll see how that works.

**Comment by jbinto** [comment] 2019-08-29 21:18
OK some developments here. I have a Code Helper process at 100% CPU right now, and it's not orphaned (yet).

I'm still figuring my way around these tools, but I was able to debug the live running process by figuring out which `Code Helper` PID was vscode-eslint, running `kill -USR1 $PID`, and by some luck I had that PID being traced with dtruss and saw the message telling me how to connect with Chrome devtools.

I captured a ~20 second profile and here's what I've gathered:

![image](https://user-images.githubusercontent.com/2664611/63976894-60ca3500-ca80-11e9-8b79-ca8e15372e3a.png)

Clicking around suggests a call to `createIndexMap` is taking up 100% of the call time and never completing. I tried pausing execution and found myself here:

![image](https://user-images.githubusercontent.com/2664611/63977065-c9b1ad00-ca80-11e9-8513-359be425e3cb.png)

Which looks like it's part of `eslint` proper: https://github.com/eslint/eslint/blob/master/lib/source-code/token-store/index.js#L44-L58

Setting some breakpoints and watches shows it's getting stuck on this iteration of the loop.

Will keep looking into it.

**Comment by dbaeumer** [comment] 2019-08-30 09:06
@jbinto First thanks a lot for tracking this down. Very very helpful!

For me it looks like an endless while loop in `createIndexMap`. I think the best we can do is to report this to the ESLint npm module itself since it needs to be fixed there.

**Comment by jbinto** [comment] 2019-08-30 13:47
@dbaeumer I thought so too, but that area of the eslint codebase hasn't been touched for 3 years (other than some renaming), and this problem is way newer than that. Somehow the call to `createIndexMap(tokens, comments)` is sending it token lists it can't process. We recently changed our project to TypeScript  
 and `@typescript-eslint/parser` so we suspect that is a contributing factor. It could be that we exposed an edge case in that function, or it could be the parser is somehow sending malformed tokens.

I got quite a bit closer into figuring out the exact tokens that cause the infinite loop, and then I closed the vscode tab that was at 100% CPU and lost the debugger session. 🤦‍♂️

**Comment by crimx** [comment] 2019-09-04 09:57
Updated the typescript parser to v2.1 and eslint to v6.3 so far so good.

**Comment by hadihallak** [comment] 2019-09-23 07:55
Same issue:
<img width="703" alt="vscode 1" src="https://user-images.githubusercontent.com/13556017/65409487-e5e30880-ddf8-11e9-8760-f8bef47787e8.png">
```js
    "typescript": "^3.6.2",
    "eslint": "6.3.0",
    "eslint-config-airbnb": "^17.1.1",
    "eslint-config-react-app": "^5.0.0",
    "eslint-plugin-flowtype": "^4.2.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-react-hooks": "^1.7.0",
```
tried running eslint only on save but didn't help

**Comment by dbaeumer** [comment] 2019-09-23 08:09
@hadihallak any reproducible steps?

**Comment by StephenHaney** [comment] 2019-09-23 08:17
Our entire team has the issue that @hadihallak pasted above across a variety of setups... it's hard to troubleshoot because it appears randomly, though consistently, but might not appear for an hour or two of work.

Our setup that seems to trigger it:
- CRA
- Styled Components
- The ESLint plugins pasted above
- `@typescript-eslint/parser`
- extends: `['react-app', 'airbnb', 'plugin:react/recommended', 'plugin:@typescript-eslint/recommended']`

**Comment by StephenHaney** [comment] 2019-09-24 19:12
Got it again today... heard my fans cranking, checked activity monitor:
"Code Helper" 99% CPU

Checked VSCode's process explorer... it's eslintServer.js at 100% CPU.

Here's some more info I was able to gather about the runaway process (Code Helper in Activity Monitor):

When I did VSCode > Toggle Dev tools and checked both the performance audit and JavaScript profiler, they had basically no load... idle process being like 99% of time. So it appears to be separate from whatever code that can see.

Activity Monitor's "Sample Process" output:
https://www.dropbox.com/s/klbqq7p8qq0ouf3/sample-of-code-helper-process.txt?dl=0

Activity Monitor's "Open files and ports" output:
https://www.dropbox.com/s/mvnhq0vpmrsiw2j/open-files-and-ports.txt?dl=0

Process: Real Memory Size 640MB
Virtual memory size: 5.18 GB

**Comment by jonaskello** [comment] 2019-10-02 13:52
FWIW, I have the same problem. Whenever I leave vscode open on my macbook and later come back it has the fans blowing at full strength. In activity monitor the process is Code Helper but running ps aux on that process shows that it is the eslint plugin.

**Comment by dbaeumer** [comment] 2019-10-03 09:14
As @jbinto pointed out this is very likely an issue in eslint itsel. See https://github.com/eslint/eslint/blob/master/lib/source-code/token-store/index.js#L44-L58 and https://github.com/microsoft/vscode-eslint/issues/721#issuecomment-526366654

But without steps to reproduce this is very hard to fix. Even moving the issue to ESLint without steps will not help. 

@StephenHaney could you capture the state of or workspace (file content) when this happens to see if we can reproduce it.

**Comment by StephenHaney** [comment] 2019-10-03 10:19
Yeah agreed – although we think it started for us when we moved to the typescript parser, so there may be something the parser or vscode-eslint can do in the short term to avoid the issue (just conjecture).

It seems to happen most often when jumping around lots of files. It's just infrequent enough that it's hard to repro, but still happens multiple times per day if we're really digging into a session.

I'll dedicate some time tomorrow to trying very carefully to reproduce.

**Comment by dbaeumer** [comment] 2019-10-03 10:21
@StephenHaney agree that this could be a problem in the typescript eslint parser as well.

**Comment by yoshi415** [comment] 2019-10-03 10:29
Another data point, this is happening to me with `@typescript-eslint/parser` enabled.

**Comment by StephenHaney** [comment] 2019-10-04 05:43
Is anyone with this issue NOT using `@typescript-eslint/parser`?

I [opened an issue on their repo ](https://github.com/typescript-eslint/typescript-eslint/issues/1042)as it seems to be the commonality here. Maybe someone there will have some helpful context.

I spent some more time trying to reproduce today, but I can't figure out any concrete repro steps. It really seems random. After working on the codebase for a while, jumping around files, I'll notice my fans have been at full blast too long, check activity monitor, and confirm it's happening.

**Comment by fabb** [comment] 2019-10-04 05:58
Since I changed ESLint extension setting `eslint.run` from `onType` to `onSave` it works fine. It slightly reduces usability though since I see old warnings in the wrong places until I save. It seems like the ESLint extension has some issue with aborting the old run when a new keystroke arrives, or maybe when it aborts it invalidates some cache and needs to completely recalculate it on the next run?

**Comment by hadihallak** [comment] 2019-10-04 06:56
@fabb I have it set up onSave and it doesn't seem to be fixing the issue as I still get 100% CPU usage occasionally

**Comment by dbaeumer** [comment] 2019-10-04 07:39
The reason why `onSave` might mitigate it is that far less validation runs happen.

**Comment by StephenHaney** [comment] 2019-10-04 23:06
I also run `onSave` and experience the issue. Maybe a good idea to turn it off to try to get quicker repro steps though.

**Comment by garyking** [comment] 2019-10-17 19:06
When editing a .ts file in vsc with this eslint ext enabled, in one of my projects with about 5000 sloc, my cpu usage on my mac hits about 400%. This only happens when I open a .ts file in this project, therefore forcing vsc to activate ts extensions. I'm using the typescript eslint parser, of course.

I'm also using `onSave`, and all I have to do is open a .ts file (doesn't matter how big or small), and cpu increases immediately. I know that eslint parses the file when opening it, but I don't know why this problem still occurs even on small files, where there shouldn't be any problems in the code to trigger this issue.

I only have this issue in some of my TS projects.

**Comment by wkoutre** [comment] 2019-10-17 20:11
Same findings as @garyking for me, across the board. Downgrading to `@typescript-eslint/parser@2.3.3` also resolves the issue for me.

**Comment by alejo-jm** [comment] 2019-10-21 02:17
For me, i'm working in a react-native project and the cpu it was at 178%, 
mi fix is open the src folder (not the entire project), copy and paste the `tsconfig.json` inside the `src` directory, change the path of the node_modules in that file:
`"extends": "../node_modules/react-redux-typescript-scripts/tsconfig.json",`
that is all :-)

**Comment by SantoJambit** [comment] 2019-10-23 08:40
I'm on `"@typescript-eslint/parser": "^2.0.0"` and I have the issue, so either it was fixed in 2.3.3 and later re-introduced or @garyking and @wkoutre just had a lucky moment. Or maybe it's not the parser that is causing the issue but another package.

**Comment by maxnowack** [comment] 2019-10-23 08:47
The issue is fixed for me with `@typescript-eslint/parser@2.5.0`

**Comment by garyking** [comment] 2019-10-23 18:14
I upgraded to `@typescript-eslint/parser@2.5.0`. The problem seems fixed for me too, so far. I tested in two of my largest projects.

**Comment by SantoJambit** [comment] 2019-11-13 09:39
I haven't had it in a long time, so yeah, it's very likely fixed!

**Comment by dbaeumer** [comment] 2019-11-18 11:59
I will close the issue then. Please ping if you see it again.

**Closed by dbaeumer** 2019-11-18 11:59 UTC
Labels: needs more info
