### ISSUE TITLE
The plugin will underline the whole object / function when there is a lint error.

### ISSUE THREAD

**Issue by cppcho** [Microsoft/vscode-eslint#278] opened 2017-08-18 09:55 UTC
For example there is an error at 17:14: `Color literal: { backgroundColor: '#fff' } `

![screen shot 2017-08-18 at 17 50 25](https://user-images.githubusercontent.com/1287355/29453934-fbb1db4e-843d-11e7-8407-f1c7f3cad0e4.png)

But in the editor, the whole object is underlined.

![screen shot 2017-08-18 at 17 49 48](https://user-images.githubusercontent.com/1287355/29453833-a42454f6-843d-11e7-93a0-12d382a8a26e.png)

This makes the editor so cluttered. I am not sure if it is due to the eslint settings or the issue of the plugin. The above screenshots are taken with only vscode-eslint enabled

vscode version 1.15.1 
vscode-eslint version 1.2.11
eslint version 4.4.1

**Comment by dbaeumer** [comment] 2017-08-30 14:08
@cppcho when you hover over the error what does the error hover show.

Can you provide a workspace I can clone to reproduce this. The ESLint simply hands the eslint error reported by the ESLint npm modules to VS Code. The extension doesn't adjust / compute any line column information.

**Comment by cppcho** [comment] 2017-08-31 02:55
@dbaeumer 

I have uploaded a demo project here.
https://github.com/cppcho/vscode-eslint-issue-278-demo

Run `yarn install` and open `App.js` in VSCode with all default settings (`settings.json`s are all empty), and with only `vscode-eslint` plugin enabled. The following is my screenshot.

![screen shot 2017-08-31 at 10 52 39](https://user-images.githubusercontent.com/1287355/29904270-976a006a-8e3a-11e7-9689-556d69fe3c05.png)

I guess it is something related to the eslintrc but I am not sure.

VSCode version 1.15.1
vscode-eslint version 1.2.11

**Comment by jeromequintard** [comment] 2017-10-11 19:16
Since the last VSCode or Eslint version, I have the same issue :
https://stackoverflow.com/questions/46695894/eslint-vscode-the-whole-object-is-underlined

**Comment by dbaeumer** [comment] 2017-10-16 09:06
There is little I can do about it. The start / end information comes from the ESLint npm module and I am very reluctant to tweak some for specific purposes. Here is what ESLint gives me in the provided example:

![capture](https://user-images.githubusercontent.com/1931590/31603922-fccf7174-b261-11e7-82fe-2cd1ad4e5b8c.png)

I will close the issue. If you think the ranges should be different please try to convince ESLint to change them

**Closed by dbaeumer** 2017-10-16 09:06 UTC
Labels: needs more info
