### ISSUE TITLE
Annoying messages from eslint

### ISSUE THREAD

**Issue by BobNobrain** [microsoft/vscode-eslint#1238] opened 2021-04-13 13:32 UTC
Sometimes eslint just spams me with irrelevant parsing error messages (because it is enabled "on type"). For example, in the following code:

```tsx
import React from 'react';

export default function Test() {
    React.useEffect(/* cursor goes here */)
}
```

i keep getting error messages with this stacktrace:

```
[Error - 4:15:39 PM] TypeError: Cannot read property 'type' of undefined
Occurred while linting <project>/.../test.tsx:4
    at visitCallExpression (<project>/node_modules/eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.development.js:1734:24)
    at <project>/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (<project>/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (<project>/node_modules/eslint/lib/linter/node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (<project>/node_modules/eslint/lib/linter/node-event-generator.js:285:22)
    at NodeEventGenerator.enterNode (<project>/node_modules/eslint/lib/linter/node-event-generator.js:299:14)
    at CodePathAnalyzer.enterNode (/<project>/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at <project>/node_modules/eslint/lib/linter/linter.js:954:32

    at Array.forEach (<anonymous>)
```

Is there a way to somehow mute this messages?

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/9580615/114560597-8451eb80-9c75-11eb-8f1a-f073ca8e1fe5.png">

**Comment by dbaeumer** [comment] 2021-04-14 11:48
Currently no. All I can think of having a setting for this that avoid the notification.

**Comment by BobNobrain** [comment] 2021-04-14 13:40
I think this would be a reasonable solution. When the setting is enabled, it just converts all these errors into some warning messages that appear in extension's output channel, but do not open this error popup. (I also wonder if there is some way to aggregate these popups into a single one, but that probably cannot be done from within the extension).

**Comment by egucciar** [comment] 2021-04-21 15:05
+1 for this, its a constant headache since i updated VSCode

**Comment by mkvlrn** [comment] 2021-04-24 14:21
Yes, PLEASE. I've tried finding a way to completely disable VSCode notifications (there isn't a way) because of that.

React's `useEffect` and changing some import paths in a node/typescript app wil absolutely SPAM (like a LOT LOT, I'm talking 30 messages) in a short period of time and you need to close ONE BY ONE.

I haven seen that before once in a while (usually only with `useEffect`)  but it's gotten much much worse. It used to be distracting but now it's flat out aggravating.

**Comment by jalajcodes** [comment] 2021-04-28 13:53
Everytime I type `useEffect()` this notification pops up. Not 30 times but just 1 time.

**Comment by patrickdean** [comment] 2021-04-30 16:55
+1 for this as well. If this is enabled on type perhaps there could be a setting that enables it on save instead? Or maybe even report these could be reported in the 'problems' tab rather than the output?

**Comment by rhyek** [comment] 2021-07-06 23:18
This has been driving me crazy for months. This always happens when using either `useEffect` or `useLayoutEffect`.

**Comment by justingrant** [comment] 2021-08-25 03:50
(merging in content from my dupe #1322) 

When ESLint encounters an exception, it will show a popup warning box in the IDE which must be manually dismissed by the user. For example, when I typed `const` on a new line in a JS file, I got an error dialog. 

![image](https://user-images.githubusercontent.com/277214/130507411-39f225ad-a4b9-48ee-84a2-f72470fc29ca.png)

![image](https://user-images.githubusercontent.com/277214/130506065-c2dda90b-2ad3-4719-8775-d2a15bdc6d62.png)

Obviously ESLint itself or its plugins (e.g. typescript-eslint) has a bug here and shouldn't be crashing. But IMHO it's not good to subject VSCode IDE users to dialogs caused by bugs in linters that most users can't fix, especially when most of these problems fix themselves once the user edits their code to fix the problem that caused ESLint to crash. 

The same is true for "can't load config" errors as described in https://github.com/microsoft/vscode-eslint/issues/1182#issuecomment-903986943. The VSCode user can't do anything to fix someone else's code, so putting up an error box isn't helpful. 

IMHO, a better UX would be to report errors without requiring the user to dismiss them. Then, even if ESLint is temporarily broken (or broken for just one file), the developer could still keep working without interruption. 

The VSCode Prettier extension handles this nicely. Instead of a modal, it shows status using an icon in the status bar, e.g. 
![image](https://user-images.githubusercontent.com/277214/130492429-5c2968c7-ea87-4703-9ccd-98dfdce2a5ff.png) - ignored file
![image](https://user-images.githubusercontent.com/277214/130492498-268d3bd0-ffb9-470c-8212-5aed01cc856b.png) - OK
![image](https://user-images.githubusercontent.com/277214/130492636-f8542b12-6d0e-4237-bdbe-056461ae8cf6.png) - file can't be parsed

If the user wants to see details behind problems, they can click the status bar to get taken to the output pane to see details. 

Could vscode-eslint do something similar?

**Comment by tizmagik** [comment] 2021-09-10 19:50
+1 to @justingrant 's suggestion of mimicking how Prettier handles this. I'd be happy to contribute a fix if someone could point me in the right direction...

**Comment by dbaeumer** [comment] 2021-09-13 13:15
@tizmagik VS Code is currently working on a language status API which we should use instead. It is in a proposed state here: https://github.com/microsoft/vscode/blob/main/src/vs/vscode.proposed.d.ts#L2933 

IMO we should use this since it will help to declutter the status bar. If you want to give it a try I can help you with that.

**Comment by justingrant** [comment] 2021-09-13 15:41
Here's the issue discussing the new language status API: https://github.com/microsoft/vscode/issues/129037

@dbaeumer the code link in the comment above is no longer valid. It points to a line that doesn't exist anymore.

**Comment by dbaeumer** [comment] 2021-09-14 09:00
New link: https://github.com/microsoft/vscode/blob/main/src/vs/vscode.proposed.d.ts#L2841

**Comment by dbaeumer** [comment] 2021-10-05 12:42
I did the coding but the new language status API is still proposed. Has to wait a little.

**Comment by justingrant** [comment] 2022-05-08 03:29
> I did the coding but the new language status API is still proposed. Has to wait a little.

Is the new language status API available?

**Comment by dbaeumer** [comment] 2022-05-09 07:50
Yes, but I have not merged the branch Yet.

**Comment by Meligy** [comment] 2022-06-26 13:40
> Yes, but I have not merged the branch Yet.

Is there any other issue blocking this to follow it?

**Comment by dbaeumer** [comment] 2022-06-27 07:56
No, just time :-)

**Comment by dbaeumer** [comment] 2022-06-27 07:57
If someone wants to continue this, the branch is: `origin/dbaeumer/languageStatus`

**Comment by charlestbell** [comment] 2022-07-27 18:58
+1 for getting these eslint warnings to go away. They just stack up in the viewport all day long.

**Comment by charlestbell** [comment] 2022-07-27 18:58
+1 for getting these eslint warnings to go away. They just stack up in the viewport all day long.

**Comment by waynebloss** [comment] 2022-08-31 18:50
Is there any fork or alternative to this extension? I don't care when ESLint can't load a config or whatever - I'd just rather see a rid thing in the status bar or whatever, instead of a notification whenever I open a file in a space that isn't configured properly yet...

**Closed** 2022-12-15 18:40 UTC
Labels: feature-request
