### ISSUE TITLE
settings.library.CLIEngine is not a constructor

### ISSUE THREAD

**Issue by sjelfull** [Microsoft/vscode-eslint#293] opened 2017-09-11 14:06 UTC
Upgraded VS Code today to 1.16.0, and i'm suddenly getting this error: `settings.library.CLIEngine is not a constructor`

After checking with/without extensions, I was able to pin it down to vscode-eslint 1.3.0 and https://github.com/Microsoft/vscode-eslint/blob/master/server/src/server.ts#L698

Found no such settings in VS Code or the docs - is this something I'm suddenly missing, after upgrading?

**Comment by chanceaclark** [comment] 2017-09-11 15:13
+1

**Comment by dbaeumer** [comment] 2017-09-11 19:06
@sjelfull & @chanceaclark this can only happend if the extension doesn't find the ESLint library to load and the code path should exit before.

Do you have steps to reproduce since this has to be fixed. I can't reproduce this with my examples. Version 1.3.0 of the library has now support for multi root folders which required a bigger change in the ESLint extension and I abviously broke something :-(

**Comment by Youzhigang** [comment] 2017-09-12 06:08
@sjelfull @chanceaclark  this can be fixed by change the 'eslint.nodePath'. 
```
// "eslint.nodePath": "/usr/local/bin/",
"eslint.nodePath": "/usr/local/lib/node_modules/eslint/bin",
```

**Comment by chanceaclark** [comment] 2017-09-12 14:37
@Youzhigang that did the trick.

**Comment by BiteBit** [comment] 2017-09-13 02:37
+1
Not fixed by **eslint.nodePath**.

**Comment by dbaeumer** [comment] 2017-09-13 07:10
Can any of you provide steps on how to reproduce this (e.g. a GitHub repository I can clone). I would like to understand why this doesn't work anymore.

**Comment by sjelfull** [comment] 2017-09-13 11:24
@dbaeumer Would be helpful if you had any advice on exactly how I could provide steps for you to reproduce this. I basically was updated after restarting VS Code, and that was when this error appeared.

If it helps, I'm managing node with nvm, and the path for eslint is 
```
✗ which eslint
/Users/fred/.nvm/versions/node/v6.6.0/bin/eslint```

**Comment by dbaeumer** [comment] 2017-09-14 07:51
@sjelfull the `nodePath` value has to point to the `node_modules` folder and not bin folder of eslint. In our example something like this:

```
{ "eslint.nodePath": "/Users/fred/.nvm/versions/node/v6.6.0/node_modules" }
```

Regarding steps. Preferable is:

- a GitHub repository to clone
- information about the env (OS, node version, npm version, nvm, yarn, ...)
- steps how to reproduce this in cloned repository.

Will ESLint work for you in a simple setup where you do the following:

- fresh workspace
- npm install eslint
- start code
- Run command ESLint; Create .eslintrc.json file
- create a JS file
- add an eslint error

Will the extension wok ?

**Comment by dbaeumer** [comment] 2017-09-20 08:09
This is very likely a dup of #298.

Did you use relative node path before?

**Comment by dbaeumer** [comment] 2017-10-27 08:25
Closing as dup of #298

**Closed** 2017-10-27 08:25 UTC
Labels: bug
