### ISSUE TITLE
Update README: new task config style for running project-wide lint

### ISSUE THREAD

**Issue by techieshark** [Microsoft/vscode-eslint#392] opened 2018-01-15 21:03 UTC
Following the README instructions to make a task that lints all files, and noticed the task config style provided is outdated: the version provided is [v0.1.0](https://code.visualstudio.com/docs/editor/tasks-v1) but I expected it to be [v2.0](https://code.visualstudio.com/docs/editor/tasks)).

This is the v0.1 config from the README now:
```
{
	"version": "0.1.0",
	"windows": {
		"command": ".\\node_modules\\.bin\\eslint"
	},
	"linux": {
		"command": "./node_modules/.bin/eslint"
	},
	"osx": {
		"command": "./node_modules/.bin/eslint"
	},
	"isShellCommand": true,
	"args": ["*.js"],
	"showOutput": "silent",
	"problemMatcher": "$eslint-stylish"
}
```

I modified this to make a v2 tasks.json config:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run eslint",
            "type": "shell",
            "command": "./node_modules/.bin/eslint *.js",
            "windows": {
                "command": ".\\node_modules\\.bin\\eslint *.js"
            },
            "presentation": {
                "reveal": "never",
                "panel": "new"
            },
            "problemMatcher": ["$eslint-stylish"]
        }
    ]
}
```

Actually, the specific command can be left off if people use npm (or yarn) and have a task set up in their `package.json` (`"lintAll"` below):

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run eslint",
            "type": "npm",
            "script": "lintAll",
            "problemMatcher": ["$eslint-stylish"],
            "presentation": {
                "reveal": "never",
            }
        }
    ]
}
```

Happy to submit a PR, but also happy to let someone else figure out the best wording for the README.

**Comment by techieshark** [comment] 2018-01-15 21:21
See also: #91

**Comment by dbaeumer** [comment] 2018-01-16 09:52
@techieshark PR is welcome. In the readme we should mentioning the following.

- if there is a script in the package.json then the task will be auto detected and the UI will let you pick a problem matcher and will automatically generate a tasks.json for you
- for non npm script users we should provide the tasks.json file as mentioned above.

**Comment by dbaeumer** [comment] 2018-01-16 09:53
Now that I think about we should do even better and the ESLint extension should contribute a task to validate the whole project. Then nothing is necessary at all. Would you want to look into this?

**Comment by techieshark** [comment] 2018-01-16 21:44
@dbaeumer hmm. I'm not sure what you mean by "extension should contribute a task". 

Looking at the capabilities available to extensions, I see that extensions can [contribute commands](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributescommands) and [contribute configuration](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration), as well as [problem matchers](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesproblemmatchers) for use within task definitions, but I didn't see the ability to provide a task. 

Another idea: assuming people commonly create a lint-all-the-things npm script in their package.json (or assuming we can just suggest they do so), would it be possible to:

* have an ESLint extension configuration option which is just a string for the lint-all-the-things npm script name ("lintAll" was what I used in my issue description's last code snippet), and
* contribute a vscode menu command like "ESLint: Lint all the things", and
* when that command is chosen, call 'npm/yarn <lint-all-the-things-scriptname>' (and if the config option isn't present, tell the user to specify it). The problem with this scenario might be that not everyone uses npm - which is where vscode's tasks come in I suppose.

**Comment by fabioimpe** [comment] 2018-01-22 14:53
Hi, I'm trying to configure the task using the npm way, but the package.json where the script is configured is not on the workspace root, I noticed that there is the "path" property which allows to specify the path to the package.json, I set it but the output on the console is always:
`Error: The npm task detection didn't contribute a task for the following configuration:
{
    "label": "Run eslint",
    "type": "npm",
    "script": "lintAll",
    "problemMatcher": [
        "$eslint-stylish"
    ],
    "presentation": {
        "reveal": "never"
    },
    "path": "${workspaceRoot}/client/" // I tried also ./, /, ../, without effect
}
The task will be ignored.`

Am I missing something?
Thank you,
Fabio

**Comment by techieshark** [comment] 2018-01-23 06:31
@fabioimpe, 

I notice the same problem when I try moving my `package.json` into a new folder like `client/` (even after ensuring I had added the root folder to a workspace and add `"path": "${workspaceFolder}/client/"` to tasks.json as you did.  (Note from [docs](https://code.visualstudio.com/docs/editor/variables-reference): "The ${workspaceRoot} variable is deprecated in favor of the ${workspaceFolder} variable.")

At first I thought the `path` property wasn't valid as it isn't directly documented on docs for vscode [tasks](https://code.visualstudio.com/docs/editor/tasks), but then I read on that page: "There are more task properties to configure your workflow. You can use IntelliSense with ⌃Space to get an overview of the valid properties" and tried it:

![task's path property shown via intellisense](https://user-images.githubusercontent.com/1072292/35260526-f010e902-ffc0-11e7-9520-8f14a10a374a.png)

@dbaeumer this may relate to Microsoft/vscode#31217

Two workarounds:

1. You might try using a shell command that calls npm directly, based on the suggestion from [this comment](https://github.com/Microsoft/vscode/issues/35734#issuecomment-336140338).

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "lintAllThings",
            "type": "shell",
            "command": "cd ${workspaceFolder}/client/; npm run lintAll",
            "problemMatcher": [
                "$eslint-stylish"
            ]
        }
    ]
}
```

2. The other thing you could do is add the directory(ies) containing your package.json (`client/` in your case) as workspaces. As long as `package.json` is top level within those workspaces, vscode should find the commands in them.

To do that, create a .vscode directory inside your `client/` directory, and add a new tasks.json like:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run eslint",
            "type": "npm",
            "script": "lintAll",
            "problemMatcher": [
                "$eslint-stylish"
            ],
            "presentation": {
                "reveal": "always"
            },
            
        }
    ]
}
```

When I do that, vscode shows my 'Run eslint' task, along with all the npm scripts it autodetected from my package.json within my subdirectory I added as a workspace folder ("myconfigdir"):

![image](https://user-images.githubusercontent.com/1072292/35260755-f828320c-ffc1-11e7-91e1-285052de8c66.png)

(As you see, the top two commands are from my two different `tasks.json` files, one at the top level `.vscode/` and one in a "`myconfigdir/.vscode`" directory. The

**Comment by dbaeumer** [comment] 2018-01-26 08:04
@techieshark there is: see https://github.com/Microsoft/vscode/blob/master/src\vs\vscode.d.ts#L5635 and https://github.com/Microsoft/vscode-extension-samples/blob/master/task-provider-sample\src\extension.ts#L1

**Comment by fabioimpe** [comment] 2018-01-26 17:00
@techieshark Thank you, for now the solution 1 fit better to me

@dbaeumer broken links :(

**Comment by dbaeumer** [comment] 2018-02-01 15:52
Fixed above links

**Comment by hunhejj** [comment] 2018-05-17 08:54
I have the same problem as @fabioimpe. I would expect that even if the folder containing `package.json` was not part of the workspace, by setting `path` to "the folder of the package.json file that provides the script" should work. Why isn't that the case?

**Comment by dbaeumer** [comment] 2018-05-18 13:32
Two things: actually there is no need anymore to have your hand crafted ESLint task. Simply set `eslint.provideLintTask: true` and the system will automatically provide the tasks even in a multi folder setup.

@hunhejj I am not understanding your problem. Which path are you setting?

**Comment by tvvignesh** [comment] 2018-05-26 21:26
@dbaeumer: I updated to v2.0 style and I got eslint working for my workspace as expected but I am not able to get my problem matchers to work. I am using stylish for eslint as the format and hence tried eslint-stylish, and also tried regex and nothing matched.

Infact, I don't see any matches even for simple regex.

First, I tried using `eslint.provideLintTask: true` and the config added did not seem to be valid since there is no type called eslint. Only shell and process are valid types for v2.0.0 of tasks.json

My tasks.json file:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "tsc-watch",
            "type": "shell",
            "command": "npm",
            "group": "build",
            "args": [
                "run",
                "watch"
            ],
            "presentation": {
                "reveal": "always",
                "panel": "new"
            },
            "problemMatcher": [
                "$tsc-watch"
            ],
            "isBackground": true
        },
        {
            "label": "Run-eslint",
            "type": "shell",
            "linux": {
                "command": "./node_modules/.bin/eslint -f stylish ./**"
            },
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "problemMatcher": [
                {
                    "base": "$eslint-stylish",
                    "fileLocation": "absolute",
                    "applyTo": "allDocuments"
                }
            ],
            "isBackground": true
        }
    ]
}
```

Since this did not work, I also tried a regex like this (partial file given):

```
{
                    "fileLocation": "absolute",
                    "pattern": [
                        {
                            "regexp": "/^([^\\s].*)$/",
                            "file": 1
                        },
                        {
                            "regexp": "^\\s+(\\d+):(\\d+)\\s+(error|warning|info)\\s+(.+?)\\s\\s+(.*)$",
                            "file": 1,
                            "location": 2,
                            "line": 1,
                            "severity": 3,
                            "message": 4,
                            "code": 5,
                            "loop": true
                        }
                    ]
                }
```

My terminal output:

```

> Executing task: ./node_modules/.bin/eslint -f stylish ./** <

/home/vignesh/VIGNESH/app/server/docker-compose.debug.yml
  4:15  error  Parsing error: ';' expected

/home/vignesh/VIGNESH/app/server/docker-compose.yml
  7:11  error  Parsing error: Expression expected

/home/vignesh/VIGNESH/app/server/Dockerfile
  1:5  error  Parsing error: ';' expected

/home/vignesh/VIGNESH/app/server/package.json
  2:8  error  Parsing error: ';' expected

/home/vignesh/VIGNESH/app/server/package-lock.json
  2:8  error  Parsing error: ';' expected

/home/vignesh/VIGNESH/app/server/README.md
  1:0  error  Parsing error: Invalid character

/home/vignesh/VIGNESH/app/server/tsconfig.json
  2:19  error  Parsing error: ';' expected

✖ 7 problems (7 errors, 0 warnings)

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

I have eslint installed both locally and globally and have the required dev dependencies installed as well:

```
"eslint": "^4.19.1",
"eslint-config-google": "^0.9.1",
"eslint-plugin-typescript": "^0.12.0",
"typescript": "^2.8.3",
"typescript-eslint-parser": "^15.0.0"
```
I have my .eslintrc file declared as well with the necessary rules.

I have spent more than 4 hours trying to figure this out with no success. Please help me out.

**Comment by tvvignesh** [comment] 2018-05-26 21:45
Never mind. Solved it. Adding  --ext=.js,.ts along with my arguments solved the issue and started showing up in problem matchers. Don't know why this behavior is since the error came up in the terminal anyway but it did not get matched earlier.

**Comment by dbaeumer** [comment] 2018-05-28 08:12
@tvvignesh good to hear you got it working. If you set `eslint.provideLintTask: true` you don't need to put anything into the tasks.json. `Run Task` should simply show a task to run eslint on the project. Didn't that happen for you.

I will close the issue since with the provided task the problem is IMO fixed and the documentation got updated as well.

**Closed by dbaeumer** 2018-05-28 08:12 UTC
Labels: feature-request, help wanted
