### ISSUE TITLE
Configuration for rule "eqeqeq" is invalid

### ISSUE THREAD

**Issue by gmaggess** [Microsoft/vscode-eslint#194] opened 2017-01-18 20:51 UTC
Hi there,

The plugin seems to be failing with the latest eslint. I now get the following error:

> Configuration for rule "eqeqeq" is invalid: 	Value "always,[object Object]" has more items than allowed.

Visual Studio Code: 1.8.1
Eslint Plugin: 1.2.2
Eslint: 3.13.1

I'm pretty sure my config is right:

extends: 'xyz'
env:
  node: true
  es6: true
  browser: true
rules:
  arrow-body-style: ['error', 'as-needed']
  comma-dangle: ['error', 'always-multiline']
  newline-before-return: error
  no-confusing-arrow: ['error', {allowParens: true}]
  no-duplicate-imports: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  object-shorthand: error
  padded-blocks: ['error', 'never']
  prefer-const: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: error
  symbol-description: error
  template-curly-spacing: error
  object-curly-spacing: ['error', 'always']
  eqeqeq: ['error', 'always', {'null': 'ignore'}]
  comma-spacing: ['error', {'before': false, 'after': true}]

Is anyone else facing this issue?

**Comment by beturs** [comment] 2017-01-19 16:06
I have this config in my settings.json file and works ok
`"eslint.options": {
      "rules": {
        "eqeqeq": 1
      }
    }`

**Comment by dbaeumer** [comment] 2017-02-03 11:24
This works for me using latest ESLint extension and ESLint library. Closing. Please ping if you can still reproduce and provided a test case to do so.

![capture](https://cloud.githubusercontent.com/assets/1931590/22589682/c24ea124-ea0b-11e6-9c66-73b58d3c06e6.png)

**Closed by dbaeumer** 2017-02-03 11:24 UTC
