### ISSUE TITLE
Always get Error: Invalid Options: - Unknown options: typescript.format.semicolons, javascript.format.semicolons in Angular project

### ISSUE THREAD

**Issue by pjc2007** [microsoft/vscode-eslint#1673] opened 2023-06-29 03:46 UTC
I have been getting these errors whenever I update from eslint 7.x to 8.x

I have just updated my Angular project, and due to many other lint errors, started again. Removed all eslint related packages, and my `.eslintrc.json` and ran `ng add @angular-eslint/schematics` hoping this would set  all up correct.

This has added

```
   "@angular-eslint/builder": "16.0.3",
   "@angular-eslint/eslint-plugin": "16.0.3",
   "@angular-eslint/eslint-plugin-template": "16.0.3",
   "@angular-eslint/schematics": "16.0.3",
   "@angular-eslint/template-parser": "16.0.3",
   "@typescript-eslint/eslint-plugin": "5.59.7",
    "@typescript-eslint/parser": "5.59.7",
    "eslint": "^8.40.0",
```

but no ``.eslintrc.json`

But I still get the error in the output window...

```
[Info  - 11:39:43 AM] ESLint server is starting.
[Info  - 11:39:44 AM] ESLint server running in node v16.17.1
[Info  - 11:39:44 AM] ESLint server is running.
[Info  - 11:39:45 AM] ESLint library loaded from: C:\dev\dome\src\Modules\myApp\node_modules\eslint\lib\api.js
Uncaught exception received.
Error: Invalid Options:
- Unknown options: typescript.format.semicolons, javascript.format.semicolons
    at processOptions (C:\dev\dome\src\Modules\myApp\node_modules\eslint\lib\eslint\eslint.js:282:15)
    at new ESLint (C:\dev\dome\src\Modules\myApp\node_modules\eslint\lib\eslint\eslint.js:429:34)
    at q (c:\Users\peter\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:18735)
    at Object.E [as withClass] (c:\Users\peter\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:19173)
    at w.then.g.validate (c:\Users\peter\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:22610)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
Uncaught exception received.
```
Any ideas?

**Comment by dbaeumer** [comment] 2023-06-29 08:19
@pjc2007 does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by pjc2007** [comment] 2023-06-30 00:51
Hi, here is a [test repo](https://github.com/pjc2007/test-eslint) where the issue will happen.

All I have done here is create a new Angular app (I then upgraded to latest v16). I then followed [this](https://www.telerik.com/blogs/angular-basics-using-eslint-boost-code-quality) to add eslint.

In here I can run the lint from the command line...

```
peter@MM0001172 MINGW64 /c/dev/Angular/test-eslint (master)
$ ng lint

Linting "test-eslint"...

All files pass linting.
```
But now if we go to the output for ESLint, (and open a  ts file) we will see the errors...

```
[Info  - 8:16:55 AM] ESLint server is starting.
[Info  - 8:16:55 AM] ESLint server running in node v16.17.1
[Info  - 8:16:55 AM] ESLint server is running.
[Info  - 8:29:44 AM] ESLint library loaded from: C:\dev\Angular\test-eslint\node_modules\eslint\lib\api.js
Uncaught exception received.
Error: Invalid Options:
- Unknown options: typescript.format.semicolons, javascript.format.semicolons
    at processOptions (C:\dev\Angular\test-eslint\node_modules\eslint\lib\eslint\eslint.js:282:15)
    at new ESLint (C:\dev\Angular\test-eslint\node_modules\eslint\lib\eslint\eslint.js:429:34)
    at q (c:\Users\peter\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:18735)
    at Object.E [as withClass] (c:\Users\peter\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:19173)
    at w.then.g.validate (c:\Users\peter\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:22610)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Back when I had Angular 14, I also got the same thing unless I downgraded eslint to 7.32.0. After my upgrades to Angular 16, I had many other eslint issues, so I removed everything and want to start afresh, and the telerik link is the only one that seemed to come close to working (though there are many more TS rules I want to add in, but this is a separate issue)

My vscode info is

```
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

Let me know if need anything else.

**Comment by dbaeumer** [comment] 2023-07-04 07:22
Actually I can't run `npm install` for the workspace provided. Ends up with

```
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to http://per-srv-prbuild:4873/zone.js/-/zone.js-0.13.1.tgz failed, reason: getaddrinfo ENOTFOUND per-srv-prbuild
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

**Comment by dbaeumer** [comment] 2023-07-04 07:22
Any hint

**Comment by pjc2007** [comment] 2023-07-04 07:28
Damn, let me fix that (it is trying to via our private npm repo )

**Comment by pjc2007** [comment] 2023-07-04 07:30
Can just delete the package-lock.json?

**Comment by dbaeumer** [comment] 2023-07-05 07:37
Actually I am not able to reproduce this

<img width="942" alt="capture" src="https://github.com/microsoft/vscode-eslint/assets/1931590/072a04bc-deb7-4c79-af11-02d96aa15bc3">

Any additional steps?

**Comment by pjc2007** [comment] 2023-07-05 09:05
:-( I don't get it, I get it every time. I am getting another dev in my tream to try (but he has gone home so will report back tomorrow)

**Comment by pjc2007** [comment] 2023-07-05 09:19
I found the problem. Was about to send my vscode `settings.json`, and noticed the following settings....

```
 "eslint.options": {
    "typescript.format.semicolons": true,
    "javascript.format.semicolons": true
  },
```

I removed these, and now no more problem!

I am not sure where these came from, but now I have tried in another project as well, and is fine.

**Comment by dbaeumer** [comment] 2023-07-05 11:46
Great you got it working. Will close the issue.

**Closed by dbaeumer** 2023-07-05 11:46 UTC
Labels: info-needed
