### ISSUE TITLE
[Flat config] Extension only read `eslint.config.js` at the root of the project

### ISSUE THREAD

**Issue by joris-fonck-loreal** [microsoft/vscode-eslint#1737] opened 2023-11-20 12:42 UTC
Hello,

I'm recently using the ESLint flat configuration and the configuration file seems to not be handled at the same bevahior than before (The previous configuration file format).

Here is an example of my **monorepo** project:

```
└── project/
    ├── apps/
    │   └── app-1/ <-- Git submodule
    │       ├── ...
    │       └── eslint.config.js
    ├── packages/
    │   └── package-1/
    │       └── ...
    └── eslint.config.js
```

In this situation, ESLint server will load the `eslint.config.js` file at the project root, even if I try to lint (Using auto fix) a file inside `apps/app-1`, which is a Git submodule. This situation is also true if this is not a git submodule.

With the previous file format, like described here:

```
└── project/
    ├── apps/
    │   └── app-1/ <-- Git submodule
    │       ├── ...
    │       └── .eslintrc.cjs
    ├── packages/
    │   └── package-1/
    │       └── ...
    └── .eslintrc.cjs
```

If I lint a file (Using auto fix) inside `apps/app-1`, ESLint server will load the file at `apps/app-1/.eslintrc.cjs` to lint the file.

Regarding my Git configuration (Submodule), I need to have a separate ESLint configuration file because I want to use the configuration in my CI and I also want my submodule to not be coupled with the monorepo configuration.

**I can provide a reproduction project if necessary.**

Regards.

**Comment by phawxby** [comment] 2023-11-20 17:06
Same problem although we're using a monorepo and not submodules. We don't have a root `eslint.config.js` so we're just getting

```
Uncaught exception received.
Error: Could not find config file.
```

**Comment by dbaeumer** [comment] 2023-11-21 08:27
The resolving strategy of flat config files has changed in ESLint itself compared to former configuration files. @joris-fonck-loreal what happens if you validate a file in `apps\app-1` in the terminal using ESLint on the command line while being the the directory `project`?

**Comment by phawxby** [comment] 2023-11-21 10:59
@dbaeumer [cross referencing this](https://github.com/eslint/eslint/issues/17784) which includes a repro.

**Comment by joris-fonck-loreal** [comment] 2023-11-21 11:06
> The resolving strategy of flat config files has changed in ESLint itself compared to former configuration files. @joris-fonck-loreal what happens if you validate a file in `apps\app-1` in the terminal using ESLint on the command line while being the the directory `project`?

When I run `npx eslint apps/app-1/src/main.ts` in `project` folder, it use the `eslint.config.js` from `project` folder.
When I run `npx eslint src/main.ts` in `apps/app-1` folder, it use `eslint.config.js` from `apps/app-1` folder.

**Comment by phawxby** [comment] 2023-11-21 14:13
@dbaeumer reading more of the eslint source code `lintText` calls [`calculateConfigArray`](https://github.com/eslint/eslint/blob/de165c108203c6703516ac651f5b4cac5b241804/lib/eslint/flat-eslint.js#L941) which passes through the `eslintOptions` which has a [`configFile`](https://github.com/eslint/eslint/blob/de165c108203c6703516ac651f5b4cac5b241804/lib/eslint/flat-eslint.js#L367) so that should make it possible to pass in a specific config file even if `eslint` it self is not using the current file path as part of its config file resolution.

**Comment by dbaeumer** [comment] 2023-11-22 08:40
Just to be sure: you both enable flat config by setting `"eslint.experimental.useFlatConfig":true`. The reason for this is that flat config is still experimental in terms of the ESLint API I need to load hence I need a clear hint which API to us.

**Comment by joris-fonck-loreal** [comment] 2023-11-22 08:42
Yes, this setting is enable on my side.

**Comment by phawxby** [comment] 2023-11-22 12:51
> Just to be sure: you both enable flat config by setting `"eslint.experimental.useFlatConfig":true`. in VS Code settings. The reason for this is that flat config is still experimental in terms of the ESLint API I need to load hence I need a clear hint which API to us.

Yep. I created a repro here.
https://github.com/phawxby/eslint-flat-bug

**Comment by dbaeumer** [comment] 2023-11-23 08:18
@phawxby with flat configs the way how configs are resolved changed. They are to my knowledge not resolved relative to the file that is validated anymore, but to the root directory. So you need to let the eslint extension know which of those you use. Adding 

```
  "eslint.workingDirectories": [
    "./packages/package-1",
    "./packages/package-2"
  ]
```

to the settings makes things work for me (I don't see any Error that a config file can't be found. However since the foo.js files are empty I can't tell if validation actually happens.

@joris-fonck-loreal you can check if this helps you as well. If not, can you please provide me with a GitHub repository I can clone with a minimal setup that reproduces what you are seeing.

**Comment by joris-fonck-loreal** [comment] 2023-11-23 14:33
Can we use syntax like this?

```
 "eslint.workingDirectories": [
    "./packages/*"
  ]
```

**Comment by dbaeumer** [comment] 2023-11-24 08:45
@joris-fonck-loreal you actually can but you need to let me know that it is a pattern since it is not easy to determine if no `*` are in it. The syntax will is

```
  "eslint.workingDirectories": [
    { "pattern": "./packages/*" }
  ]
```

I will close the issue since there is little I can do to fix this due to the change in ESLint how flat configs are resolved compared to older configs.

**Closed by dbaeumer** 2023-11-24 08:45 UTC
Labels: info-needed

**Comment by phawxby** [comment] 2023-11-24 09:52
@dbaeumer that works perfectly! Might be worth calling out somewhere that flat configs require a change in config for working directories due to resolution changes
