### ISSUE TITLE
Use eslint specified in `eslint.nodePath` rather than global, for untitled files

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode-eslint#728] opened 2019-08-11 02:51 UTC
For untitled files, why does it forcefully tries to use the global eslint, rather than the one specified in `eslint.nodePath`?

Instead, for untitled files, it should still continue to use the eslint specified in `nodePath`, or whatever it uses by default for workspaces.

I assume there's a technical limitation for this, and if so, then please mention it in the readme, and please suggest a workaround, if one exists. The reason this is a problem for me, is that since upgrading to eslint 6, my plugins cannot be accessed globally, so they are installed in the same dir as my global eslint config file, and now this vscode extension is trying to access the global plugins for untitled files, when I don't have any there anymore.

I'm also getting `Error: Failed to load config "airbnb" to extend from.` when opening JS untitled files, and I've installed `eslint-config-airbnb` locally, globally, in the same project as my global eslint config, etc. but nothing fixes it.

Per these lines: 

https://github.com/microsoft/vscode-eslint/blob/9318950b070c2642fd76f5852ca12e6bee0884aa/client/src/extension.ts#L692-L698

**Comment by dbaeumer** [comment] 2019-08-12 08:45
@garyking where do you define the `nodePath` setting. In the user file or the workspace file. The problem is that for untitled files I actually don't know where it will be saved and hence don't know which setting to consider. But I think the user setting should still be respected.

**Comment by garyking** [comment] 2019-08-12 16:26
I set `nodePath` in the user file (global `settings.json` VS Code) file. Yes, I think that one should be respected.

**Comment by dbaeumer** [comment] 2019-08-13 07:37
I tested it and the user setting is still respected in this case. Can you enable logging 
`"eslint.trace.server": "verbose"` to see which node path is used in the server for the file.

**Comment by dbaeumer** [comment] 2019-08-13 07:37
The log is printed to the ESlint Output channel.

**Comment by garyking** [comment] 2019-08-13 16:42
I can confirm that in untitled files, this extension still uses the global `eslint` package to lint the untitled file, so that's good.

BUT, when I made this thread, I had just upgraded to eslint v6, and had a bunch of problems with this extension and with that upgrade. So since then, I've downgraded to eslint v5. 

From what I remember from when I was testing things, since eslint v6 doesn't support globally installed eslint packages, I had to install the packages locally to my global eslint config file. And so that's why I had to use the `eslint.nodePath` setting to point the extension to my global eslint config file's `node_modules`, which contained all my eslint plugins. (`eslint.nodePath: "/Users/gary/.dotfiles/node_modules/"`)

And when I did that, and opened an untitled file and pasted some JS code to lint, I got the error as seen in the linked source code lines in the first post. My only solution was to disable warnings from eslint-ext, since they popped up every time I set an untitled file to the `javascript` language.

So unfortunately, I can't exactly reproduce this issue again, as I've since downgraded back to eslint v5 due to all the problems with v6. Feel free to close this issue if you feel there is no further action to be taken, or leave it open to be resolved in the future. I just found there were too many problems with eslint v6 itself, and with this extension.

**Comment by dbaeumer** [comment] 2019-08-14 08:29
The is a dedicated issue here to track the ESLint v6 problems: https://github.com/microsoft/vscode-eslint/issues/696

Especially useful might be this comment: https://github.com/microsoft/vscode-eslint/issues/696#issuecomment-519936333

I will close the issue. Please ping if you think there is something that needs to be done other than what is discussed in #696

**Closed by dbaeumer** 2019-08-14 08:29 UTC
Labels: needs more info
