### ISSUE TITLE
import/no-unresolved with webpack modules/aliases in the VS Code

### ISSUE THREAD

**Issue by ValeryVS** [microsoft/vscode-eslint#464] opened 2018-05-07 13:44 UTC
Update:

So, there are few separate issues.

1) To fix issue now, I can adjust my config: replace object spreading with `Object.assign`, or use `babel-register`.
2) Something interpret `Unexpected token ...` as ESLint error and show `no-undesolved`, `no-duplicate` and other.
![2018-05-10 19 55 21](https://user-images.githubusercontent.com/6702994/39882449-7f4fc7bc-548c-11e8-812e-b2694624ac1b.png)
Which is wrong - it should be `SyntaxError` in ESLint output.
![index js__marketnode-2018-05-10-19-53-42-osox6](https://user-images.githubusercontent.com/6702994/39882266-f76732ea-548b-11e8-9a49-57fae9006958.png)
It happens because node v7.9.0 in VS Code can't launch webpack config with object spread syntax.
3) May be `vscode-eslint` can launch `.eslintrc.js` and webpack config with local node, not with bundles one?

----

Original text

Faced with such issue.
There is no errors while launching eslint from terminal.

<img width="1440" alt="2018-05-07 15 39 51" src="https://user-images.githubusercontent.com/6702994/39704860-66d42396-5215-11e8-8a2d-305ca5d1ca3d.png">

<img width="1440" alt="2018-05-07 15 40 02" src="https://user-images.githubusercontent.com/6702994/39704872-6c49bfd4-5215-11e8-8040-4dff8d34bc51.png">

Trying to reproduce error in clean repository, but without success yet.

**Comment by alecf** [comment] 2018-05-07 21:03
This was driving me bonkers and I was getting other odd errors from the import plugin. Just for kicks I put:

```javascript
require('babel-register')
``` 

at the top of my .eslintrc and magically everything seems to work now! (I was already using `babel-register` elsewhere in my project, so it was already installed)

It seems like vscode-eslint runs eslint as a library, and JS imports aren't recognized without `babel-register`

**Comment by ValeryVS** [comment] 2018-05-10 15:12
@alecf 
@dbaeumer 
No, my webpack config doesn't require babel. It use `require()` for imports, etc.

But, when I create some simple webpack configuration - it works.
The reason is definitely in webpack config, but it is something else, not the new syntax.
I will try to debug it this week.

**Comment by ValeryVS** [comment] 2018-05-10 16:46
@dbaeumer 
Found it!

Our project is bundled with node 8.
So, there is some object destructions in webpack configuration.

But there is node v7.9.0 VS Code! Webpack config executed with node 7.9.0 when vscode-eslint try to execute .eslintrc.js with eslint-plugin-import and eslint-import-resolver-webpack.

The wierd thing is, that in most of my files I have strange errors, like at the first image in that issue.
`[eslint] Resolve error: Unexpected token ... (import/no-unresolved)`
`[eslint] Resolve error: Unexpected token ... (import/no-duplicates)`
![screen](https://user-images.githubusercontent.com/6702994/39704860-66d42396-5215-11e8-8a2d-305ca5d1ca3d.png)
And ESLint output in VS Code was pretty clean
![screen-2018-05-10-19-43-03-wx1p2](https://user-images.githubusercontent.com/6702994/39881731-6943fec2-548a-11e8-9613-4f7bcce6e304.png)

But, when I add one more resolver in my `.eslintrc.js`
```javascript
'node': {
    'paths': [
        __dirname,
    ],
},
```
resolve errors are gone, and I, finally, saw the real error

```
[Info  - 19:40:18] ESLint server is running.
[Info  - 19:40:19] ESLint library loaded from: /Users/tasogare/Projects/MY_FOLDER/node_modules/eslint/lib/api.js
[Error - 19:40:20] ESLint stack trace:
[Error - 19:40:20] /Users/tasogare/Projects/MY_FOLDER/configs/webpack/browser.js:46
            ...grab(OLD_STYLE_PAGES_DIR, 'browser.js'),
            ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tasogare/Projects/MY_FOLDER/configs/webpack/development.js:9:23)
```

**Comment by ValeryVS** [comment] 2018-05-10 16:59
So, there are few separate issues.

1) I can adjust my config: replace object spreading with `Object.assign`.
2) Something interpret `Unexpected token ...` as ESLint error and show `no-undesolved`, `no-duplicate` and other.
![2018-05-10 19 55 21](https://user-images.githubusercontent.com/6702994/39882449-7f4fc7bc-548c-11e8-812e-b2694624ac1b.png)
Which is wrong - it should be `SyntaxError` in ESLint output.
![index js__marketnode-2018-05-10-19-53-42-osox6](https://user-images.githubusercontent.com/6702994/39882266-f76732ea-548b-11e8-9a49-57fae9006958.png)
3) May be `vscode-eslint` can launch `.eslintrc.js` and webpack config with local node, not with bundles one?

**Comment by ValeryVS** [comment] 2018-05-10 18:42
1.1
Ok, now I'm understand how to solve this with babel-register
```javascript
require('babel-register')({
    presets: [ 'es2015', 'stage-2' ],
});
```

It wasn't help me before, because, with default settings, it can't handle spread operator.
With `stage-2` it can.

**Comment by dbaeumer** [comment] 2018-05-11 09:38
@ValeryVS thanks for the great analysis. Very helpful.

I will keep the item open to look into 2 and 3

**Comment by viT-1** [comment] 2019-02-14 15:25
https://github.com/Microsoft/vscode-eslint/issues/405#issuecomment-380745912

Still have this issue with VSCode 1.30.1
Project is bundled normally, but eslint plugin underlines me "incorrect" imports in paths with webpack aliases.

Here I found workaround but don't understand how to fix .eslintrc file.
https://github.com/Microsoft/vscode-eslint/issues/464#issuecomment-387205760

No solution to the problem found still?

**Comment by viT-1** [comment] 2019-02-14 15:27
@alecf Can you show your root .eslintrc workaround?
I need to install babel-register globally?

**Comment by viT-1** [comment] 2019-02-14 15:46
I changed webpack config from this:
`resolve: {
        alias: {
            '~': path.resolve(__dirname),
            '@': path.resolve(__dirname, './src'),
        },
    },`
to this:
`resolve: {
        alias: {
            '~': path.resolve(__dirname),
            '@': path.resolve(__dirname, 'src'),
        },
    },`

It seems to be ok. But intellisence not showing fresh added methods in imported file,
but show arguments intellisence after I writing the name of "fresh" method completely.

**Comment by callumlocke** [comment] 2019-05-23 13:46
Thanks @alecf for the workaround. Switching from `.eslintrc` to `.eslintrc.js` and adding `require('@babel/register')` fixed it for me.

Still, I don't think this hack should be necessary, seems like this is a bug in the VSCode plugin, if the CLI works fine without the hack.

By the way, this only started happening to me after upgrading to Babel 7 and switching from `.babelrc` to `babel.config.js`, not sure if that's relevant.

**Comment by dbaeumer** [comment] 2019-05-23 14:12
Regarding https://github.com/microsoft/vscode-eslint/issues/464#issuecomment-463676765

Can someone provide me with a GitHub repository that I can clone with steps on how to reproduce this?

Regarding using a different node version than the one that is shipped in VS Code. Use the `eslint.runtime` setting

**Comment by shapkarin** [comment] 2019-08-27 18:21
Maybe this extention should parse `jsconfig.json`? Users need that file to make IDE [understand aliases](https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases).

**Comment by dbaeumer** [comment] 2019-08-28 10:09
I think if this is necessary then eslint itself or the corresponding eslint plugin should read the `jsconfig.json` file.

**Comment by shapkarin** [comment] 2019-08-28 12:25
I can provide a PR at this weekend. But if that solutions is OK for the author and community.
[Project example](https://github.com/shapkarin/shapkarin.me) with that bug.

**Comment by shapkarin** [comment] 2019-08-28 12:30
I'm not sure about this solution. But here is the [project with that bug](https://github.com/shapkarin/shapkarin.me).

**Comment by shapkarin** [comment] 2019-08-29 15:28
Seems that it's `eslint-plugin-import` problem
https://github.com/benmosher/eslint-plugin-import/issues/496

**Comment by dbaeumer** [comment] 2021-10-01 11:57
I will close the issue. There is now a setting `eslint.runtime` which lets you point to a newer/different runtime than the one we ship in VS Code.

**Closed by dbaeumer** 2021-10-01 11:57 UTC
Labels: feature-request
