### ISSUE TITLE
ESlint-issue-vscode Not working with new release 

### ISSUE THREAD

**Issue by shankarsingh482** [Microsoft/vscode-eslint#645] opened 2019-03-15 07:16 UTC
Hey , Is there any issue with elslint after new update for vs code. 
```
{
  "editor.tabSize": 2,
  "workbench.editor.enablePreview": false,
  "workbench.editor.enablePreviewFromQuickOpen": false,
  "editor.rulers": [
    80
  ],
  "editor.minimap.enabled": true,
  "editor.renderIndentGuides": true,
  "editor.showFoldingControls": "always",
  "files.insertFinalNewline": true,
  "files.autoSave": "off",
  "files.exclude": {
    "**/dest": true,
    "**/dist": true,
    "**/build": true,
    "**/bower_components": true,
    "**/node_modules": true,
    "**/coverage": true,
    "**/log": true,
    "**/logs": true,
    "**/.nyc_output": true
  },
  "files.watcherExclude": {
    "**/bower_components/**": true,
    "**/dest/**": true,
    "**/dist/**": true,
    "**/build/**": true,
    "**/log/**": true,
    "**/logs/**": true,
    "**/node_modules/**": true,
    "**/coverage/**": true,
    "**/.nyc_output/**": true
  },
  "search.exclude": {
    "**/dest": true,
    "**/dist": true,
    "**/build/**": true,
    "**/bower_components": true,
    "**/node_modules": true,
    "**/log": true,
    "**/logs": true,
    "**/coverage": true,
    "**/.nyc_output": true
  },
  "files.trimTrailingWhitespace": true,
  "prettier.eslintIntegration": true,
  "eslint.autoFixOnSave": true,
  "eslint.enable": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact"
  ],
}

```
My settings.json file.

**Comment by dbaeumer** [comment] 2019-03-15 09:41
Works for me. Can you provide me with a GitHub reposistory I can clone that demos what you are seeing.
<img width="356" alt="capture" src="https://user-images.githubusercontent.com/1931590/54422454-d595f680-470e-11e9-88e8-669b3b1e899e.png">

**Comment by shankarsingh482** [comment] 2019-03-15 09:42
Sorry sir , It's enterprise Github repo  will not be able to share that.

**Comment by dbaeumer** [comment] 2019-03-15 09:43
Can you try to distill something. Without reproducible steps hard to tell what is going wrong.

**Comment by shankarsingh482** [comment] 2019-03-15 09:46
I guess it will provide help to you. 
![image](https://user-images.githubusercontent.com/24459676/54422798-40f2bf00-4735-11e9-8e46-34d93f8dcafc.png)

**Comment by shankarsingh482** [comment] 2019-03-15 09:51
![image](https://user-images.githubusercontent.com/24459676/54423175-0dfcfb00-4736-11e9-8c9a-9b0c11bae2ea.png)

**Comment by shankarsingh482** [comment] 2019-03-15 10:04
Error message of eslint.

![image](https://user-images.githubusercontent.com/24459676/54423924-c24b5100-4737-11e9-92f8-250d7031501d.png)

**Comment by dbaeumer** [comment] 2019-03-15 10:06
@shankarsingh482 what messages are in thge output panel. 

This is usually caused by a ESLint setup that calls `process.exit()` which is caused by a not correctly configured ESLint.

What happens if you validate the file using ESLint on the command line?

**Comment by shankarsingh482** [comment] 2019-03-15 10:09
@dbaeumer - We installed the ESlint globally and it runs automatically on save of particular file.

**Comment by dbaeumer** [comment] 2019-03-18 09:03
@shankarsingh482 can you pleasee provide the following informaiton:

- what happens if you run ESLint on file in the terminal?
- the information form the output panel

Best would still be a reprodicable case.

**Comment by shankarsingh482** [comment] 2019-03-18 14:59
@dbaeumer I lower the version of vs code  and ESlint and it starts working.

**Comment by dbaeumer** [comment] 2019-03-19 07:41
@shankarsingh482 I am not trying to say that there is not issue. But without more information as requested here https://github.com/Microsoft/vscode-eslint/issues/645#issuecomment-473824854 there is little I can do to understand why it is not working for you.

**Comment by nikolay-borzov** [comment] 2019-03-23 17:08
Maybe it is not related. For me, ESLint doesn't work if `Eslint: Enable` unchecked in 'User Settings' but checked in 'Workspace Setting'. Once `Eslint: Enable` in 'User Settings' is checked the extension is loaded

**Comment by dbaeumer** [comment] 2019-03-26 10:12
@nikolay-borzov I can not reproduce this:

![capture](https://user-images.githubusercontent.com/1931590/54989069-17008e80-4fb8-11e9-8e57-857ee47c4d9d.png)

Any additional steps?

**Comment by nikolay-borzov** [comment] 2019-03-26 10:33
@dbaeumer, let me investigate it. I'll update this comment with additional details

**Comment by bradennapier** [comment] 2019-04-10 20:05
Mine just times out on every request

```
[2019-04-10 13:05:01.176] [exthost] [error] onWillSaveTextDocument-listener from extension 'dbaeumer.vscode-eslint' threw ERROR
[2019-04-10 13:05:01.176] [exthost] [error] Error: timeout
    at Timeout.define._deliverEventAsync.setTimeout [as _onTimeout] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:439:616)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

```

**Comment by dbaeumer** [comment] 2019-04-11 08:24
@bradennapier does this reproduce for you. If yes can you provide me with steps?

**Closed** 2019-04-22 14:15 UTC
Labels: needs more info
