### ISSUE TITLE
Extension 'ESlint' cannot format file 'index.ts' caused by probing failure

### ISSUE THREAD

**Issue by ipid** [microsoft/vscode-eslint#1168] opened 2021-01-31 14:38 UTC
I encountered the problem `Extension 'ESlint' cannot format file 'index.ts'` while trying to format my TypeScript code in a Vue project. Here is the snapshot:

![image](https://user-images.githubusercontent.com/5251264/106387123-31f18480-6413-11eb-92f4-9e08ae4f9382.png)

And here is my `settings.json` in the workspace:

```json
"eslint.format.enable": true,
"editor.codeActionsOnSave": {
  "source.fixAll.eslint": true
},
"[typescript]": {
  "editor.defaultFormatter": "dbaeumer.vscode-eslint"
}
```

Then, I try to turn on the trace log of plugin with `"eslint.trace.server": "verbose"`. The plugin gives the following output:

```
[Info  - 下午10:17:00] ESLint library loaded from: D:\code\web\***\node_modules\eslint\lib\api.js
[Trace - 下午10:17:01] Received request 'eslint/probeFailed - (4)'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/code/web/***/src/backend/index.ts"
    }
}


[Trace - 下午10:17:01] Sending notification 'textDocument/didClose'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/code/web/***/src/backend/index.ts"
    }
}


[Trace - 下午10:17:01] Sending response 'eslint/probeFailed - (4)'. Processing request took 0ms
No result returned.
```

It seems that probing failure causes the problem. So, I use the settings `"eslint.validate": ["typescript"]` to enforce validating of TypeScript. Finally, **the problem got solved, and soon it is available to format my TypeScript code with ESLint**.

The question has been reported for multiple times (#1086, #850, #951), is it a bug or feature?

The following information may be useful:
- The project is generated by @vue/cli v4
- Problem can be reproduced on any kinds of TypeScript file, even a Hello World
- The `.ts` file can be fixed by `eslint --fix index.ts`
- OS System: Windows 10 20H2
- Node: v14 globally installed, v12 used by VSCode
- VSCode version: v1.52.1
- Extension version: v2.1.14

Thank you for help!

**Comment by dbaeumer** [comment] 2021-02-01 08:19
@ipid actually the probing is "difficult" since it require me to inspect the parser and plugins used and if something changes there I might fail with the probing.

Can you provide me with a Github repository I can clone that demos your behavior. Then I can have a look and see why the probing fails.

**Comment by ipid** [comment] 2021-02-01 16:57
@dbaeumer Here it is: [ipid/vscode-eslint-probing-issue](https://github.com/ipid/vscode-eslint-probing-issue)

Note: The problem seems to be reproducible only on Windows.

Again thank you for your help!

**Comment by mrvisser** [comment] 2021-02-11 21:33
I had this issue just now, same error, not vue or anything, just a typescript project with no TSX files. I

I nuked my `node_modules`, ran `npm install`, then `shift+cmd+p: Reload window` / restart vscode. I didn't update the eslint.validate setting.

Not the solution we need, but perhaps the one that we deserve.

**Comment by dbaeumer** [comment] 2021-02-12 08:29
@mrvisser that is strange. May be a plugin was missing hence the probing didn't work correctly.

**Comment by jamiehaywood** [comment] 2021-03-14 17:17
I'm getting this issue also

### VSCode:
```
Version: 1.54.2
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:09.783Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

### VSCode ESLint
```
v2.1.17
```

### Local `settings.json`
```json
{
    "eslint.format.enable": true,
    "editor.codeActionsOnSave": {
        "source.fixAll": true
    },
    "eslint.trace.server": "verbose",
    "editor.defaultFormatter": "dbaeumer.vscode-eslint",
    "eslint.alwaysShowStatus": true,
    "eslint.debug": true,
    "eslint.packageManager": "yarn",
    "eslint.probe": [
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "html",
        "vue",
        "markdown",
        "json"
    ]
}
```

### User `settings.json`
There is nothing in my user `settings.json` that relates to ESLint

### Reproduction repo:
https://github.com/jamiehaywood/eslint-debug

**Comment by dbaeumer** [comment] 2021-03-15 10:59
@jamiehaywood I can't reproduce this using the repository you provided. Any special steps?

**Comment by jamiehaywood** [comment] 2021-03-15 14:49
@dbaeumer thanks for taking the time to look into this. I'm not sure to be honest, all I know is that when trying to edit `hello.ts` inside my eslint-debug repo I'm getting this:

![image](https://user-images.githubusercontent.com/26779712/111172261-93be1600-859d-11eb-9e8e-b581ed8ca24f.png)

**Comment by jamiehaywood** [comment] 2021-03-16 00:03
So there were two problems which I've since figured out and fixed:
1. I hadn't installed TypeScript... which may have been why it couldn't format the `hello.ts` file (duh...🤦🏻‍♂️)
2. ESLint can't lint json files out the box (it's _**ES**_ Lint double duh...🤦🏻‍♂️🤦🏻‍♂️)

Having spent a good couple of hours trying to figure out how to get VSCode, Prettier, & ESLint playing nicely together, I'm going to raise a PR with example setup & config instructions for my issue #1204.

Just want to say a big thanks to @dbaeumer - the plugin is awesome, and I think I speak for everyone who uses the tool - we would be lost without it.

**Comment by dbaeumer** [comment] 2021-03-17 09:57
@jamiehaywood great that you figured it out. I agree ESLint can be confusing especially you need some configuration to validate anything other than js.

Looking forward to your PR. I will close the issue

@maximumstock can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Closed by dbaeumer** 2021-03-17 09:57 UTC
Labels: needs more info
