### ISSUE TITLE
If there are ESLint in both global and local, please use local's

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode-eslint#13] opened 2015-12-17 01:15 UTC
Currently, `vscode-eslint` seems to choose global installed ESLint if ESLint is installed in both global and local.
But local's should be more apposite version specified by `package.json` for the product.
So if there are ESLint in both local and global, I'd like to use local's.

**Comment by prashaantt** [comment] 2015-12-31 09:09
+1

The other unexpected (IMO) issue is that `vscode-eslint` isn't picking up project-specific plugins if no local `eslint` is found.

```json
{
    "extends": "hapi"
}
```

Here `eslint-config-hapi` isn't getting picked up from my `devDependencies` because I don't have `eslint` in my `devDependencies`, so it's using the global `eslint` and then complaining that `eslint-config-hapi` isn't available globally.

I would expect the following to happen:

1. Use local `eslint` if present, else default to global `eslint`.
2. Use local `.eslintrc` if present, else default to global `.eslintrc`.

**Comment by felixfbecker** [comment] 2016-01-22 23:40
+1
Exactly what @prashaantt said, you have to install all plugins (like `babel-eslint`) globally if you want to use them

**Comment by dbaeumer** [comment] 2016-01-25 16:25
Will try to look into this for the Jab milestone.

**Comment by dbaeumer** [comment] 2016-02-01 13:48
I tested this and vscode-eslint prefers a local installed eslint over a global installed one (this is only for the code eslint). I need to test plugins. They might behave different.

**Comment by dbaeumer** [comment] 2016-02-01 14:12
Plugins work for me as well. In the screen shot below you see a eslint-plugin-objects in action. Both the plugin and the eslint core are installed locally

![capture](https://cloud.githubusercontent.com/assets/1931590/12719584/3e16834a-c8f6-11e5-87ac-832362d1e626.png)

**Comment by dbaeumer** [comment] 2016-02-01 14:15
However what doesn't work is having the plugin locally and eslint core globally

![capture](https://cloud.githubusercontent.com/assets/1931590/12719626/93b874e8-c8f6-11e5-88b3-2c9e771ae058.png)

**Comment by dbaeumer** [comment] 2016-02-01 14:17
However this seems to be consistent to the eslint command line. Running eslint from a shell gives me

![capture](https://cloud.githubusercontent.com/assets/1931590/12719670/ddfa6a48-c8f6-11e5-8303-8c30a4173ee8.png)

in the setup where where the plugin is installed locally and the eslint globally.

**Comment by dbaeumer** [comment] 2016-02-01 14:23
The is actually expected: see http://eslint.org/docs/user-guide/configuring.html

Note: A globally-installed instance of ESLint can only use globally-installed ESLint plugins. A locally-installed ESLint can make use of both locally- and globally- installed ESLint plugins.

**Comment by dbaeumer** [comment] 2016-02-01 14:32
I tested the extends property and that works for me as well:

![capture](https://cloud.githubusercontent.com/assets/1931590/12720058/f299ddec-c8f8-11e5-8f16-453b3508fa49.png)

Can someone of you who sees the problem please provide a workspace (zip, git repository) showing the problem.

**Comment by mysticatea** [comment] 2016-02-01 21:01
I have several projects which are using eslint.
Project A is using eslint 1.10.3.
Project B is using eslint 2.0.0.

npm ecosystem's tools are designed to use together with npm-scripts.
In this case, e.g. `npm run lint`.

```json
{
    "scripts": {
        "lint": "eslint ."
    },
    "devDependencies": {
        "eslint": "1.10.3"
    }
}
```

In npm-scripts, commands such `eslint` uses the local installed one which is specified by package.json.
But vscode-eslint is selecting the global installed one. So it raises errors on new rules or removed rules. It's very inconvenience to me.

Plus, I'm a contributor of eslint. The repository of eslint is linting itself by own code. So I have installed the HEAD of eslint to global by `npm link`. vscode-eslint is always using it on other projects even if there is the version the project specified by package.json. It's very inconvenience to me.

**Comment by mysticatea** [comment] 2016-02-01 21:55
To make sure, this issue's intention is not related to plugins and shareable configs.

**Comment by dbaeumer** [comment] 2016-02-02 09:49
@mysticatea vscode-eslint first tries to use the eslint version installed in the workspace folder. So if you have executed npm install and the package.json lists eslint as a dev dependency eslint should be available and be used by vscode-eslint. That is what I tested (see https://github.com/Microsoft/vscode-eslint/issues/13#issuecomment-177978513). Can you provide me with a test case where this is not the case?

**Comment by dbaeumer** [comment] 2016-02-02 09:54
@mysticatea which OS are you on. I tested all this only on Windows so far.

**Comment by mysticatea** [comment] 2016-02-02 10:51
Thank you for investigating.
I'm on

- Windows 7 Pro 64bit
- nodist (0.6.1)
- node (4.2.3)
- npm (3.5.0)
- VSCode Insiders (0.10.7-insiders)
- vscode-eslint (0.10.11)

I can reproduce this as I execute the following commands on `cmd.exe` at an empty folder.

```bat
mkdir node_modules
echo {"rules": {"keyword-spacing": 2}} > .eslintrc
echo if(true); > test.js
npm install -g eslint@latest
npm install eslint@next
eslint -v
.\node_modules\.bin\eslint -v
code-insiders test.js
```

![issue13](https://cloud.githubusercontent.com/assets/1937871/12747037/12063a08-c9e5-11e5-9b64-f644f43aec09.gif)

The `keyword-spacing` rule has been added on `eslint@next`.
I expected VSCode to show `"Expected space(s) after "if" (keyword-spacing)"`.
But actually VSCode shows `"Definition for rule 'keyword-spacing' was not found (keyword-spacing)"`.
This result is the same as the global installed one's.

![image](https://cloud.githubusercontent.com/assets/1937871/12747185/d688dca0-c9e5-11e5-9292-7b8c176c0a0a.png)

**Comment by dbaeumer** [comment] 2016-02-03 09:04
Here is what I see:

![capture](https://cloud.githubusercontent.com/assets/1931590/12777349/9eb4f814-ca5c-11e5-9a43-62dc9bce4698.png)

The version differences are as follows:

- Windows 10
- node: v4.2.6
- npm: 2.14.12

I do use npm to help me resolve the module to load. Could you do me a favour and run the following npm command for me: npm config get prefix

**Comment by mysticatea** [comment] 2016-02-03 09:11
Oh, interesting.

```
$ npm config get prefix
C:\Users\t-nagashima.AD\nodist\bin
```

And I have several environment variables which is related to this.

```
NODE_PATH        %NODIST_PREFIX%\bin\node_modules
NODIST_PREFIX    C:\Users\t-nagashima.AD\nodist
NODIST_X64       1
PATH             %NODIST_PREFIX%\bin;C:\Users\t-nagashima.AD\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code Insiders\bin;C:\Program Files (x86)\Microsoft VS Code\bin;........

**Comment by dbaeumer** [comment] 2016-02-03 09:24
OK. Thanks. I know what the problem is :-) The NODE_PATH setting which instructs node to look there for modules. I will think what I can change.

**Comment by mysticatea** [comment] 2016-02-03 09:40
Mmm, I removed the variable then try, but I look the same result...

```
$ echo "%NODE_PATH%"
"%NODE_PATH%"

$ echo "%NODIST_PREFIX%"
"C:\Users\t-nagashima.AD\nodist"

$ code-insiders test.js
```

![image](https://cloud.githubusercontent.com/assets/1937871/12778290/5989c5fa-caa5-11e5-9e1a-981cc98634f4.png)

**Comment by dbaeumer** [comment] 2016-02-03 09:49
Can you do me a favour? Create the following two files in that workspace folder:

file.js
```javascript
var child_process = require('child_process');
var path = require('path');

var nodePathKey = 'NODE_PATH';
var moduleName = 'eslint';
var nodePath = [];

function isWindows() {
	return process.platform === 'win32';
}

nodePath.push(path.join(__dirname, 'node_modules'));
child_process.exec('npm config get prefix', function (error, stdout, stderr) {
	if (!error) {
		var globalPath = stdout.toString().replace(/[\s\r\n]+$/, '');
		if (globalPath.length > 0) {
			if (isWindows()) {
				nodePath.push(path.join(globalPath, 'node_modules'));
			} else {
				nodePath.push(path.join(globalPath, 'lib', 'node_modules'));
			}
		}
	}
	var separator = isWindows() ? ';' : ':';
	var env = process.env;
	var newEnv = Object.create(null);
	Object.keys(env).forEach(function (key) { return newEnv[key] = env[key]; });
	if (newEnv[nodePathKey]) {
		newEnv[nodePathKey] = nodePath.join(separator) + separator + newEnv[nodePathKey];
	}
	else {
		newEnv[nodePathKey] = nodePath.join(separator);
	}
	try {
		console.log('NODE_PATH: ' + newEnv[nodePathKey]);
		var cp = child_process.fork(path.join(__dirname, 'resolve.js'), [], { env: newEnv, execArgv: [] });
		cp.on('message', function (message) {
			if (message.command === 'resolve') {
				var toRequire = moduleName;
				if (message.success) {
					toRequire = message.result;
				}
				cp.send({ command: 'exit' });
				console.log(toRequire);
			}
		});
		var message = {
			command: 'resolve',
			args: moduleName
		};
		cp.send(message);
	}
	catch (error) {
		console.log(error);
	}
});
```

and resolve.js
```javascript
'use strict';
process.on('message', function (message) {
    if (message.command === 'exit') {
        process.exit(0);
    }
    else if (message.command === 'resolve') {
        try {
            var result = require.resolve(message.args);
            process.send({ command: 'resolve', success: true, result: result });
        }
        catch (err) {
            process.send({ command: 'resolve', success: false });
        }
    }
});
```
Set the environment variable ATOM_SHELL_INTERNAL_RUN_AS_NODE to 1 and then execute file.js using the "Code - Insider.exe". Something like
```
'C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe' file.js
```

What does the program print to the console I your 'original' setup.

**Comment by mysticatea** [comment] 2016-02-03 10:01
I revived NODE_PATH and did it.

```js
C:\Users\t-nagashima.AD\Documents\GitHub\sand>"C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe" file.js

NODE_PATH: C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules;C:\Users\t-nagashima.AD\nodist\bin\node_modules;C:\Users\t-nagashima.AD\nodist\bin\node_modules
C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\api.js
```

**Comment by dbaeumer** [comment] 2016-02-03 10:12
Thanks. Then my fix will work for you. As you can see I will now resolve your local installed eslint.

**Comment by mysticatea** [comment] 2016-02-03 10:17
OK, Thank you very much for the great support!

**Comment by prashaantt** [comment] 2016-02-03 10:29
I'm sorry I haven't been able to get back to this yet, but I wanted to thank you @dbaeumer for your detailed investigations, and @mysticatea for following up.

**Comment by mysticatea** [comment] 2016-02-03 10:38
I got it.

from 

```js
newEnv[nodePathKey] = newEnv[nodePathKey] + separator + nodePath.join(separator);
```

to

```js
newEnv[nodePathKey] = nodePath.join(separator) + separator + newEnv[nodePathKey];
```

**Comment by dbaeumer** [comment] 2016-02-03 10:39
Correct :-)

**Comment by dbaeumer** [comment] 2016-02-03 10:41
You can patch your eslint installation if you want. I need to wait to update eslint to have a 0.10.7 available since I did other changes which require the latest VSCode.

**Comment by mysticatea** [comment] 2016-02-03 10:45
Yeah, I will do. Thank you very much again!

**Comment by dbaeumer** [comment] 2016-02-03 16:07
The fix of this problem is covered by https://github.com/Microsoft/vscode-languageserver-node/issues/23. 

@mysticatea Thanks again for helping me tracking this down.
@prashaantt if you still see problems with resolving correct configurations please open another issue.

**Closed by dbaeumer** 2016-02-03 16:07 UTC
Labels: bug, needs more info
