### ISSUE TITLE
Take a lot time saving files

### ISSUE THREAD

**Issue by antoniogiroz** [microsoft/vscode-eslint#1575] opened 2022-12-29 11:44 UTC
Type: <b>Bug</b>

Save a file with autoformating enabled:

```json
{
  "css.validate": false,
  "less.validate": false,
  "scss.validate": true,
  "prettier.enable": false,
  "editor.formatOnSave": false,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.fixAll.stylelint": true
  }
}
 ```
And I have to realod the window because the procees never ends

Extension version: 2.2.6
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:32:21.587Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv|--crash-reporter-id 61ba4831-2700-4184-b389-1246d35fbdf0|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by dbaeumer** [comment] 2023-01-09 08:17
@antoniogiroz 

can you please follow the steps here https://github.com/microsoft/vscode-eslint/issues/1344 to find out where the problem comes from. In almost all cases something like this is caused by a slow ESLint rule and there is little the extension can do about that.

**Comment by antoniogiroz** [comment] 2023-01-19 06:42
Hello!

I did the bisect and I came to the conclusion that it only happens when I have ESLint and the GraphQL extension ("Apollo GraphQL" or "GraphQL: Language Feature Support") enabled.

Since I disabled GraphQL code highlighting it has not happened anymore.

Is there any posible solution?

Thanks!

**Comment by dbaeumer** [comment] 2023-01-19 11:03
All I can recommend is to open an issue against the owner of the GraphQL extension.

Any objection to close this one

**Closed** 2023-01-24 08:47 UTC
Labels: info-needed
