### ISSUE TITLE
auto fix on save doesn't work with editor's autoSaveDelay

### ISSUE THREAD

**Issue by spacegoing** [Microsoft/vscode-eslint#195] opened 2017-01-23 11:01 UTC
When I enable `files.autoSaveDelay`, `auto fix on save` doesn't work. It works if I disable editor's auto save mode.

**Comment by dthielman** [comment] 2017-02-01 11:22
Related: with the settings
```
{
    "eslint.run": "onSave",
    "eslint.autoFixOnSave": true
 }
```
auto fix does not appear to work.

ESLint 1.2.2
Windows 7
VSCode data attached
![code_2017-02-01_06-22-08](https://cloud.githubusercontent.com/assets/1881074/22504935/cc4c72ee-e846-11e6-8b39-14decbe81869.png)

**Comment by dbaeumer** [comment] 2017-02-02 16:17
@dthielman this is covered by #158

**Comment by dbaeumer** [comment] 2017-02-02 16:39
@spacegoing this is by design since the save has a high likelihood to infer with the user typing and might remove characters that the user just typed or were incomplete. For this reason fixOnSave is always disabled when autoSave === delay. There is an issue open in VS Code to trigger the fixOnSave with Ctrl+S even if the file is not dirty in this case. See https://github.com/Microsoft/vscode/issues/19723.

There is nothing ESLint can do to fix this. Closing the issue and waiting for resolution of https://github.com/Microsoft/vscode/issues/19723

**Closed by dbaeumer** 2017-02-02 16:39 UTC
