### ISSUE TITLE
monorep/recommended-requiring-type-checking/VS Code ESlint incorrect highlighting

### ISSUE THREAD

**Issue by what1s1ove** [microsoft/vscode-eslint#1619] opened 2023-03-12 19:53 UTC
Hello there,

While using [recommended-requiring-type-checking](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended-requiring-type-checking.ts), the VSCode ESlint extension highlights all the rules that are included in this set of the rules.

<img width="731" alt="image" src="https://user-images.githubusercontent.com/42296182/224569048-9e94b27b-041a-490b-a35f-e7acd7c66e66.png">

But when using CLI ESlint, there will be no errors.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/42296182/224569127-eb0e2796-2f83-4078-83b7-4b001fe894fe.png">

Interestingly, it highlights the rules that are used in `recommended-requiring-type-checking`. With all others, there is no such problem.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/42296182/224569270-78db6076-b3c7-4fd9-92b4-58d67a594f86.png">
<img width="651" alt="image" src="https://user-images.githubusercontent.com/42296182/224569432-8c6e7d12-883c-4ccb-9af7-2fb6ddf16cb0.png">

ESlint config (root):

```yml
root: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module
  project:
    - ./tsconfig.json
    - ./shared/tsconfig.json
    - ./backend/tsconfig.json
    - ./frontend/tsconfig.json

settings:
  typescript: true
  node: true

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - plugin:unicorn/recommended
  - plugin:sonarjs/recommended

plugins:
  - simple-import-sort
```

ESlint config (frontend):

```yml
env:
  browser: true

settings:
  react:
    version: 'detect'

parserOptions:
  project:
    - ./tsconfig.json

extends:
  - ../.eslintrc.yml
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
```

All teammates use different operating systems (Windows, Linux, MacOS). Everyone has this problem.

Tried to find similar issues among other issues but could not find anything similar. This is an open-source educational project. Any recommendations would be grateful 🙏

https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-simpleland

**Comment by dbaeumer** [comment] 2023-03-13 08:23
I cloned the repository but I am not sure what steps to use to reproduce the issue. Could you please provide some for me.

A quick look at the screen shots shows that you are chdir into `frontend` when running eslint. Since this seems to be a working directory for ESLint you need to let the ESLint extension know about this as well. See the setting `eslint.workingDirectories`

**Comment by what1s1ove** [comment] 2023-03-13 10:22
Hey @dbaeumer ! Thanks for your reply!

> I cloned the repository but I am not sure what steps to use to reproduce the issue. Could you please provide some for me.

You can open any file. For example, `frontend/src/index.tsx`.

> A quick look at the screen shots shows that you are chdir into `frontend` when running eslint. Since this seems to be a working directory for ESLint you need to let the ESLint extension know about this as well. See the setting `eslint.workingDirectories`

That helped! Thank you 🙏 🎉

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/42296182/224673597-6e6c9a3c-6a79-422b-b95b-39fcef5e1ac5.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/42296182/224673712-37b8e933-2579-433a-91d3-891dcee1dca4.png">

But I still have a question. Why some of the rules for the eslint plugin work fine, while for others you need to specify this parameter (`eslint.workingDirectories`) in the monorepository?

**Comment by MariaSolOs** [comment] 2023-03-14 03:15
> But I still have a question. Why some of the rules for the eslint plugin work fine, while for others you need to specify this parameter (eslint.workingDirectories) in the monorepository?

My educated guess is that `typescript-eslint` requires some more information about the folder structure in order to discover the corresponding `tsconfig.json` files. Without that it isn't able to query TypeScript for type information and hence that would explain the `any` warnings.

**Comment by dbaeumer** [comment] 2023-03-14 08:45
@MariaSolOs  is correct. The ESLint npm module is very sensitive in regards of the working directory to discover rules, plugins, config files, ....

**Comment by dbaeumer** [comment] 2023-03-14 08:45
I will close the issue. Please ping if something is still unclear.

**Closed by dbaeumer** 2023-03-14 08:45 UTC
Labels: info-needed
