### ISSUE TITLE
Reload eslint config and clear cache

### ISSUE THREAD

**Issue by Akryum** [microsoft/vscode-eslint#477] opened 2018-05-29 13:14 UTC
Is there a way to tell the plugin to reload the configuration and clear the cache?

For example, when using [eslint-plugin-graphql](https://github.com/apollographql/eslint-plugin-graphql) and updating the GraphQL schema, errors in the GraphQL queries are still reported based on the old schema.

**Comment by dbaeumer** [comment] 2018-05-30 09:44
No this is currently not possible.

**Comment by Akryum** [comment] 2018-05-30 09:55
> But you can always reload the Window which will reload the eslint server / plugin.

And kill the terminals 😿

**Comment by dbaeumer** [comment] 2018-05-30 11:33
Valid point.

**Comment by Tbhesswebber** [comment] 2018-10-08 21:51
I have had to refresh my VSCode window every two to three minutes for the past four hours.  Well, I didn't know that that restarted the server until someone told me, so I was really closing VSCode entirely for about half of that time. Being able to manually restart the server is probably not valuable in general, but when you're trying to debug why ESLint and other tooling aren't playing nicely together, it would be **MAGICAL**

**Comment by xaviershay** [comment] 2019-06-24 04:34
> But you can always reload the Window

For those who were also wondering what this means/how to do it: Open the command palette ( `Ctrl + Shift + P` ) and execute `Reload Window` command (type it in until it autocompletes, press enter). Note that it will reload any terminals (I think it's basically equivalent to closing and re-opening VS Code?)

**Comment by parkerault** [comment] 2019-07-07 22:53
I'll 👍 this feature too; mucking about with your .eslintconfig file is a *nightmare* if you have to reload VSCode every time you change a rule to see if it works, especially if you have an underpowered computer and lots of extensions (and if your workplace forces the use of shitty antivirus software that make launching VSCode take 30 seconds!!!).

**Comment by dbaeumer** [comment] 2019-07-08 08:59
The extension should handle changes to `**/.eslintr{c.js,c.yaml,c.yml,c,c.json}` files correctly if located in the workspace. Where is the `.eslintconfig` located.

**Comment by dbaeumer** [comment] 2019-07-08 09:00
I will accept a PR that add a corresponding command to the extension.

**Comment by parkerault** [comment] 2019-07-11 00:38
I didn't realize until later that you only have to close and re-open the *file*. That, and a combination of errors were making me think I had to reload the whole instance. I think the problem is more with the UX around presenting errors in the eslint config for new users. Perhaps a notification that an eslintrc file was found but can't be loaded because x, y, and z.

**Comment by futagoza** [comment] 2019-08-27 09:40
This is really becoming a headache when:

1. Linting `.ts` files because the problem now is that when using `"include": [ "**/*.ts" ]` in my `tsconfig.json`, the ESLint server will read it and get the current `.ts` files, but if I add a new `.ts` file to my project, `typescript-eslint` will throw an error because it's not in the project files list passed to it at the start (I'm presuming something along this line is what's going on).

2. Updating eslint config's and/or plugins via npm/yarn install. I keep forgetting to reload the window in this case and mostly remember when I've got some important terminal task running 😢

@dbaeumer Do you mean a command like `Reload Window` but for the ESLint plugin? If so, it's definitely what I'm looking for.

**Comment by dbaeumer** [comment] 2019-08-28 12:00
@futagoza the `*.ts` is an interesting case since we should only react to this when validating TypeScript. 

For the rest the plugin actually should react and reparse things after changes to the following patterns:

```
'**/.eslintr{c.js,c.yaml,c.yml,c,c.json}'
'**/.eslintignore'
'**/package.json'
```

The case that is not covered are arbitrary changes to the `node_modules` folder. IMO this is fine since usually users run `npm install` with save or save-dev.

**Comment by futagoza** [comment] 2019-09-21 16:52
@dbaeumer It seems either this isn't the case anymore, or the ESLint plugins aren't being reloaded when there are changes to the `.eslintrc*` config files (the files are in the root of the workspace).

```js
// .eslintrc*
{

    "extends": "@futagoza",
    "root": true

}

// tsconfig.json
{
    "extends": "@futagoza/tsconfig",
    "include": [ "." ]
}

// src/tsconfig.json
{
    "extends": "@futagoza/tsconfig/node",
    "include": [
        "**/*.ts"
    ],
    "compilerOptions": {
        "outDir": "../out",
        "rootDir": "."
    }
}
```

Both compiling and linting work fine via the CLI, but vscode-eslint complains every time I create a new file. I've tried modifying the `.eslintrc*` file and saving, but there's no noticeable change, and I still get the error until I reload the window.

**Comment by dbaeumer** [comment] 2019-09-25 10:10
@futagoza can you provide me with a GitHub repository I can clone that demos this? But as said adding new TS files is currently not handled correctly.

**Comment by gwsbhqt** [comment] 2019-10-08 09:03
@dbaeumer If you add a new ts file and you get an error, try adding `"createDefaultProgram": true` in parserOptions

**Comment by gwsbhqt** [comment] 2019-10-08 09:06
I also encountered the same problem, it seems that eslint will only verify the file when it is reloaded. When I fixed these errors, the old error message still exists. This is very frustrating. Does anyone know of any way to solve this problem?

**Comment by BertelBB** [comment] 2019-10-09 06:49
Something is definitely not how it should be, this is happening to me on a daily basis. ESLint starts hanging, showing errors where there are none and auto-formatting stops working. The only thing that works is reloading vscode.

**Comment by gwsbhqt** [comment] 2019-10-10 01:49
@BertelBB Oh, my God, why is this? I am constantly reloading vscode at least half of my time every day, which is too bad.

**Comment by dzintars** [comment] 2020-01-09 14:23
Same problem there. I'm glad i find this issue and i no more feel lonely. :) I am on i3 tiling window manager, so my terminals are in another pane so i use `CTRL + SHIFT + P > Reload Window` while trying to get typescript linting and formatting to work properly in Lerna monorepo.
Kinda PITA
Take my vote for this.

**Comment by zacaj** [comment] 2020-01-09 14:25
I'm having the same issue as @futagoza.  Every time I add a new Typescript file, the ES Lint plugin doesn't pick it up.  I get a single error on the first line of code complaining the file isn't in my project.  If I run eslint manually via a terminal it works fine.  Only way to get the vs code plugin to work again is to reload the window, which is a pain since I sometimes have 5-10 terminals open.  While it'd be nice to fix this specific bug, it seems a more general solution of a command (via CTRL+SHIFT+P) to restart the plugin/server somehow would be more generally useful

**Comment by dbaeumer** [comment] 2020-01-10 09:23
Actually this works for me. Can someone provide a GitHub repository I can clone with steps how to reproduce this.

![cast](https://user-images.githubusercontent.com/1931590/72141506-493a7b80-3393-11ea-8600-da434c68f800.gif)

**Comment by mb21** [comment] 2020-06-10 07:59
We seem to be having this problem when switching git branches on the terminal... it always complains "does not match the underlying filesystem" afterwards, which is quite annoying. But yes, [reloading window](https://github.com/microsoft/vscode-eslint/issues/477#issuecomment-504853991) fixes it.

**Comment by ecraig12345** [comment] 2020-06-18 19:59
@dbaeumer Would #845 fix this issue as well, or is some additional step needed to also clear the cache?

**Comment by dbaeumer** [comment] 2020-06-22 08:05
@ecraig12345 good point. I think stopping & restarting the server is the most save thing to do.

**Comment by numfin** [comment] 2020-09-03 09:43
is it seriously not implemented yet?

**Comment by rusakovic** [comment] 2020-09-23 10:26
confirm the issue:
Hot fix for now:
`CMD + shift + p`  and type `typescript: Restart TS server`  or `typescript: Reload Project`

**Comment by leandro-manifesto** [comment] 2020-10-30 20:07
@rusakovic I'm using ESLint and Typescript-ESLint and that workaround **doesn't** work, the error just stays there.

But reloading the window works, obviously.

**Comment by vdh** [comment] 2020-11-13 04:02
this plugin has started caching a bad file path somewhere hidden, causing false positive results that the normal CLI does not report, and it's driving me crazy trying to find a way to clear this plugin's cache 😞

**Comment by dbaeumer** [comment] 2020-11-16 08:31
@vdh a window reload does a hard reload of the ESLint server. So even a command as requested in this issue will not help you.

**Comment by dbaeumer** [comment] 2021-03-11 07:50
Version 2.1.17 now contains a Restart Server command.

**Closed by dbaeumer** 2021-03-11 07:50 UTC
Labels: feature-request, help wanted

**Comment by metasean** [comment] 2021-03-11 23:40
Of course, to actually use the 2.1.7 update VS Code requires a reload, which is exactly what this ticket's functionality is supposed to avoid. 😩

Regardless, @dbaeumer - thank you for adding the server restart functionality!  (It will make life easier in the near future.)

**Comment by metasean** [comment] 2021-03-11 23:52
@dbaeumer - Tangential confused observation, you mentioned the 2.1.17 release, I am able to update to the 2.1.17 in my VS Code, and the package.json indicates the main branch is at [version](https://github.com/microsoft/vscode-eslint/blob/main/package.json#L5) 2.1.17, _however_ when I look at the [tagged versions](https://github.com/microsoft/vscode-eslint/tags) they stop at `release/2.1.14` and `prerelease/2.1.15-next.1` (i.e. there's no `release/2.1.16` or `release/2.1.17`).

**Comment by dbaeumer** [comment] 2021-03-12 08:02
@metasean thanks for reporting the missing tags. My fault. For the reload on new version install: this is VS Code and nothing the extension can fix by itself.

**Comment by dbaeumer** [comment] 2021-03-12 08:06
I added the tags.

**Comment by nick-khoury** [comment] 2021-03-17 17:34
Deleting the `.eslintcache` file in my project root directory worked for me.

**Comment by al3x-huang** [comment] 2021-03-26 22:46
> Version 2.1.17 now contains a Restart Server command.

How do you actually use this command?

**Comment by biro456** [comment] 2021-03-27 00:05
@al3x-huang Open the Command Palette (by default `ctrl + shift + P` on Windows) and search for `ESLint: Restart ESLint Server`.

**Comment by mckravchyk** [comment] 2021-09-17 05:03
+1, it would be very useful when developing an Eslint plugin.

**Comment by Ebuall** [comment] 2021-12-08 08:04
Only changing the config file helped to clear stale errors from unhealthy interaction between git and eslint
