### ISSUE TITLE
pnpm, eslint & typescript - Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js

### ISSUE THREAD

**Issue by tomenden** [microsoft/vscode-eslint#1373] opened 2021-11-15 09:46 UTC
In my project, using pnpm, Node v14.6.0, Eslint 7.23.0 and the plugin's latest version, I get this error:
`Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js`

Unfortunately, I cannot share the project itself to allow for easy reproduction.
I went through all the relevant issues and tried the suggestions without any luck.

In the dir in which I open `code`, I successfully run `which pnpm` (I saw this was referenced in another issue), and also running from the terminal `pnpm run eslint` is successful.
I set my Workspace Settings for the plugin to use `pnpm` as the package manager.

Any advice on how I can debug this further?

It might be worth noting that the `.eslintrc.js` in question is not the one in my project, but rather one referenced from one of my dependencies, which my `.eslintrc.js` extends.

**Comment by dbaeumer** [comment] 2021-11-15 13:48
Did you set the settings `eslint.packageManager` to `pnpm`

**Comment by tomenden** [comment] 2021-11-15 17:26
> Did you set the settings `eslint.packageManager` to `pnpm`

Yes

**Comment by dbaeumer** [comment] 2021-11-16 08:44
Without reproducible steps (best a GitHub repository to clone) it is hard to say why it is not working.

**Comment by tomenden** [comment] 2021-11-16 18:28
Thanks for your help. I will try to create a minimal reproducible repo and send it over.
Is there any way for me to further debug this myself? 
As far as I understand, the eslint plugin should basically run `eslint` on the dir in which the workspace is open, is it not so?

**Comment by tomenden** [comment] 2021-11-17 20:23
I found that the issue has to do with `public-hoist-pattern[]` I have defined in my .npmrc. Does this give any relevant clues that could help?
My issue with creating a reproducible repo is that most of the packages used by the project are private.
The reason for the `public-hoist-pattern` is that this is how the project runs in my CI environment which I don't have control over, and I want to run my local project in an environment as close as possible to CI.

I will give another try to creating a reproducible repo over the weekend but really hoping that this will give some clues.
Thanks a lot for your help.

**Comment by tomenden** [comment] 2021-11-17 20:28
To add more (hopefully useful) info:
Only some of my packages are hoisted, but not all. And eslint specifically is NOT.

Also, I want to reiterate - the command works fine in the command line (running `pnpm eslint` or `npm run eslint`)

**Comment by dbaeumer** [comment] 2021-11-18 14:31
Are you using a mono repository. It might be a problem of working directories and the setting `eslint.woringDirectories` might be your friend.

**Comment by simontegelid** [comment] 2021-12-12 12:09
I also get this error. Here is a bit more info:
```
(node:72304) UnhandledPromiseRejectionWarning: Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Cannot find module '/path/to/project/node_modules/eslint-scope/dist/eslint-scope.cjs'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:961:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:954:15)
    at resolveExports (internal/modules/cjs/loader.js:439:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:479:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:921:27)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/path/to/project/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint-scope/index.js:14:24)
```

node v16.13.1
"@typescript-eslint/eslint-plugin": "^5.6.0",
"@typescript-eslint/parser": "^5.6.0",

**Comment by dbaeumer** [comment] 2021-12-13 08:40
As said earlier it would be great to have a GitHub repository I can clone that demos that.

@simontegelid what happens when you run eslint in the terminal?

**Comment by simontegelid** [comment] 2021-12-13 09:27
In the terminal it works just fine, so I made a npm script as a workaround for now. I'll see if I can arrange a repro repo. I think that the issue might have been resolved with a vscode restart, but not 100 % sure what's going on behind the scenes to be honest.

**Comment by dbaeumer** [comment] 2021-12-14 10:28
OK. Ping me when the repro is ready.

**Comment by dbaeumer** [comment] 2022-03-02 11:46
This issue has been closed because it needs more information and has not had recent activity. See also our issue reporting guidelines.

Happy Coding!

**Closed by dbaeumer** 2022-03-02 11:46 UTC
Labels: needs more info

**Comment by kelly-tock** [comment] 2022-05-24 21:40
came across this while migrating a repo I work on to pnpm. I had to one by one hoist as described here. happy to repro if we want to dive back in. 

I have:
pnpm 7.1.5
a mono repo:
app1
- .eslintrc.js extends shared-eslint-config, and installs it as a workpsace dependency in pnpm
app2
- .eslintrc.js extends shared-eslint-config, and installs it as a workpsace dependency in pnpm
shared-eslint-config



and from terminal eslint works fine without hoisting, but I added this:
```
public-hoist-pattern[]=*eslint-plugin-*
```
in my .npmrc file. 

and that cleared it up for me. 

I tried various settings as well from other similarly reported issues:

settings.json:

```
  "eslint.nodePath": "/Users/username/admin-pnpm/node_modules/.pnpm/node_modules",
  "eslint.runtime": "/Users/username/Library/Caches/fnm_multishells/9686_1653421493848/bin/node",
  "eslint.workingDirectories": [ "./app1", "./app2" ],
  "eslint.packageManager": "pnpm",
  "npm.packageManager": "pnpm",
```

without hoisting I get this:
```
Uncaught exception received.
Error: Failed to load plugin 'jsx-a11y' declared in '.eslintrc.js » shared-eslint-config': Cannot find module 'eslint-plugin-jsx-a11y'
Require stack:
- /Users/username/admim-pnpm/app1/__placeholder__.js
Referenced from: /Users/username/admim-pnpm/shared-eslint-config/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.resolve (/Users/username/admin-pnpm/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (/Users/username/admin-pnpm/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1017:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (/Users/username/admin-pnpm/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:837:29)
    at ConfigArrayFactory._loadExtends (/Users/username/admin-pnpm/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:779:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/username/admin-pnpm/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/username/admin-pnpm/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
```

**Comment by bryantobing12** [comment] 2022-09-08 13:53
still not solved for me. i'm using `eslint-config-airbnb-typescript` which uses `@typescript-eslint/eslint-plugin` as peers, I set `auto-install-peers=true` in `.npmrc`. But @typescript-eslint/eslint-plugin not added to node_modules, even though it's listed in `pnpm-lock.yaml`

**Comment by vim-daniel** [comment] 2022-10-03 14:39
I've created a new issue as this was closed because of lack of reproduction

Added this reproduction, hope this can get resolved soon 😞
https://github.com/vim-daniel/eslint-pnpm-workspace-reproduction

**Comment by taoliujun** [comment] 2022-12-13 02:15
@tomenden thks. i used `public-hoist-pattern` to set depenencies of eslint bundle to top directory in node_modules. then eslint find plugins.

**Comment by hafeyang** [comment] 2024-12-02 06:35
For me ,  I found `packages/[package]/node_modules/@repo/config-eslint` exists


```
// .eslintrc.js
const sharedConfig = require("@repo/config-eslint/next.js");
module.exports = {
  ...sharedConfig,
};

```

solved this issue
