### ISSUE TITLE
GitLens commit messages being checked by ESLint

### ISSUE THREAD

**Issue by JakubKoralewski** [Microsoft/vscode-eslint#602] opened 2019-01-23 12:07 UTC
I made a commit that mentions console logs. GitLens displays that commit message inside the file and place where the changes were made and for some reason ESLint is taking this into consideration, as far as I understand.

I think this is pretty funny:
![](https://i.imgur.com/h9MEI4o.png)

**Comment by dbaeumer** [comment] 2019-01-24 11:02
This must be caused by something else since I can't repro this. 

![capture](https://user-images.githubusercontent.com/1931590/51674030-d8f2e880-1fcf-11e9-8add-9fdf9681e0f3.png)

Any additional steps ?

**Comment by JakubKoralewski** [comment] 2019-01-24 13:01
Only thing else I can think of is that along with the commit message the actual commit may have removed a console.log in that exact place.

It must have been fixed with a restart of VSCode / plugin / ESLint server since the error is gone now:

![](https://i.imgur.com/nlFR0QF.png)

**Comment by dbaeumer** [comment] 2019-01-25 08:15
@JakubKoralewski thanks for getting back to me. Without reproducible steps hard to fix. I will close the issue for now. If you see it again and provide more information post them here and I am happy to reopen.

**Closed by dbaeumer** 2019-01-25 08:15 UTC
Labels: needs more info
