### ISSUE TITLE
Quick Fix popup stopped suggesting "Add missing import" for JS

### ISSUE THREAD

**Issue by croraf** [microsoft/vscode-eslint#1326] opened 2021-08-28 10:58 UTC
- VS Code Version: 1.59.1
- OS Version: Linux x64 5.4.0-45-generic

Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:54:37.513Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.4.0-45-generic

Steps to Reproduce:

1. Context: 
 - have a JS project with `package.json` with `"type": "module"` property.
 - Have ESLint extension installed, eslint dependency installed locally with `npm install eslint`
 - Have the following eslint configuration file `.eslintrc.cjs`:

```
module.exports = {
  'env': {
    'node': true,
    'es2021': true,
  },
  'extends': 'eslint:recommended',
  'parserOptions': {
    'ecmaVersion': 12,
    'sourceType': 'module'
  },
  'rules': {
  }
};
```

2. have two JS files `first.js` and `second.js`

```
// second.js
const myItem = 5;
export {myItem};
```

```
// first.js
const temp = myItem;
```

During typing of `myItem` in `first.js` the editor does suggest me to complete it and import, and on confirm it does complete and import `myItem`. (this part works even without ESLint extension and library)

But, if it is already completed, it does get underlined as a missing error and you can open a Quickfix popup. But in the Quickfix popup there is no suggestion to "Add the missing import".
![Screenshot from 2021-08-28 12-53-06](https://user-images.githubusercontent.com/19698636/131215682-c85f9e2f-1ae9-4644-84bc-a75c2961c3f7.png)
![Screenshot from 2021-08-28 12-55-07](https://user-images.githubusercontent.com/19698636/131215733-2985b5b2-8cf6-4fd4-9904-c3425c99a779.png)

The "Add the missing import" suggestion was present until sometime in the mid 2021. (But perhaps I disabled something in the settings also.)

**Comment by croraf** [comment] 2021-08-28 10:58
This is a copy of this issue opened on the vscode repository: https://github.com/microsoft/vscode/issues/131840

**Comment by dbaeumer** [comment] 2021-08-30 07:22
I am not sure what exactly the issue is. Running eslint in the terminal shows exactly the same errors than the eslint extension does

```
dirkb:~/Projects/../1326 $ ./node_modules/.bin/eslint first.js

/home/dirkb/Projects/playgrounds/1326/first.js
  2:7   error  'temp' is assigned a value but never used  no-unused-vars
  2:14  error  'myItem' is not defined                    no-undef

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by croraf** [comment] 2021-08-30 09:41
Yes. The problem is in the _Quick Fix_ feature. When error popup shows up in the bottom right corner you have a `Quick Fix` link which opens another popup with suggested fixes. (As shown in the images)


The Quickfix popup should suggest to add the missing import but it does not. 

(Perhaps this is not related to `vscode-eslint` but to `vscode`. I'm not sure so I opened also here to check if `vscode-eslint` has something to do with providing the fix suggestions or some other context to `vscode`.)

**Comment by dbaeumer** [comment] 2021-08-31 09:05
When you run eslint in the terminal with the `--fix` option doe the problem get fixed. If not it is not fixable in the extension either. This can be a configuration problem or something ESLint itself doesn't support anymore.

**Comment by croraf** [comment] 2021-08-31 09:58
I actually tried that later yesterday, and it does not get fixed. This is what suggested me that it has nothing to do with `vscode-eslint` extension, because the extension just forwards the autofixable things to the vscode, right?

**Comment by dbaeumer** [comment] 2021-09-01 09:41
The latest update on `vscode-eslint` is from 6/15/2021. Since eslint on the terminal doesn't fix the issue either there is little I can do to fix this. If you ask me the fix came from TypeScript and not from ESLint itself since ESLint is usually single file and wouldn't know from where to import the symbol from.

**Comment by dbaeumer** [comment] 2021-09-01 09:42
I will close the issue.

**Closed by dbaeumer** 2021-09-01 09:42 UTC
Labels: needs more info

**Comment by croraf** [comment] 2021-09-01 09:51
> The latest update on `vscode-eslint` is from 6/15/2021. 

Oh, I see now in the marketplace docs. But here on the github, in code tab it says:
![Screenshot from 2021-09-01 11-48-28](https://user-images.githubusercontent.com/19698636/131650621-90a2cc97-44f6-428a-ac4c-5f68f329150d.png)


> Since eslint on the terminal doesn't fix the issue either there is little I can do to fix this. If you ask me the fix came from TypeScript and not from ESLint itself since ESLint is usually single file and wouldn't know from where to import the symbol from.

Makes sense for now.

**Comment by kbridge** [comment] 2022-12-31 14:50
It's almost 2023 and this problem still seems not fixed yet.

**Comment by dbaeumer** [comment] 2023-01-09 08:13
As said this need to be fixed in TS/JS and not in ESLint.

**Comment by Pefington** [comment] 2023-03-16 06:05
[This works for me](https://github.com/microsoft/vscode/issues/97925#issuecomment-629389601).
