### ISSUE TITLE
Extension somehow ignores options given in package.json

### ISSUE THREAD

**Issue by hogart** [Microsoft/vscode-eslint#20] opened 2016-01-18 16:25 UTC
This is strange, because eslint by default respects options given in package.json in eslintConfig field.
STR:
1. `git clone git@bitbucket.org:hogart/ntwlk.git && cd ntwlk && npm install`
2. `npm test` will lint files according to rules. 
3. Open folder in VS Code and there are errors.

**Comment by hogart** [comment] 2016-01-20 10:48
Not sure what's the difference, but [jscs](https://github.com/Microsoft/vscode-jscs/) extension works properly with similar setup on the same project.

**Comment by dbaeumer** [comment] 2016-01-25 16:21
Could reproduce. Need to understand why this is the case since we delegate config reading to the eslint node module.

**Comment by hogart** [comment] 2016-01-25 22:48
I've found something. You can repeat my steps by setting breakpoint on line 122 of server.ts. 

`cli.executeOnText` calls `cli.getConfigForFile` to determine which set of rules to apply (see eslint sources). `cli.getConfigforFile('d:\some\path')` return config object with empty fields. While `cli.getConfigforFile('d:/some/path')` (note backslashes) return correct config object. And vscode-languageserver.Files.uriToFilePath return path with backslashes `\`.

**Comment by dbaeumer** [comment] 2016-02-01 14:46
@hogart: thanks a lot for the tip. Will have a look.

**Comment by hogart** [comment] 2016-02-01 14:56
Actually I'm not sure this is vscode-eslint issue. Back-slashed (`\`) paths are officially returned from path.normalize, so every node software should know how to handle it. The question is should we raise it to eslint, or create workaround, or may be both? It still bothers me that standalone `eslint .` command works properly.

**Comment by dbaeumer** [comment] 2016-02-01 20:18
I debugged it again and actually the config in package.json is honored. I used eslint version 1.10.3. The path uses backslashes and the actual resolving is happening from the package.json file.,

**Comment by dbaeumer** [comment] 2016-02-01 20:20
@hogart I tried to clone the repository from your first comment but it is not public. If you provide me access to the code or attach a zip with it I will investigate further.

**Comment by hogart** [comment] 2016-02-02 12:04
Very strange, but I can't reproduce it now too.
Probably it was problem of some particular eslint version.

**Comment by dbaeumer** [comment] 2016-02-04 09:53
@hogart thanks. I will close the issue. Pls reopen if you see it again.

**Closed by dbaeumer** 2016-02-04 09:53 UTC
Labels: bug, needs more info
