### ISSUE TITLE
Is there a way to prevent "spam" notifications?

### ISSUE THREAD

**Issue by marbuser** [Microsoft/vscode-eslint#593] opened 2018-12-17 17:37 UTC
This never previously happened, so I'm not sure if this has been a new thing, but when I started coding today I noticed while coding these really annoying popups started showing.

![image](https://user-images.githubusercontent.com/34422459/50104486-1479f480-0265-11e9-83ed-dbe8c895aac3.png)

Is there a way I can disable these since they are pretty annoying. I don't mind having them popup for major stuff like ESLint config errors and such (Like they used to), but having them popup instantly as soon as I delete even a single line of code is pretty frustrating.

**Comment by dbaeumer** [comment] 2018-12-20 09:05
This happens in the ESLint library I use and swallowing them might not be good either. Can you share a GitHub repository that reproduces this. Then I can see if this is a deeper problem in ESLint or a runtime engine problem (e.g. you need to start the server using a different version of node).

**Comment by marbuser** [comment] 2018-12-22 04:51
> This happens in the ESLint library I use and swallowing them might not be good either. Can you share a GitHub repository that reproduces this. Then I can see if this is a deeper problem in ESLint or a runtime engine problem (e.g. you need to start the server using a different version of node).

Hey @dbaeumer 

I'm just using a default Vue CLI 3 project. Not sure entirely if it's to do with the project though since this never happened previously, and only started happening maybe a day or two before I initially posted this issue, which is also the time this extension received an update.
🤔

**Comment by BPScott** [comment] 2018-12-28 07:05
Heya folks, I think this is due to eslint-plugin-prettier not handling the SyntaxError that prettier throws when it is given code it can't parse - in this case malformed HTML in a vue template like `<template><div></template>` (note the lack of a closing `</div>`). As the eslint plugin lints on typing by default you'll have invalid HTML pretty often - as you won't have finished writing the correct closing tags just yet!

I've put up a PR to fix this in https://github.com/prettier/eslint-plugin-prettier/pull/141 and hopefully I intend to merge it tomorrow. By reporting the SyntaxError as an ESLint error you'll get a red squiggly line somewhere in your file, rather than an "problem" notification because eslint crashed.

**Comment by siric1** [comment] 2018-12-28 13:56
Great thank you very much @BPScott I can confirm that it is working as intended in eslint-plugin-prettier 3.0.1!

**Comment by dbaeumer** [comment] 2019-01-08 09:21
Closing the issue then since there is nothing to do for the ESLint extension itself.

**Closed by dbaeumer** 2019-01-08 09:21 UTC
Labels: needs more info
