### ISSUE TITLE
Extension loading time

### ISSUE THREAD

**Issue by sakara** [Microsoft/vscode-eslint#556] opened 2018-10-11 11:30 UTC
- Extension Name: vscode-eslint
- Extension Version: 1.6.0
- OS Version: Windows_NT x64 10.0.17763
- VSCode version: 1.29.0-insider

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 10279,
		"activateCallTime": 102,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

Is this normal that takes more then 10 seconds to load?

**Comment by dbaeumer** [comment] 2018-10-17 09:48
No, and I can't reproduce this. Here is what I see

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 116,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

Any special steps on how to reproduce what you see.

**Comment by dbaeumer** [comment] 2018-10-17 09:51
Actually the activation times are accumulated over reloads. In your case the eslint extension for activated 102 time which in total took 10279 ms which give 100ms per activation which IMO is OK. Closing the issue.

**Closed by dbaeumer** 2018-10-17 09:51 UTC
Labels: needs more info
