### ISSUE TITLE
Feature Request: Add severity "off" to eslint.rules.customizations setting

### ISSUE THREAD

**Issue by edupsousa** [microsoft/vscode-eslint#1241] opened 2021-04-27 23:26 UTC
The customization config will be much more helpful if we could disable some annoying rules on editor. ;-)

PS: I tried to change the rule severity (on customization) to warn or info and set the eslint.quiet config to true, but the "quiet" setting ignores the customized severity.

PS 2: My annoying rule is "import/no-unused-modules", there is a incompatibility with this rule in the way TSServer cache modules, the vscode-eslint keeps flagging my exports even after i imported it on another module, the only solution is to restart the tsserver. :-(

**Comment by dbaeumer** [comment] 2021-04-28 13:03
I like the idea of `off`. @JoshuaKGoldberg are you interested of adding this?

**Comment by JoshuaKGoldberg** [comment] 2021-04-28 13:37
In theory yes, this sounds like a reasonable idea. I don't think I can commit to adding it now but if nobody takes it in a few months I can take a stab.

In practice this particular instance is something that should be addressed at the TSServer cache <> import <> typescript-eslint layer. @edupsousa have you filed any issues on, say, the import ruleset? I worry about allowing people to override things without addressing the root cause.

**Comment by edupsousa** [comment] 2021-04-28 14:22
Hi @JoshuaKGoldberg, i didn't filled any issue because to be honest i'm not 100% sure what the root cause is, the workspace where the problem was raised is pretty messy , i will set a clean environment to investigate this before filling a issue on the import ruleset.

About the feature request, i did some implementation (with no tests), but i didn't opened a pull request cause I'm afraid that it can raise other issues (no experience with this extension source code, sorry). :-|

https://github.com/edupsousa/vscode-eslint/commit/8d5afe0be0d7957a546e800fe52352bee1bf1f9e

**Comment by edupsousa** [comment] 2021-04-28 15:12
Should I open a PR for reviewing?

**Comment by JoshuaKGoldberg** [comment] 2021-05-02 17:39
I'm not a maintainer here but from what I can tell that looks like a great start. Would love to see a PR! 😍

**Comment by dbaeumer** [comment] 2021-05-14 08:42
Merged the PR from @edupsousa

**Closed by dbaeumer** 2021-05-14 08:42 UTC
Labels: feature-request

**Comment by laverdet** [comment] 2021-11-09 06:48
@edupsousa thank you for this contribution. I want to point out that setting a rule's severity to "off" does *not* disable automatic fixes from that rule from leaking through. As an example I tried to set "prefer-const" to "off" since the autofix for that is highly disruptive to the editing experience. The new setting actually creates a pretty confusing experience because there's no graphical callout but the "eslint.codeActionsOnSave" option still modifies your code in place.

**Comment by dbaeumer** [comment] 2021-11-09 08:07
@laverdet this was more or less on purpose since a common use case is to see no errors for this that are easily auto-fixable. There is a second setting `eslint.codeActionsOnSave.rules` that allows to customize which one are honored.

**Comment by laverdet** [comment] 2021-11-09 18:05
@dbaeumer thank you for the tip. Your point about reducing visual noise while editing makes sense. I had problems with `eslint.codeActionsOnSave.rules` but I'll be sure to give it another try once more of the ecosystem has updated their dependencies to eslint 8.x.
