### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Request workspace/configuration failed with message: Cannot read property 'source.fixAll.eslint' of null

### ISSUE THREAD

**Issue by JustFly1984** [microsoft/vscode-eslint#950] opened 2020-04-16 21:20 UTC
Got eslint broken for me since yesterday.

Tried to reinstall plugin, removed all plugins except eslint from vscode, have latest eslint in the project. reinstalled vscode

Output of eslint in vscode:

```
(node:17052) UnhandledPromiseRejectionWarning: Error: Request workspace/configuration failed with message: Cannot read property 'source.fixAll.eslint' of null
    at /Users/justfly/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:8961
    at /Users/justfly/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9255
    at Immediate.<anonymous> (/Users/justfly/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9616)
    at processImmediate (internal/timers.js:439:21)
(node:17052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3522)
(node:17052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3522)
```

I have my settings.json

```json
{
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ],
  "eslint.enable": true,
  "eslint.packageManager": "yarn",
  "eslint.options": {
    "configFile": "./.eslintrc.js"
  },
  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,
  "stylelint.enable": true,
  "stylelint.autoFixOnSave": true,
  "typescript.preferences.importModuleSpecifier": "non-relative",
  "typescript.tsdk": "node_modules/typescript/lib",
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "cSpell.enableFiletypes": [
    "json"
  ]
}
```

vscode 
```
Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:47:00.296Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

My projects running on node 13.11.0

Why does vscode using 12.8.1 node? How can I run vscode with node 13.11.0 ?

I have node running with `nvm`, and default node is also 13.11.0

Had no issues for this setup for long time

PS VS Code runs extensions on the node version that is built into electron (on which VS Code is based). This cannot be changed. https://stackoverflow.com/questions/45062881/custom-node-version-to-run-vscode-extensions

**Comment by JustFly1984** [comment] 2020-04-17 11:29
crosslinking an issue in vscode repo: https://github.com/microsoft/vscode/issues/95519

**Comment by dbaeumer** [comment] 2020-04-17 12:52
I have a fix for this in master but to ensure it is working correctly I tied to reproduce this but I can't. Can you still reproduce this. If so can you provide me with a GitHub repository I can clone.

**Comment by JustFly1984** [comment] 2020-04-17 13:14
@dbaeumer  I'm not sure that it is about the repo itself, but I can provide you access to one of my private repo.

**Comment by JustFly1984** [comment] 2020-04-17 13:16
@dbaeumer https://github.com/JustFly1984/drivefromto-gatsby/invitations
please remove repo after you test fix.

**Comment by dbaeumer** [comment] 2020-04-17 14:44
@JustFly1984  It works for me with my latest preview version. 

Can you please give it a try and let me know if it works for you as well. It is available here: https://github.com/microsoft/vscode-eslint/releases/tag/release%2F2.1.4-next.1 and you can install it using the Install Extension from VSIX command.

Thanks.

**Comment by JustFly1984** [comment] 2020-04-17 22:19
@dbaeumer You are awesome! 2.1.4 is working for me too! Thank you

**Closed** 2020-04-20 08:40 UTC
Labels: needs more info
