### ISSUE TITLE
ESLint keeps prompting "No ESLint configuration found."

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-eslint#133] opened 2016-09-09 00:04 UTC
![eslint](https://cloud.githubusercontent.com/assets/4033249/18371023/3ede24c0-75e6-11e6-9582-40143819b414.gif)

If it's not found ESLint should silence itself if I close the message. The current behavior is not very UX friendly.

**Comment by waderyan** [comment] 2016-09-09 00:05
Duplicate of #122

**Closed by waderyan** 2016-09-09 00:05 UTC
