### ISSUE TITLE
"Problems" window in Panel stops working after a while...

### ISSUE THREAD

**Issue by QAnders** [Microsoft/vscode-eslint#515] opened 2018-08-09 07:32 UTC
The ESLint plugin itself works fine and my files in file explorer are indicated with red, orange and green as expected but the "Problems" window in the Panel view kind of "freezes" after some time.
If I re-start VSCode the Panel is working fine but after a few minutes and switching between files a few times it "freezes" again and shows information but trying to click anything in it nothing happens or it opens the wrong file or a the wrong row.
It also shows outdated information, i.e. Linting errors/warnings that has already been fixed.

Seems it is not updating as i should...

Using ESLint 1.4.12
VSCode 1.25

**Comment by chrumck** [comment] 2018-08-15 17:16
Same here, except I'm on 1.26.0

**Comment by davis1410** [comment] 2018-08-15 17:48
I started seeing this issue when I upgraded to 1.26.0. I'm wondering if it's a similar problem that's being reported here:
https://github.com/Microsoft/vscode/issues/56317

**Comment by sandy081** [comment] 2018-08-15 17:55
Duplicate of https://github.com/Microsoft/vscode/issues/56371

**Comment by dbaeumer** [comment] 2018-08-16 13:48
Closing.

**Closed by dbaeumer** 2018-08-16 13:48 UTC
