### ISSUE TITLE
Failed to apply ESLint fixes to the document. Please consider opening an issue with steps to reproduce.

### ISSUE THREAD

**Issue by whizzbbig** [microsoft/vscode-eslint#1310] opened 2021-08-02 17:05 UTC
Issue Type: <b>Bug</b>

/* O U T P U T */
[Info  - 10:19:30 PM] ESLint server is starting
[Info  - 10:19:30 PM] ESLint server running in node v14.16.0
[Info  - 10:19:31 PM] ESLint server is running.
[Info  - 10:19:31 PM] ESLint library loaded from: /Users/desartist22/Desktop/Experience.me/floema/node_modules/eslint/lib/api.js
(node:14489) UnhandledPromiseRejectionWarning: Error: Failed to load config "standard" to extend from.
Referenced from: /Users/desartist22/Desktop/Experience.me/floema/.eslintrc.js
    at configInvalidError (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
(Use `Code Helper (Renderer) --trace-warnings ...` to show where the warning was created)
(node:14489) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14489) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:14489) UnhandledPromiseRejectionWarning: Error: Failed to load config "standard" to extend from.
Referenced from: /Users/desartist22/Desktop/Experience.me/floema/.eslintrc.js
    at configInvalidError (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
(node:14489) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14489) UnhandledPromiseRejectionWarning: Error: Failed to load config "standard" to extend from.
Referenced from: /Users/desartist22/Desktop/Experience.me/floema/.eslintrc.js
    at configInvalidError (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
(node:14489) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:14489) UnhandledPromiseRejectionWarning: Error: Failed to load config "standard" to extend from.
Referenced from: /Users/desartist22/Desktop/Experience.me/floema/.eslintrc.js
    at configInvalidError (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
(node:14489) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:14489) UnhandledPromiseRejectionWarning: Error: Failed to load config "standard" to extend from.
Referenced from: /Users/desartist22/Desktop/Experience.me/floema/.eslintrc.js
    at configInvalidError (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
(node:14489) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:14489) UnhandledPromiseRejectionWarning: Error: Failed to load config "standard" to extend from.
Referenced from: /Users/desartist22/Desktop/Experience.me/floema/.eslintrc.js
    at configInvalidError (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/desartist22/Desktop/Experience.me/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
(node:14489) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

Extension version: 2.1.23
VS Code version: Code 1.58.2 (Universal) (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id e4c2479c-f96f-4bfa-a570-1766ff2f5c14|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

i am setting up eslint for my boilerplate here is my 
.eslintrc.js

```js
module.exports = {
  root: true,
  extends: ["standard"],
  globals: {
    IS_DEVELOPMENT: "randomly",
  },
  parserOptions: {
    ecmasVersion: 2020,
  },
};
```

i installed all the dependencies 
```json
{
  "name": "floema",
  "version": "1.0.0",
  "scripts": {
    "build": "webpack --progress --config webpack.config.build.js",
    "development": "webpack serve --progress --config webpack.config.development.js",
    "start": "npm run development"
  },
  "author": "whizzbbig",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.14.8",
    "@eslint/eslintrc": "^0.4.3",
    "babel-loader": "^8.2.2",
    "clean-webpack-plugin": "^4.0.0-alpha.0",
    "copy-webpack-plugin": "^9.0.1",
    "css-loader": "^6.2.0",
    "eslint": "^7.32.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-promise": "^5.1.0",
    "eslint-plugin-standard": "^5.0.0",
    "eslint-standard": "^1.0.2",
    "file-loader": "^6.2.0",
    "glslify-loader": "^2.0.0",
    "image-minimizer-webpack-plugin": "^2.2.0",
    "imagemin": "^8.0.0",
    "imagemin-gifsicle": "^7.0.0",
    "imagemin-jpegtran": "^7.0.0",
    "imagemin-optipng": "^8.0.0",
    "imagemin-svgo": "^9.0.0",
    "mini-css-extract-plugin": "^2.1.0",
    "postcss-loader": "^6.1.1",
    "raw-loader": "^4.0.2",
    "sass": "^1.37.0",
    "sass-loader": "^12.1.0",
    "url-loader": "^4.1.1",
    "webpack": "^5.47.1",
    "webpack-cli": "^4.7.2",
    "webpack-dev-server": "^3.11.2",
    "webpack-merge": "^5.8.0"
  }
}

```

</details>

**Comment by dbaeumer** [comment] 2021-08-05 20:09
@whizzbbig any steps. Without very hard to tell what is happening.

**Comment by whizzbbig** [comment] 2021-08-05 22:04
> @whizzbbig any steps. Without very hard to tell what is happening.

you can see in A/B Experiments I'd described what steps i taken

**Comment by dbaeumer** [comment] 2021-08-06 18:21
To ensure we are looking at the same example can you please provide me with a GitHub repository I can clone that demos that. The repository should be self contained and not depend on any global machine state.

**Comment by whizzbbig** [comment] 2021-08-06 23:31
> To ensure we are looking at the same example can you please provide me with a GitHub repository I can clone that demos that. The repository should be self contained and not depend on any global machine state.

i sent you the invite link sir and also thanks for helping me people like me also facing this problem i know can also be helped if i know what was the problem.

**Comment by dbaeumer** [comment] 2021-08-09 08:51
@whizzbbig thanks. Any additional steps. Opening index.js give the following for me in the ESLint output channel:

```
[Info  - 8:49:26 AM] ESLint server is starting
[Info  - 8:49:27 AM] ESLint server running in node v14.16.0
[Info  - 8:49:27 AM] ESLint server is running.
[Info  - 8:49:27 AM] ESLint library loaded from: /workspaces/floema/node_modules/eslint/lib/api.js
[Info  - 8:49:28 AM] ESLint configuration of global 'IS_DEVELOPMENT' in .eslintrc.js is invalid: 'randomly' is not a valid configuration for a global (use 'readonly', 'writable', or 'off')
[Info  - 8:49:39 AM] ESLint configuration of global 'IS_DEVELOPMENT' in .eslintrc.js is invalid: 'randomly' is not a valid configuration for a global (use 'readonly', 'writable', or 'off')
```

No exceptions.

**Comment by whizzbbig** [comment] 2021-08-09 18:00
> @whizzbbig thanks. Any additional steps. Opening index.js give the following for me in the ESLint output channel:
> 
> ```
> [Info  - 8:49:26 AM] ESLint server is starting
> [Info  - 8:49:27 AM] ESLint server running in node v14.16.0
> [Info  - 8:49:27 AM] ESLint server is running.
> [Info  - 8:49:27 AM] ESLint library loaded from: /workspaces/floema/node_modules/eslint/lib/api.js
> [Info  - 8:49:28 AM] ESLint configuration of global 'IS_DEVELOPMENT' in .eslintrc.js is invalid: 'randomly' is not a valid configuration for a global (use 'readonly', 'writable', or 'off')
> [Info  - 8:49:39 AM] ESLint configuration of global 'IS_DEVELOPMENT' in .eslintrc.js is invalid: 'randomly' is not a valid configuration for a global (use 'readonly', 'writable', or 'off')
> ```
> 
> No exceptions.

so the extension isn't working right?

**Comment by dbaeumer** [comment] 2021-08-10 09:13
I don't see the exception you provided in the issue description. Anything I am missing ?

**Comment by whizzbbig** [comment] 2021-08-10 22:14
> I don't see the exception you provided in the issue description. Anything I am missing ?

:( idk y it isn't working at my end should i also give you screen recording

**Comment by dbaeumer** [comment] 2021-08-11 09:07
Yes, it is not working but the reason is not the exception you provided. If you run eslint in the terminal you get:

```
./node_modules/.bin/eslint app/index.js 

Oops! Something went wrong! :(

ESLint: 7.32.0

Error: ESLint configuration of global 'IS_DEVELOPMENT' in .eslintrc.js is invalid:
'randomly' is not a valid configuration for a global (use 'readonly', 'writable', or 'off')
    at /workspaces/floema/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:219:27
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateGlobals (/workspaces/floema/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:215:14)
    at ConfigValidator.validateConfigArray (/workspaces/floema/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:320:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/workspaces/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/workspaces/floema/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:21)
    at FileEnumerator._iterateFilesWithFile (/workspaces/floema/node_modules/eslint/lib/cli-engine/file-enumerator.js:365:43)
    at FileEnumerator._iterateFiles (/workspaces/floema/node_modules/eslint/lib/cli-engine/file-enumerator.js:346:25)
    at FileEnumerator.iterateFiles (/workspaces/floema/node_modules/eslint/lib/cli-engine/file-enumerator.js:296:59)
    at iterateFiles.next (<anonymous>)
```

In general the extension is only working correctly if eslint is working in the terminal as well. They behave more or less the same. Changing it to `readonly` as recommended makes it work for me.

**Comment by dbaeumer** [comment] 2021-08-11 09:08
I will close the issue since this is not caused by the extension itself

**Closed by dbaeumer** 2021-08-11 09:08 UTC
Labels: needs more info

**Comment by whizzbbig** [comment] 2021-08-14 21:49
> I will close the issue since this is not caused by the extension itself

Hi some how I able to find the solution of this problem
by doing

``./node_modules/.bin/eslint --init`` or ``npx eslint --init`` fix it extension start working again

and i also getting error like if i want to see whether it is installed g or not
so i usually do ``eslint --version``
so it gives me error like ``zsh: command not fount: eslint``
to fix this ``npx eslint --version`` which works fine ^

**Comment by whizzbbig** [comment] 2021-08-14 21:50
by wrapping up i wanna thanks to you @dbaeumer  for helping me :)
