### ISSUE TITLE
imports do not work in flat config yarn pnp

### ISSUE THREAD

**Issue by agarwalvaibhav0211** [microsoft/vscode-eslint#1825] opened 2024-04-08 20:00 UTC
While using Flat Configs with yarn pnp, the CLI command works, but eslint Extension throws error

```
Uncaught exception received.
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'eslint-config-custom' imported from yarn-flat-config-eslint-error/a/eslint.config.js
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:887:9)
    at moduleResolve (node:internal/modules/esm/resolve:936:20)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
```

Error also occurs if public packages are imported

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@eslint/eslintrc' imported from yarn-flat-config-eslint-error/eslint.config.js
Did you mean to import @eslint-eslintrc-npm-3.0.2-1fbcfb08c5-d8c92f06bd.zip/node_modules/@eslint/eslintrc/dist/eslintrc.cjs?
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:887:9)
    at moduleResolve (node:internal/modules/esm/resolve:936:20)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
```

Here is a minimal reproduction: https://github.com/agarwalvaibhav0211/yarn-flat-config-eslint-error

**Comment by dbaeumer** [comment] 2024-04-09 12:37
Which version of ESLint are you using. Good support for ESLint flat config requires 3.0.5 pre-release.

**Comment by HajekTim** [comment] 2024-04-10 20:07
I am having the exact same issue.

## Commands to reproduce the error

```
yarn install
yarn add @eslint/js #not needed
yarn add eslint        #not needed
yarn dlx @yarnpkg/sdks vscode
```

## Error message

```
[Error - 9:48:06 PM] An unexpected error occurred:
[Error - 9:48:06 PM] Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@eslint/js' imported from C:\Users\timmi\VSCodeProjects\yarn-flat-config-eslint-error\eslint.config.mjs
Did you mean to import @eslint-js-npm-9.0.0-5e980024c8-10c0.zip/node_modules/@eslint/js/src/index.js?
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:863:9)
    at moduleResolve (node:internal/modules/esm/resolve:912:20)
    at defaultResolve (node:internal/modules/esm/resolve:1105:11)
    at nextResolve (node:internal/modules/esm/loader:166:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:840:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:429:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
```

## Environment data

Version: 1.88.0 (user setup) <br>
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c<br>
Date: 2024-04-03T13:26:18.741Z<br>
Electron: 28.2.8<br>
ElectronBuildId: 27744544<br>
Chromium: 120.0.6099.291<br>
Node.js: 18.18.2<br>
V8: 12.0.267.19-electron.0<br>
OS: Windows_NT x64 10.0.22631<br>

ESLint Extension: v3.0.5 (pre-release)

A reproducible repository can be found here:
https://github.com/HajekTim/yarn-flat-config-eslint-error

**Comment by dbaeumer** [comment] 2024-04-11 09:48
This is a problem with yarn pnp and flat config module files (mjs). See https://github.com/microsoft/vscode-eslint/issues/1620#issuecomment-2033982223

Will close the issue since this is something that needs to be fixed in yarn or the yarn sdk generation.

**Closed by dbaeumer** 2024-04-11 09:48 UTC
Labels: info-needed

**Comment by dbaeumer** [comment] 2024-04-11 10:34
I created https://github.com/yarnpkg/berry/issues/6219 to track this in yarn.
