### ISSUE TITLE
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.

### ISSUE THREAD

**Issue by jez9999** [microsoft/vscode-eslint#1533] opened 2022-10-07 08:29 UTC
I recently added a couple of ESLint rules that required me to add this to my `.eslintrc.cjs` config:

```
	"parserOptions": {
		"ecmaVersion": "latest",
		"project": "./tsconfig.json",
		"parser": "@typescript-eslint/parser"
	},
```

My `.tsconfig.json` looks like:

```
{
	"extends": "@vue/tsconfig/tsconfig.web.json",
	"include": [
		"env.d.ts",
		"src/**/*",
		"src/**/*.vue"
	],
	"exclude": [
		"src/**/__tests__/*"
	],
	"compilerOptions": {
		"allowJs": true,
		"outDir": "dist",
		"noImplicitAny": true,
		"jsx": "preserve",
		"composite": true,
		"baseUrl": ".",
		"paths": {
			"@/*": [
				"./src/*"
			]
		}
	},
	"references": [
		{
			"path": "./tsconfig.config.json"
		},
		{
			"path": "./tsconfig.app.json"
		},
		{
			"path": "./tsconfig.vitest.json"
		}
	]
}
```

This is causing the following error in VS Code in *some* of my TS and JS files:

> Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
> The file does not match your project config: src\lib\game\libHex.ts.
> The file must be included in at least one of the projects provided.eslint

The weird thing is I will get this error in a TS file in a dir, but not in another TS file in the same dir.  If I rename the file with the error (something like `file.ts` -> `file2.ts`), the error will disappear, and it appears when I rename it back, so I assume it's some weird caching issue.  How can I fix it?

**Comment by MariaSolOs** [comment] 2022-10-08 02:12
As @dbaeumer brought up in #1530, this repo just houses the extension that integrates ESLint support in VS Code. Your problem is not caused by this integration, but from your linting setup itself.
That being said, I enjoy helping y'all so let's try to figure out the issue :)

A quick Google search for your issue gives this [result](https://stackoverflow.com/questions/63118405/how-to-fix-eslintrc-the-file-does-not-match-your-project-config). It seems like your `tsconfig` file doesn't include your `.eslintrc` file, so give that a try.

**Comment by jez9999** [comment] 2022-10-10 15:39
@MariaSolOs I'm not getting the error for `.eslintrc`, I'm getting it for a seemingly random collection of `.ts` files in my project.

**Comment by MariaSolOs** [comment] 2022-10-10 16:40
@jez9999 Can you try replacing `"src/**/*"` inside the `include` array by the specific file extension you want (e.g.: `"src/**/*.ts"`)?

**Comment by jez9999** [comment] 2022-10-10 16:43
That gives the same errors.

**Comment by jez9999** [comment] 2022-10-10 16:48
I did: https://github.com/typescript-eslint/typescript-eslint/issues/5765

**Comment by dbaeumer** [comment] 2022-10-21 10:33
I am closing the issue in favour of https://github.com/typescript-eslint/typescript-eslint/issues/5765

**Closed by dbaeumer** 2022-10-21 10:33 UTC
