### ISSUE TITLE
Is it possible to add setting to suppress `Failed to load the ESLint library ..` message from showing

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode-eslint#727] opened 2019-08-09 10:51 UTC
I nearly always get this popup every time I open most projects in VSCode:

![2019-08-09 at 11 49](https://user-images.githubusercontent.com/6391776/62774126-dfdcd680-ba9b-11e9-8ca1-4e3463c971df.png)

Is it possible to add setting to suppress this `Failed to load the ESLint library ..` message from showing?

Thank you.

**Comment by dbaeumer** [comment] 2019-08-09 14:02
@nikitavoloboev this should only happen once per workspace. The problem is that it is very hard to determine whether this is a misconfiguration or whether this is intended. 

Do you see this on a workspace twice?

**Comment by nikitavoloboev** [comment] 2019-08-09 15:43
> Do you see this on a workspace twice?

Don't think so.

But it is still annoying to see it on per workspace basis. Why is it hard to dismiss this message from showing?

Also if it is hard, is it at least possible to dismiss it after some time? Currently to dismiss it, I have to manually dismiss it myself. I would love if it disappeared itself after 2 seconds.

**Comment by dbaeumer** [comment] 2019-08-12 08:04
The notification auto-dismisses however only after 15 seconds. This is VS Code default behavior which I can't overwrite. Instead of adding another custom solution (e.g. a setting in ESLint) I am more in favor of pushing for https://github.com/microsoft/vscode/issues/41767 and 
 https://github.com/microsoft/vscode/issues/46676 in VS Code. I will close this issue for now to see if this can gain some tracking in VS Code itself.

**Closed by dbaeumer** 2019-08-12 08:04 UTC
Labels: needs more info
