### ISSUE TITLE
rulename no longer shows

### ISSUE THREAD

**Issue by wmertens** [Microsoft/vscode-eslint#571] opened 2018-11-02 14:51 UTC
In some recent update, not sure of eslint or this plugin, the eslint rule name stopped showing.

This means I can't easily look it up or disable it.

Can this be reinstated? Preferably, the rulename is the first part of the error message, so it's easy to copy and paste.

**Comment by GStipick** [comment] 2018-11-02 20:29
I am also having the same problem.  It appears that work is being done to fix this though.

Reference:
https://github.com/Microsoft/vscode-eslint/pull/562

**Comment by dbaeumer** [comment] 2018-11-05 09:55
Two things: the missung rule name is caused by a bug in VS Code which is already fixed in Insider and will be available in the next stable version appearing soon.

Due to a [PR](https://github.com/Microsoft/vscode-eslint/pull/530) I got from @loune the quick fix now contains actions to disable a rule. No need to copy paste anymore.

![capture](https://user-images.githubusercontent.com/1931590/47991007-3d955a00-e0e9-11e8-9871-7f3743cb47ba.png)

**Closed by dbaeumer** 2018-11-05 09:55 UTC

**Comment by Friksel** [comment] 2018-11-05 10:42
Thanks for the info @dbaeumer and great to have an action for it! I also just found out that the rule-names are still visible in the 'problems' tab, so there's no need to search for the eslint-names anymore.

**Comment by Friksel** [comment] 2018-11-06 08:42
@dbaeumer When using the 'Suppress ... for this line' we don't get the suppression on the same line, but as a `// eslint-disable-next-line` instead of a `// eslint-disable-line`. I normally put these on the same line as the suppressed line for better readability and less disturbing code flow, but this seems to be impossible with this workflow. Would it be possible to make the '`Suppress .. for this line`' insert the suppress-line on the same line as the code (`eslint-disable-line`) and perhaps move the current behaviour to an additional action to add it to the next line (`eslint-disable-next-line`)? Thanks!

**Comment by dbaeumer** [comment] 2018-11-06 14:57
@Friksel can you please open a separate issue for this?

**Comment by Friksel** [comment] 2018-11-06 16:32
@dbaeumer Hereby: https://github.com/Microsoft/vscode-eslint/issues/573
