### ISSUE TITLE
Eslint shows one warning in all ignored files

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode-eslint#106] opened 2016-07-30 14:30 UTC
Eslint shows this warning in all files which I've ignored via the .eslintignore:

```
File ignored because of a matching ignore pattern. Use --no-ignore to override.
```

I think that this warning should not be shown, as the cli doesn't show it either. Is this default warning intentional, or should it be fixed?

**Comment by dbaeumer** [comment] 2016-09-14 20:06
Can't reproduce using the latest ESLint extension and ESLint version. Closing. @kumarharsh please ping if you can still reproduce.

**Closed by dbaeumer** 2016-09-14 20:06 UTC

**Comment by kumarharsh** [comment] 2016-09-14 21:17
@dbaeumer I'm still getting it. One file where this always comes is the `.eslintrc.js` file in the workspace root.
![2016-09-15 2](https://cloud.githubusercontent.com/assets/760112/18530332/b6747b80-7aee-11e6-95be-ef7c71187632.png)

**Comment by dbaeumer** [comment] 2016-09-19 10:07
@kumarharsh this looks like eslint behavior. Do you see the same message in the terminal ?
