### ISSUE TITLE
Cache probing?

### ISSUE THREAD

**Issue by Kagami** [microsoft/vscode-eslint#963] opened 2020-05-02 10:05 UTC
Hi,

As far as I understand the logic of extension, it always tries to find eslint configuration for file types listed in `eslint.probe`.

So if I create empty directory with empty JavaScript file and start typing in it (and `eslint.run` set to `onType`), I see the following log in the output:

```
[Info  - 12:54:09 PM] No ESLint configuration found in /home/kagami/t.
[Info  - 12:54:10 PM] No ESLint configuration found in /home/kagami/t.
[Info  - 12:54:10 PM] No ESLint configuration found in /home/kagami/t.
[Info  - 12:54:10 PM] No ESLint configuration found in /home/kagami/t.
[Info  - 12:54:10 PM] No ESLint configuration found in /home/kagami/t.
[Info  - 12:54:10 PM] No ESLint configuration found in /home/kagami/t.
[Info  - 12:54:10 PM] No ESLint configuration found in /home/kagami/t.
[Info  - 12:54:10 PM] No ESLint configuration found in /home/kagami/t.
[Info  - 12:54:10 PM] No ESLint configuration found in /home/kagami/t.
[Info  - 12:54:10 PM] No ESLint configuration found in /home/kagami/t.
[Info  - 12:54:10 PM] No ESLint configuration found in /home/kagami/t.
```

It basically tries to find eslint configuration multiple times per second.
It's probably not something to worry about because I can't feel the lag, but it still bothers me a bit.

So the questions are: should it be cached and can it affect performance?

Thanks.

**Comment by dbaeumer** [comment] 2020-05-04 18:53
The problem is that caching / ignoring this will need to reload VS Code if you create such a file in a parent directory. The extension will have no way to detect that and re-evaluate.

Need to value what to do here is best.

**Comment by Kagami** [comment] 2020-05-04 19:02
Maybe it's worth to cache for 1 minute or something like that. Or maybe detect `.eslintrc*` config creation (not sure if VS Code extension API allows that).

**Comment by dbaeumer** [comment] 2020-05-05 10:16
The extension listens to these events but can't outside of the workspace folder.

**Comment by dbaeumer** [comment] 2020-10-23 17:56
I will close the issue. VS Code has no API that allows listening for file events outside of workspace folders.

**Closed by dbaeumer** 2020-10-23 17:56 UTC
Labels: bug
