### ISSUE TITLE
why it's not working for .css files?

### ISSUE THREAD

**Issue by zzzgit** [microsoft/vscode-eslint#1730] opened 2023-11-12 08:23 UTC
<img width="262" alt="image" src="https://github.com/microsoft/vscode-eslint/assets/1060733/8c2f4af7-0026-43e8-9301-6d154be3b4ab">

**Comment by zzzgit** [comment] 2023-11-12 08:26
Eventhough, I added `"eslint.probe"=[..., "css"]`.

**Comment by dbaeumer** [comment] 2023-11-14 11:30
Are eslint errors detected in `css` files when you run eslint in the terminal. If that works can you please provide me with a GitHub repository with minimal setup I can clone that demos that it doesn't work in VS Code.

**Comment by zzzgit** [comment] 2024-01-02 07:57
```json
{
  "eslint.format.enable": true,
  "eslint.probe": [
          "javascript",
          "javascriptreact",
          "typescript",
          "typescriptreact",
          "html",
          "vue",
          "markdown",
          "css"
  ],
  "editor.defaultFormatter": "dbaeumer.vscode-eslint",
  "[css]": {
          // "editor.defaultFormatter": "vscode.css-language-features",
          "editor.defaultFormatter": "aeschli.vscode-css-formatter",
  },
}
```

Eventhrought Ive set like this, the tool wont lint .css files at all.

**Comment by zzzgit** [comment] 2024-01-02 08:00
![image](https://github.com/microsoft/vscode-eslint/assets/1060733/ec9305c9-da38-4451-842f-707e877d46b2)

**Comment by dbaeumer** [comment] 2024-01-08 13:05
@zzzgit can you please provide me with a minimal GitHub repository I can clone that demos that. Very hard to say what is causing this without being able to reproduce.

**Comment by kuoruan** [comment] 2024-08-02 10:32
@zzzgit Finally fixed by set `eslint.validate`
```
  "eslint.validate": [
    "css",
    "scss"
  ],
  ```

**Comment by dbaeumer** [comment] 2024-12-09 07:49
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Closed by dbaeumer** 2024-12-09 07:49 UTC
Labels: info-needed
