### ISSUE TITLE
No linting in Yarn monorepo with PnP

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [microsoft/vscode-eslint#1314] opened 2021-08-10 16:26 UTC
1. I've installed the necessary sdks via `yarn dlx @yanrpkg/sdks vscode`
2. I've configured VSCode to use the typescript version from the sdks of the previous step.
3. I've set up the repo in a manner where I have a structure like so:

```
├── packages/
│   └── main
│           ├── build/
│           ├── src/
│           ├── .eslintrc.js
│           ├── package.json
│           └── tsconfig.json
├── .eslintrc.js
├── package.json
└── tsconfig.json
```

Where the root `.eslintrc.js` and `tsconfig.json` are the base configurations all the other workspaces extend their configurations from.
I've tried the following "eslint.workingDirectories" configurations to point the vscode-eslint plugin to the correct places.

1. [ { "mode": "auto" } ] ..does nothing. No linting happening.
2. [ { "mode": "location" } ] ..does nothing. No linting happening.
3. [ "./packages/main" ] ..does nothing. No linting happening.
4. [ ".\\\packages\\\main" ] ..does nothing. No linting happening.

I also toyed with "pattern"-option as my actual project has much more nested workspaces so ideally, I wouldn't want to manually list all of them. This didn't work either.

I ran the linter manually with CLI and it seems to work properly both from the root and inside the workspace package.

Here are the plugins and what not I use:

```
"@typescript-eslint/eslint-plugin": "^4.29.1",
"@typescript-eslint/parser": "^4.29.1",
"eslint": "^7.32.0",
"typescript": "^4.3.5"
```

Here's the root `.eslintrc.js`:
```javascript
module.exports = {
  root: true,
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended"
  ],
  parser: "@typescript-eslint/parser",
  
  parserOptions: {
    sourceType: "module",
    env: {
      node:  true
    },
    ecmaVersion: 2020
  },
  plugins: [
    "@typescript-eslint"
  ],

  rules: {
    // Omitted for brevity
  }
};
```
And the extending one:

```javascript
module.exports = {
  extends: [ 
    "../../.eslintrc.js"
  ],
  parserOptions: {
    tsconfigRootDir: __dirname,
    project: [
      "./tsconfig.json"
    ]
  }
}
```

The tsconfigs are as follows.  Firstly the root:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "target":  "esnext",
    "module":  "commonjs",

    "strict":             true,
    "removeComments":     true,
    "preserveConstEnums": true,
    "sourceMap":          true,
    "allowJs":            true,
    "incremental":        true,

    "esModuleInterop":                  true,
    "moduleResolution":                 "node",
    "forceConsistentCasingInFileNames": false,
    "resolveJsonModule":                true,
    "skipLibCheck":                     true
  },
  "exclude": [
    "node_modules"
  ],
  "watchOptions": {
    "watchFile":      "useFsEvents",
    "watchDirectory": "useFsEvents",
    "fallbackPolling": "dynamicPriority"
  }
}
```

and the extending config:

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "baseUrl": ".",
    "rootDir": "src",
    "outDir":  "build",
    
    "composite":      true,
    "declarationMap": true
  },
  "include": [ 
    "src/**/*"
  ],
  "exclude": [
    "build"
  ]
}
```

VSCode: 1.59.0
OS: Windows_NT x64 10.0.19042

**Comment by dbaeumer** [comment] 2021-08-11 09:11
@4lph4-Ph4un can you provide me with a GitHub repository I can clone that demos this. This ensures that we use the same version of package and configuration files (e.g. VS Code settings, ...)

**Comment by 4lph4-Ph4un** [comment] 2021-08-11 11:43
https://github.com/4lph4-Ph4un/vscode-eslint-repro, here!

**Comment by dbaeumer** [comment] 2021-08-11 12:31
@4lph4-Ph4un thanks for the repro. Looking at the generated npm scripts for the packages the lint script looks like this `"eslint --resolve-plugins-relative-to \"../../../../\" \"./src/**/*\""` (observe: the additional `-resolve-plugins-relative-to`). You need to let the ESLint extension know about this as well using the `eslint.options` setting. The possible options depend on the version of ESLint you are using and are described here: https://eslint.org/docs/developer-guide/nodejs-api#-new-eslintoptions

However the setting can only provided once. So if these values differ per package then it might still not work.

**Comment by 4lph4-Ph4un** [comment] 2021-08-11 12:39
Hmm!!! Indeed indeed..! Actually, that path is copypaste code that I forgot the refactor for the repro (sorry about that).. the actual path should be "../../" as it is for the main package. The actual codebase luckily has all of their packages nested in the same level, but does that mean that there's a potential recipe for disaster if a project is dependent on using that resolve-plugins flag? As far as I know that has been the only way I have gotten eslint to work in a Yarn monorepo (with the CLI, that is).

**Comment by merceyz** [comment] 2021-08-11 12:40
You can patch ESLint's resolution so it resolves plugins correctly by using https://yarnpkg.com/package/@rushstack/eslint-patch

**Comment by 4lph4-Ph4un** [comment] 2021-08-11 12:43
Yes, the linting started to work immediately when I added that path to `eslint.options.resolvePluginsRelativeTo`! In a general sense, would passing eslint options per workspace be something that should be possible in the future?

@merceyz, yes, but if a tools cli flag would suffice to fix the problem (afaik, that's what that flag is for), I rather use that, than hack it with a plugin which is another extra dependency to my codebase that I would rather do without.

**Comment by dbaeumer** [comment] 2021-08-12 07:47
The problem is that VS Code doesn't support this. If VS Code adds such a support I would be happy to adapt it. Otherwise I would need to roll my own implementation which I would like to stay away from. 

I will close the issue for now.

**Closed by dbaeumer** 2021-08-12 07:47 UTC
Labels: needs more info

**Comment by dbaeumer** [comment] 2021-08-12 07:49
The corresponding VS Code issue is: https://github.com/microsoft/vscode/issues/32693

You might want to vote on it.
