### ISSUE TITLE
Plugin is unresponsive with typescript v4.0.2

### ISSUE THREAD

**Issue by Nokel81** [microsoft/vscode-eslint#1060] opened 2020-08-31 16:46 UTC
I am currently trying to use this plugin in the following environment:

OS: macos 10.15.6
VSCode: 1.48
Plugin: 2.1.8
TS: 4.0.2

But as soon as I type anything that is an error (eg the first `/` in a comment which is also the beginning of a regex expression) that is the only error reported and that error is never retracted (eg after typing the second `/` in a comment).

Expected behaviour: update the red error under-squiggles once the error is no longer valid (did work with typescript 3.X)

Current workaround: force reload the whole VScode window

**Comment by Nokel81** [comment] 2020-08-31 17:05
I have found that I was using an outdated version of the typescript parser, (which coincidentally prints out a warning) maybe that warning should be displayed to the user.

**Comment by dbaeumer** [comment] 2020-09-01 13:37
@Nokel81 are you still experiencing the slowness. If so can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by Nokel81** [comment] 2020-09-01 13:40
Before updating my typescript parser for eslint I was still experiencing the slowness. 

The repo I was working on is LensApp/Lens

**Comment by dbaeumer** [comment] 2020-09-01 13:42
Can you provide steps on how to reproduce. This otherwise very hard to track down.

**Comment by Nokel81** [comment] 2020-09-01 15:54
Sure, 

1. Clone https://github.com/lensapp/lens/commit/cb3e19f2f09b226dfb8b96a874f14e944cd7e5db
2. Run `yarn` 
3. Configure vscode (with the above version) to use the repo version of eslint
4. The error should now occur in any file

To fix the issue git checkout https://github.com/lensapp/lens/commit/8c0ee5dc37d3c21e53dc79f63038b63d9c74985a instead which updates the version of the parser.

**Comment by dbaeumer** [comment] 2020-09-02 11:57
@Nokel81 thanks for the repository. Actually when using TS 4.x with an older version of the eslint TS plugin I get a warning that this is not supported. So moving to 4.x there as well makes sense to me. 

From a extension perspective there sis not much I can do about this. So I opt to close and if you think that is something that needs to be addressed you should open an issue against the typescript/eslint repository.

**Closed by dbaeumer** 2020-09-02 11:57 UTC
Labels: needs more info

**Comment by Nokel81** [comment] 2020-09-02 12:42
I think that displaying the same warning while in VS code would be good

**Comment by dbaeumer** [comment] 2020-09-04 07:29
The warning is displayed in the ESLint output channel. I had code in the past the pop the channel to the front in these case but users opted against this since it is at the end very disturbing

**Comment by Nokel81** [comment] 2020-09-04 12:40
Okay fair
