### ISSUE TITLE
Not working on .vue files

### ISSUE THREAD

**Issue by jonjbar** [Microsoft/vscode-eslint#103] opened 2016-07-22 17:45 UTC
When using vue.js, the following plugin is installed and enabled: https://www.npmjs.com/package/eslint-plugin-vue
eslint from the command line can retrieve problems from .vue files but vscode-eslint can't.
Is there some configuration I've missed in vscode-eslint ?
Thanks.

**Comment by kaleb** [comment] 2016-08-04 12:20
How do you run eslint from the commandline, and have you set the extensions key in your .vscode/settings.json?

    {
        "eslint.options": {
            "extensions": [".js", ".vue"]
        }
    }

**Comment by er1x** [comment] 2016-08-10 17:59
Same issue here.  It looks like eslint options in settings.json are not being processed. 

I have:

````json
{
    "editor.tabSize": 2,
    "eslint.options": {
        "extensions": [".js", ".vue"]
    }
}
```

Tab size options work, while the other one doesn't.
Using _eslint src/ --ext vue_ from console works, though.

**Comment by Wenzil** [comment] 2016-08-14 05:36
Same problem here

**Comment by luchsamapparat** [comment] 2016-08-16 10:07
It seems I have the same issue when trying to lint TypeScript files:
```
{
    "eslint.options": {
        "extensions": [
            ".js",
            ".ts"
        ]
    }
}
```
Removing `".js"` also has no effect. Other options however, like `useEslintrc`, have an immediate effect.

**Comment by wszgxa** [comment] 2016-09-01 09:53
same problem

**Comment by xmoki** [comment] 2016-09-03 04:06
same problem

**Comment by Franky47** [comment] 2016-09-11 07:58
Same problem here, starting from the vue-cli webpack template.

**Comment by Franky47** [comment] 2016-09-12 07:40
From https://github.com/Microsoft/vscode-eslint/blob/4e19c91826a9cae663d9f09a250863291eec11da/eslint/extension.ts#L141
```typescript
let clientOptions: LanguageClientOptions = {
  documentSelector: ['javascript', 'javascriptreact'],
  ...
```
It appears that this line causes the extension to be working only on files loaded with a language mode of Javascript or Javascript React. Vue files have their own language mode, or sometimes fall back to HTML.

Even if the eslintrc config file or config options in `settings.json` contain the `vue` or `html` ESLint plugins, they won't fire because the extension is not active by default on Vue files.

**Comment by aximario** [comment] 2016-09-14 02:57
same here

**Comment by dbaeumer** [comment] 2016-09-14 13:36
@Franky47 your analysis is 100% correct and the problem is not easy to fix since it is somehow a chicken egg problem. I don't want to activate the extension to eagerly on the other side on the extension could know on which file types it can work. I will think about what we can do to make this smarter. I will require some work on the language client / server library as well to make this work.

**Comment by jdillworth** [comment] 2016-10-26 21:56
I'm having this same issue.

I understand that you don't want to activate the extension too eagerly.

What about a new option like this?:
```
"eslint.documentTypes":["vue", "typescript"]
```

Then we could solve our problem and it would be an "opt-in" situation. The plugin will behave the same as it does today in the absence of the above option.

**Comment by yxqme** [comment] 2016-10-28 04:13
same problem

**Comment by dbaeumer** [comment] 2016-11-04 12:03
Agree, but this needs to get more dynamic since you could change the settings and want eslint to respect this. This is currently not possible with the LSP protocol I use. I am working there to enable this.

**Comment by ifelsee** [comment] 2016-11-09 14:59
same proble

**Comment by sz332** [comment] 2016-11-18 09:35
I have quite similar problem with html files and eslint. I installed eslint-plugin-html, and from command line, the problems are displayed. However, from Visual Studio Code, even with enabled file extensions:

    "eslint.options": {"extensions":[".js", ".html"]}

No error is displayed.

**Comment by dbaeumer** [comment] 2016-12-05 11:38
Closing as a dup of #21 #42.

I am looking for volunteers to test this since it was a bigger code changes. See steps in #42 on how to install the latest version and on how to provide feedback.

**Closed by dbaeumer** 2016-12-05 11:38 UTC
Labels: feature request

**Comment by JzKUO** [comment] 2017-03-08 18:08
format code not working on vue

**Comment by dbaeumer** [comment] 2017-03-09 10:25
@JzKUO what do you mean by format code ? Format vue files? The eslint extension doesn't provide any formatting support at all.

**Comment by lekhnath** [comment] 2017-03-13 17:57
I was trying to lint typescript files using this extension and [typesciprt-eslint-parser](https://github.com/eslint/typescript-eslint-parser) but cannot get to work with .ts files

**Comment by lekhnath** [comment] 2017-03-13 18:01
Solution found #42
