### ISSUE TITLE
Not working with eslint-plugin-import and yarn 3

### ISSUE THREAD

**Issue by brunomacf** [microsoft/vscode-eslint#1494] opened 2022-07-03 20:44 UTC
I'm not sure if this is an issue with eslint-plugin-import or vscode-eslint itself but i created this repo https://github.com/brunomacf/vscode-eslint-yarn-berry reproducing the issue. If i open src/index.ts in vscode i don't see any lint errors (i do see the correct errors when i totally remove the eslint-plugin-import settings from .eslintrc.js config file). But if i run lint manually through yarn lint i see the lint errors just fine (bellow is a screenshot showing on the left the result of yarn lint on the left and on the right vscode showing no lint errors). Any ideas? PS.: I created a similar issue in eslint-plugin-import [here](https://github.com/import-js/eslint-plugin-import/issues/2487)

![Captura de Tela 2022-07-03 às 17 38 08](https://user-images.githubusercontent.com/2754593/177056690-327600d0-cefe-4657-917f-ac54a782cf14.png)

**Comment by dbaeumer** [comment] 2022-07-04 08:00
@brunomacf according to the yarn documentation you need to run `yarn dlx @yarnpkg/sdks vscode` to make yarn pnp work with VS Code (this is not only a general VS Code problem it is that yarn pnp changes the way how node load things).

VS Code then runs eslint from `.yarn/sdks/eslint/lib/api.js`. If I do that on the command line using `node ./.yarn/sdks/eslint/lib/api.js ./src/index.ts` I get actually no errors either. So this seems to be a setup problem with either your workspace or `yarn dlx @yarnpkg/sdks vscode` 

I have to admit that I am not a super expert with `yarn pnp` but in general yarn's sdks for editors worked so far for me.

I am absolutely open for tip on how to improve this for VS Code.

**Comment by brunomacf** [comment] 2022-07-04 11:32
@dbaeumer I don't understand what is going on tbh. If i remove all `eslint-plugin-import` stuff from `.eslintrc.js` file and add a `console.log` call in `src/index.js` i see vscode-eslint complaining about it (screenshot bellow). If `eslint-plugin-import` stuff is in `eslint.js` i can see eslint itself complaining about the `console.log` when running eslint in terminal via `yarn eslint . --ext .ts` (second screenshot bellow) although running eslint via `.yarn/sdks/eslint/lib/api.js` indeed does not show anything. But what intrigues me is the fact that `vscode-eslint` is working when i remove `eslint-plugin-import` stuff.

![Captura de Tela 2022-07-04 às 08 30 32](https://user-images.githubusercontent.com/2754593/177146243-ff6aae26-df69-4b6f-b34e-1aeb8a9e9f63.png)
![Captura de Tela 2022-07-04 às 08 31 10](https://user-images.githubusercontent.com/2754593/177146253-755da8a4-2787-4b0b-8b6a-7643b443ba5c.png)

**Comment by ljharb** [comment] 2022-07-04 15:51
It’s because the import plugin relies on the proper way to resolve things - ie, what node ships - and since pnp breaks this, pnp and the import plugin can’t be used together unless pnp’s workarounds are employed.

**Comment by brunomacf** [comment] 2022-07-04 17:26
@ljharb then why eslint-plugin-import work just fine when i run eslint from command line with `yarn eslint . --ext .ts`? In the screenshot bellow you can see it complains about `import/order` but in vscode there is no error at all:

![Captura de Tela 2022-07-04 às 14 25 30](https://user-images.githubusercontent.com/2754593/177198233-b93f0c2c-aeb4-4544-aa05-7305b7868f2f.png)

**Comment by ljharb** [comment] 2022-07-04 19:12
Because then you’re invoking it with yarn, so yarn is able to hack the runtime to make it work - the editor doesn’t invoke eslint with yarn, it invokes it directly. If you ran `npx eslint` I’d expect it to break in the same way.

**Comment by dbaeumer** [comment] 2022-07-05 06:25
@ljharb thanks for helping me out here. 

@brunomacf one thing you can do is to setup a task that runs eslint through yarn. This would not give you the live feedback but would benefit from yarn setting up the runtime correctly.

Since there is little the extension can do to fix this are you OK to close the issue? I would actually recommend to reopen the issue with the `eslint-plugin-import` pointing out that if you call eslint from the yarn sdk folder the plugin doesn't work correctly.

**Comment by ljharb** [comment] 2022-07-05 06:29
I think this remains an issue with yarn pnp, tbh, but happy to discuss it on that issue as well.

**Comment by JounQin** [comment] 2022-07-06 00:03
Did you try https://github.com/import-js/eslint-import-resolver-typescript? I've just added PnP support at https://github.com/import-js/eslint-import-resolver-typescript/pull/133 to fix https://github.com/import-js/eslint-import-resolver-typescript/issues/130 like this

**Comment by brunomacf** [comment] 2022-07-06 12:09
@JounQin i guess it's release yet right? I just upgraded eslint-import-resolver-typescript to `3.2.4` in https://github.com/brunomacf/vscode-eslint-yarn-berry and i still cant see vscode-eslint complaining about incorrect import order:

![Captura de Tela 2022-07-06 às 09 06 30](https://user-images.githubusercontent.com/2754593/177546306-e8a0b9c4-449a-46bd-89e5-e92f812c188b.png)

As you can see vscode-eslint doesn't even complain about the `console.log` even though i have set `no-console` rule. If i remove all stuff related to eslint-plugin-import from `.eslintrc.js` file then i start seeing vscode-eslint complaining about `console.log`:

![Captura de Tela 2022-07-06 às 09 08 06](https://user-images.githubusercontent.com/2754593/177546792-af94ae95-a5bc-44af-88d0-2d9ab02f6acd.png)

**Comment by JounQin** [comment] 2022-07-06 12:19
@brunomacf Oh, sorry, so the resolving seems working but `vscode-eslint` and `eslint-plugin-import` are not compatible in this case, right?

**Comment by JounQin** [comment] 2022-07-06 12:26
@brunomacf 

`yarn` v3 requires `yarn dlx @yarnpkg/sdks vscode`, I think it may have to patch `eslint-plugin-import` like they do for `eslint`  and `typescript` in this case?

<img width="242" alt="image" src="https://user-images.githubusercontent.com/8336744/177549446-e46afdde-e264-4c37-be4e-dab3341f627e.png">

Maybe you should post issue to https://github.com/yarnpkg/berry/blob/HEAD/packages/yarnpkg-sdks/README.md instead?

**Comment by brunomacf** [comment] 2022-07-06 12:36
@JounQin i've already run `yarn dlx @yarnpkg/sdks vscode`... as you can see here https://github.com/brunomacf/vscode-eslint-yarn-berry/blob/main/.vscode/settings.json#L6 it's already patching eslint. Very weird :(

**Comment by brunomacf** [comment] 2022-07-06 12:38
@JounQin and as i mentioned about the weird thing is: if i run `yarn eslint . --ext .ts` in terminal then eslint-plugin-import seems to be working fine so it seems yarn is patching the env correctly for eslint to work.

![Captura de Tela 2022-07-04 às 14 25 30](https://user-images.githubusercontent.com/2754593/177551885-07b0b254-16d0-49ac-adee-326d76cb8b8d.png)

**Comment by JounQin** [comment] 2022-07-06 12:40
As I mentioned at https://github.com/microsoft/vscode-eslint/issues/1494#issuecomment-1176159721

It's `yarn`'s responsibility to fix this issue with `vscode`, not `vscode-eslint` nor `eslint-plugin-import`.

**Comment by lachlanhunt** [comment] 2022-08-06 03:04
I think I'm also experiencing this same issue. I noticed in the VSCode ESLint Output channel, it shows this error:

```
[Info  - 12:58:00 pm] ESLint server is starting
[Info  - 12:58:00 pm] ESLint server running in node v16.13.2
[Info  - 12:58:00 pm] ESLint server is running.
[Info  - 12:58:01 pm] ESLint library loaded from: /Users/lhunt/Sites/sandbox/.yarn/sdks/eslint/lib/api.js
Uncaught exception received.
Error: Cannot find module '/Users/lhunt/Sites/sandbox/.yarn/__virtual__/eslint-import-resolver-typescript-virtual-948cc217d9/0/cache/eslint-import-resolver-typescript-npm-3.4.0-fc722c19cd-42fa7fbf7a.zip/node_modules/eslint-import-resolver-typescript/lib/worker.mjs'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Module._load (node:internal/modules/cjs/loader:832:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:193:24)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

I also ended up applying a similar fix to kriasoft/react-starter-kit#1984 to exclude the import/* plugins when running inside VSCode.

I also suspect (but can't confirm) this problem may be the root cause of import-js/eslint-import-resolver-typescript#163, which causes VSCode to get stuck while trying to save a file.

**Comment by JounQin** [comment] 2022-08-06 03:12
@lachlanhunt See https://github.com/microsoft/vscode-eslint/issues/1494#issuecomment-1176174288

**Comment by lachlanhunt** [comment] 2022-08-07 14:18
I investigated further and found that specific error I posted above comes from within synckit (a dependency of eslint-import-resolver-typescript), and is thrown from the worker thread it tries to create.

The import resolver is passing synckit the fully resolved path to worker.js, which is correctly resolved to be within the zip file by Yarn PnP. In my case, that's:

```
/Users/lhunt/Sites/sandbox/.yarn/__virtual__/eslint-import-resolver-typescript-virtual-948cc217d9/0/cache/eslint-import-resolver-typescript-npm-3.4.0-fc722c19cd-42fa7fbf7a.zip/node_modules/eslint-import-resolver-typescript/lib/worker.mjs
```

With Yarn PnP setup performed, if you give a path like this to `require(...)`, it handles it correctly and loads it from the zip file. However, when constructing a [`new Worker(...)`](https://nodejs.org/api/worker_threads.html#class-worker), which synckit tries to do, that's not being handled correctly.

I found yarnpkg/berry#2476 which appears to be about this exact issue. But it's had very little attention since it was filed in February 2021.

**Comment by JounQin** [comment] 2022-08-07 16:25
@lachlanhunt See https://github.com/un-ts/synckit/pull/98

**Comment by lachlanhunt** [comment] 2022-08-10 23:28
In my testing, this issue has been resolved by updating to synckit 0.8.3. Thanks to https://github.com/un-ts/synckit/pull/98 and https://github.com/un-ts/synckit/pull/103

**Comment by JounQin** [comment] 2022-08-10 23:57
@brunomacf Can you help to test whether it's working as expected after upgrading?

**Comment by dbaeumer** [comment] 2022-12-05 19:48
I will close the issue since according to the latest comments it got solved in the plugin.

**Closed by dbaeumer** 2022-12-05 19:48 UTC
Labels: info-needed

**Comment by acusti** [comment] 2025-01-30 02:41
i am using yarn PnP and was seeing very similar non-sensical errors to the OP, socfor anyone else like myself who had this problem and found this issue about it, i needed to add `'import/external-module-folders': ['.yarn'],` to my `settings` to get this to work ([details here](https://acusti.ca/blog/2025/01/13/eslint-plugin-import-with-yarn-pnp/)). so my full `settings` object in my `eslint.config.js` file looks like:
```js
    settings: {
        'import/resolver': { typescript: { alwaysTryTypes: true } },
        'import/external-module-folders': ['.yarn'],
    },
```
