### ISSUE TITLE
Writes to settings.json

### ISSUE THREAD

**Issue by nflaig** [microsoft/vscode-eslint#840] opened 2019-12-17 15:52 UTC
The extension keeps writing to the `settings.json` file in the `.vscode` folder.

The written setting is
```json
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }
```

Even after deleting this manually it gets rewritten to the file automatically which means there is no way to remove this besides deactivating or uninstalling the extension.

I would prefer if the extension doesn't write to files automatically. The deprecation warning on the `"eslint.autoFixOnSave": true`  setting and the suggestion to use the other setting should be enough.

**Comment by threehams** [comment] 2019-12-17 17:20
While I appreciate the idea behind this automatic settings migration, it's causing a ton of disruption in my company because we check in a workspace file to the project. _Every branch_ which isn't up to date now has to go through the same process for every person in the company: switch branches, shut down VS Code, pull latest master, start up VS Code again.

Can this be changed to a prompt to update settings automatically?

**Comment by dbaeumer** [comment] 2019-12-17 20:06
I see the problem but there are competing goals. The old setting `eslint.autoFixOnSave` has no effect anymore and I only write into the settings file if that setting exists and is set to true. So you can turn this off by removing `eslint.autoFixOnSave` from the setting.

Without this migration I would have ended up with 100 of issue compaining that auto fix on save is broken.

I do agree that I should add this to the readme to point out how to disable the migration.

**Comment by dbaeumer** [comment] 2019-12-17 20:06
Please be also aware of the isseu https://github.com/microsoft/vscode-eslint/issues/839

**Comment by threehams** [comment] 2019-12-17 20:50
For cases where the settings file isn't checked into the project, this makes sense, but the problem is happening on 400+ branches which are all out of date and have `eslint.autoFixOnSave` into the committed settings file. This means that because of an extension update, we're needing to update all those branches (manually or automatically), with VS Code shut off each time to prevent it from interfering with the merge.

Right now, we're considering forking this extension just to get access to the version without this behavior, but the old version still can't be automatically uninstalled. It's not a great situation to be in.

I'd take pretty much any compromise at this point - a user setting to disable auto-upgrades, for instance. I know I'm not at the only company with a checked-in settings file like this.

**Comment by dbaeumer** [comment] 2019-12-17 22:48
I added a user setting `eslint.migration.2_x` which can be set to `off` to turn this off. But just to be sure: this means that after using eslint 2.x auto fix on save will be disabled and needs to be enabled by changing the settings file you check in. In addition I want to point out that the settings are compatible. So even though the new code action on save setting gets added the old one stays functional. So user can still use eslint 1.9.x and 2.x in parallel on the same workspace. There is no need to migrate all users to the 2.x version.

I did all the coding but it is too late to release this to the market place now. I need to do some additional testing. If you want to give it a try I have uploaded it here: https://github.com/microsoft/vscode-eslint/releases/tag/2.0.7-next.1

**Comment by threehams** [comment] 2019-12-18 01:08
Thank you for the quick update! From local testing the setting is suppressing the upgrade as I switch around branches. Getting a few dozen people to manually update user settings tomorrow shouldn't be a problem.

**Comment by dbaeumer** [comment] 2019-12-18 14:41
I decided to add a confirmation dialog that allows you to disable the update.

**Comment by dbaeumer** [comment] 2019-12-18 15:42
@threehams @nflaig @Andriy-Kulak 

I created a new prerelease 2.0.8 which can be downloaded here: https://github.com/microsoft/vscode-eslint/releases/tag/2.0.8-next.1

This release ask for confirmation before updating and also allows to disable the automatic update globally or per workspace folder.

I would appreciate if you could give it a test run.

**Comment by nflaig** [comment] 2019-12-18 16:21
@dbaeumer 

Thanks for the fast update. I tested the 2.0.8 release in different repositories and it does not update the settings file automatically anymore but it also didn't ask for confirmation to do an automatic update.

**Comment by dbaeumer** [comment] 2019-12-18 16:42
@nflaig it only asks if you had `"eslint.autoiFixOnSave": true` setting. All other settings I was able to keep compatible.

**Comment by nflaig** [comment] 2019-12-18 17:53
@dbaeumer I am have the `"eslint.autoFixOnSave": true` setting but it is not asking if it should the update

**Comment by threehams** [comment] 2019-12-18 17:55
Working for me, at least. I was able to check suppressing at user level and folder level, though I'm not sure where the extension writes information about the folder-level suppression so I couldn't check the rest.

That's a lot of options to choose from. I'm curious what people will select since it's a modal prompt.

**Comment by dbaeumer** [comment] 2019-12-18 20:49
The folder level is stored in a memento store provided by VS Code  to not change anything in the workspace itself. I agree on the number of options but since the dialog will not show up constantly I thought it is better to offer them than taking another short cut.

**Comment by nflaig** [comment] 2019-12-18 22:47
@dbaeumer After doing some more testing I got the dialog where I could disable the automatic update for the current folder but I noticed it is also does not update for other folders now and the dialog does not show up. This could be a problem on my end again I am still not sure what caused the problem I had before.

**Comment by dbaeumer** [comment] 2019-12-20 14:52
@nflaig This is expected as explained in the Readme. If you disable it you can run the command `ESLint: Migrate Settings` manually from the command list

**Comment by dbaeumer** [comment] 2019-12-20 14:52
Publish 2.0.10

**Closed by dbaeumer** 2019-12-20 14:52 UTC
