### ISSUE TITLE
Casing of <lib> does not match the underlying filesystem

### ISSUE THREAD

**Issue by sebelga** [Microsoft/vscode-eslint#400] opened 2018-01-27 08:13 UTC
Hello
I am getting false positive with the plugin on the rule "import/no-unresolved" in Visual Studio Code.

I get "`Casing of <lib> does not match the underlying filesystem`".
But when I run eslint from the command line, I don't get this error.

It is related to https://github.com/benmosher/eslint-plugin-import/issues/720 and seems to have been fixed in version 2.8.0 of "eslint-plugin-import" but I still get the error.

I appreciate the help if anyone knows how to fix this in VS Studio Code 👍

**Comment by dbaeumer** [comment] 2018-02-01 15:40
@sebelga does the problem show up if you run eslint from the terminal as well. If so I would recommend to ask the question in this repository:  benmosher/eslint-plugin-import

**Comment by sebelga** [comment] 2018-02-01 16:10
@dbaeumer I don't get the error in the terminal. Only inside VS studio code.

This is what I get:

![alt text](https://s3.eu-central-1.amazonaws.com/sebelga-tmp/eslint-import-error.png "eslint import error")

**Comment by stoplion** [comment] 2018-03-17 08:38
+1

**Comment by dbaeumer** [comment] 2018-03-19 08:06
@sebelga can you provide me with a GitHub repository I can clone that demos this ? 

Which OS are you on and does the name of the VS Code workspace folder you open match the name on disk in terms of casing?

**Comment by sebelga** [comment] 2018-03-19 08:24
It is related to my repo I guess because other project using eslint don't have this issue.
The repo with errors is https://github.com/sebelga/gstore-node
I was going to copy/paste all file to new files but didn't have time to do it yet.

**Comment by dbaeumer** [comment] 2018-03-19 08:32
This works for me without problems. 

<img width="964" alt="2018-03-19 09_30_53-casing of _lib_ does not match the underlying filesystem issue 400 microsof" src="https://user-images.githubusercontent.com/1931590/37585163-6a2bc8e8-2b58-11e8-9e73-a0e3f0bab33d.png">

**Comment by sebelga** [comment] 2018-03-19 08:35
Interesting... I did clone the project in an new folder though (I got that far :smile: )...
I will do it again and let you know. Thanks for looking into this :+1:

**Comment by ValeryVS** [comment] 2018-05-04 13:41
@dbaeumer 
@sebelga 
I also faced with this issue.
And it can be reproduced only in VS Code.
eslint in terminal doesn't show error.

**Comment by dbaeumer** [comment] 2018-05-07 10:06
@ValeryVS can you provide me with a GitHub repository I can clone that demos the behavior?

**Comment by ValeryVS** [comment] 2018-05-07 10:53
Can't share my project's repo, but I will try to reproduce it in fresh project.

**Comment by ValeryVS** [comment] 2018-05-07 13:46
Actually, my issue is not the same.
I have not `Casing of <lib> ...` error.
#464

**Comment by Hirse** [comment] 2018-05-24 21:06
Looks like this is not an issue (any more), right?

**Comment by sebelga** [comment] 2018-05-25 06:16
Yeah, never found out why only 1 of my project with eslint was giving this issue.

**Comment by dbaeumer** [comment] 2018-05-25 08:32
Great. I will close the issue then.

**Closed by dbaeumer** 2018-05-25 08:32 UTC
Labels: needs more info
