### ISSUE TITLE
eslint extension complains during eslint --init about missing modules

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-eslint#285] opened 2017-08-29 16:32 UTC
https://github.com/Microsoft/vscode/issues/33261

1. `git clone https://github.com/gwtw/js-avl-tree`
2. `code-insiders js-avl-tree`
3. Open integrated terminal
4. Run `eslint --init` and use "standard JS"

![image](https://user-images.githubusercontent.com/2193314/29832340-ba165bda-8c9c-11e7-85d4-365c8a6d6bdc.png)

**Comment by Tyriar** [comment] 2017-08-29 16:33
This actually still happens unexpectedly after reloading the window. Note I'm using a global eslint install but the modules are installed locally.

![image](https://user-images.githubusercontent.com/2193314/29832429-140806b6-8c9d-11e7-9798-734d855b9c8f.png)

**Comment by Tyriar** [comment] 2017-08-29 16:34
`npm i -S eslint` resolves this but it would not be clear how to get rid of the error and get the extension working to many people.

**Comment by dbaeumer** [comment] 2017-08-30 07:50
This also happens in a normal terminal. The problem is that ESLint requires that both the ESLint npm module and all plugins into ESLint are either install globally or locally. You can't have the npm module install globally and the plugins locally.

I know that this is confusing and I get reports / complains about this from time to time but the issue needs to be addressed in ESLint. I usually point people to the ESLint repository.

**Closed by dbaeumer** 2017-08-30 07:50 UTC
