### ISSUE TITLE
ESLint config not found for flat config 

### ISSUE THREAD

**Issue by jonkoops** [microsoft/vscode-eslint#1826] opened 2024-04-09 14:08 UTC
ESLint is unable to initialize due to the configuration not being found in our project.

**Environment**
Visual Studio Code: v1.88.0
Node.js: v21.7.2
ESLint: v8.57.0
ESLint extension: v3.0.5 (pre-release)

**Steps to reproduce**
- Clone [our repository](https://github.com/keycloak/keycloak)
- `corepack enable && pnpm install`
- `pnpm --filter admin-ui build` 
- Open a random file (in my case `js/apps/admin-ui/src/realm-settings/PoliciesTab.tsx`)

**Expected behaviour**
Plugin finds the ESLint configuration in `js/eslint.config.js`.

**Actual behaviour**
Plugin attempts the ESLint configuration in `js/apps/admin-ui/src/realm-settings`, which doesn't exist and logs the following stack:

```log
Error: No ESLint configuration found in /home/jon/Projects/redhat/keycloak/js/apps/admin-ui/src/realm-settings.
    at CascadingConfigArrayFactory._finalizeConfigArray (/home/jon/Projects/redhat/keycloak/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:4000:19)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/home/jon/Projects/redhat/keycloak/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3791:21)
    at CLIEngine.isPathIgnored (/home/jon/Projects/redhat/keycloak/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/cli-engine/cli-engine.js:1000:18)
    at ESLint.isPathIgnored (/home/jon/Projects/redhat/keycloak/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/eslint/eslint.js:681:26)
    at /home/jon/.vscode/extensions/dbaeumer.vscode-eslint-3.0.5/server/out/eslintServer.js:1:24250
    at Object.M [as withClass] (/home/jon/.vscode/extensions/dbaeumer.vscode-eslint-3.0.5/server/out/eslintServer.js:1:19760)
    at async O.then.m.validate (/home/jon/.vscode/extensions/dbaeumer.vscode-eslint-3.0.5/server/out/eslintServer.js:1:24202)
    at async /home/jon/.vscode/extensions/dbaeumer.vscode-eslint-3.0.5/server/out/eslintServer.js:1:233288
    at async /home/jon/.vscode/extensions/dbaeumer.vscode-eslint-3.0.5/server/out/eslintServer.js:1:63833
```

**Comment by newoga** [comment] 2024-04-10 07:14
@jonkoops I tried this reproduction myself because I'm now seeing/troubleshooting a separate weird behavior with flat configurations in my pnpm monorepo.

However, in the case of the keycloak repository, it looks like the plugin is unable to find the `eslint.config.js` file because it's in the `js` directory (the plugin looks for configurations relative to the working directory). It seems like you have two options:

1. Move the `eslint.config.js` file into the repository root (probably less desirable in your case)
2. Add the `js` directory to this extension's `eslint.workingDirectories` setting (for example, via a workspace configuration)


`<repository-root>/.vscode/settings.json`:
```json
 {
  "eslint.workingDirectories": ["js"]
}
```

**Comment by dbaeumer** [comment] 2024-04-10 09:29
@newoga thanks for providing the great answer.

@jonkoops you should move to `ESLint v8.57.0`. This one has special API I an use to better detect flat config files. Might even be possible that the `eslint.workingDirecotries` setting is not necessary with that version.

Let me know how it goes.

**Comment by jonkoops** [comment] 2024-04-10 11:22
> you should move to `ESLint v8.57.0`. This one has special API I an use to better detect flat config files. Might even be possible that the `eslint.workingDirectories` setting is not necessary with that version.

Turns out the version in my lock-file was already on that one (updated my original post), but it seems that the issue remains the same. Adding `eslint.workingDirectories` does seem to resolve this issue, so we'll use that for now.

> However, in the case of the keycloak repository, it looks like the plugin is unable to find the `eslint.config.js` file because it's in the `js` directory (the plugin looks for configurations relative to the working directory). It seems like you have two options:

Interesting, how exactly does this resolution work? I would expect that it would walk up the directory tree until it finds a configuration file, in which case it should be able to find the config in our project because the `js` directory which contains the configuration is one of the parent directories.

**Comment by newoga** [comment] 2024-04-10 14:27
> Interesting, how exactly does this resolution work? I would expect that it would walk up the directory tree until it finds a configuration file, in which case it should be able to find the config in our project because the js directory which contains the configuration is one of the parent directories.

@jonkoops I'm also trying to understand this better. However, to no fault of the authors/maintainers, I can't imagine this would be a simple answer due to the number of permutations across eslint versions, project setups, and extension configurations. 😄 

For example, yesterday I was troubleshooting a separate issue issue where errors were detected _once_ for open files when the eslint configuration would change, but detections never occurred after. After finding the root cause for your repository, I ended up with this solution for mine:

```json
{
  "eslint.workingDirectories": [{ "mode": "auto" }]
}
```

This configuration (similar to the one suggested to you) also worked:

```json
{
  "eslint.workingDirectories": { "pattern": "./packages/*/" }
}
```

I'm still don't understand what the root cause was and why the default extension configuration did not suffice, however the extension documentation does suggest reviewing this `workingDirectories` setting carefully.

**Comment by dbaeumer** [comment] 2024-04-11 07:54
@jonkoops I looked at your repository and here is what is happening. ESLint changed the lookup algorithm form rc files to flat config files. RC files where searched upwards from the directory containing the file you are validating. Flat configs are searched upwards from the current working directory (note this is the behaviour of ESLint not the eslint extension for VS Code).

Since the `eslint.config.js` file is in the `js` directory and the working directory in be default the workspace folder the eslint npm module doesn't find the configuration files. The `workingDirectories` setting instructs the extension to use `js` as a working directory for files below the `js` directory hence the file is found.

Hope that explains the behavior. I will close the issue since you have the same behavior on the command line

![Image](https://github.com/microsoft/vscode-eslint/assets/1931590/69ffcf77-9a4a-46b6-aabf-1bcda03a4f2c)

I will close the issue since this is the new default behavior of the flat config system.

**Closed** 2024-04-11 07:54 UTC
Labels: info-needed

**Comment by jonkoops** [comment] 2024-04-11 14:25
Thanks @dbaeumer, appreciate the thorough research. Looks like the best solution is likely to start moving my ESLint config to the root directory then.

**Comment by shubham43MP** [comment] 2024-07-21 06:00
Alternativey you can also do some similar tweaks in .vscode/settings.json

```
    "eslint.useFlatConfig": true,
    "eslint.options": {
      "overrideConfigFile": "./eslint.config.mjs"
    },
```

Although the above answers given worked for me at some point or the other
